# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "qfdmo"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "default"

flags:
  send_anonymous_usage_stats: false

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

on-run-start:
  - "{{ create_udf_encode_base57() }}"
  - "{{ create_udf_uuid_to_int() }}"
  - "{{ create_udf_safe_divmod() }}"
  - "{{ create_udf_columns_concat_unique_non_empty() }}"
  - "{{ create_udf_normalize_string_alpha_for_match() }}"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +unlogged: true
  base:
    schema: public
    +materialized: view
  intermediate:
    schema: public
    +materialized: view
  marts:
    +materialized: table
    exhaustive:
      schema: public
    carte:
      schema: public
    opendata:
      schema: public
  exposure:
    +materialized: table
    exhaustive:
      schema: public
    carte:
      schema: public
    opendata:
      schema: public
