default:
  target: qfdmo
  outputs:
    qfdmo:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 6543) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'qfdmo') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'qfdmo') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'qfdmo') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
    # To implement sampling logic for large tables
    # (e.g. Annuaire Entreprises Etablissements = 40M rows)
    # Each model is free to implement its own sampling strategy
    # using {% if target.name == 'sampling' %}...{% endif %}
    sampling:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 6543) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'qfdmo') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'qfdmo') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'qfdmo') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"