default:
  target: warehouse
  outputs:
    warehouse:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 8765) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'warehouse') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'warehouse') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'warehouse') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
