"""
Django base settings for quefairedemesobjets project.

Shared by all deployment profiles (dev, production, airflow, test).
Profile-specific overrides go in dev.py / production.py / airflow.py / test_settings.py.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse

import decouple
import dj_database_url
from import_export.formats.base_formats import CSV, XLS, XLSX

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Assistant settings
# ------------------
ASSISTANT = {
    "MATOMO_ID": decouple.config("ASSISTANT_MATOMO_ID", default=82, cast=int),
    "POSTHOG_KEY": decouple.config(
        "ASSISTANT_POSTHOG_KEY",
        default="phc_fSfhoWDOUxZdKWty16Z3XfRiAoWd1qdJK0N0z9kQHJr",  # pragma: allowlist secret  # noqa: E501
        cast=str,
    ),
}

# Carte settings
# --------------
CARTE = {
    "MATOMO_ID": decouple.config("LVAO_MATOMO_ID", default=50, cast=int),
    "GOOGLE_SEARCH_CONSOLE": "google9dfbbc61adbe3888.html",
    "DECLARATION_ACCESSIBILITE_PAGE_ID": decouple.config(
        "CARTE_DECLARATION_ACCESSBILITE_PAGE_ID",
        default=177,
        cast=int,
    ),
}
DEFAULT_MAX_SOLUTION_DISPLAYED = decouple.config(
    "DEFAULT_MAX_SOLUTION_DISPLAYED", cast=int, default=10
)
CARTE_MAX_SOLUTION_DISPLAYED = decouple.config(
    "CARTE_MAX_SOLUTION_DISPLAYED", cast=int, default=100
)
DISTANCE_MAX = decouple.config("DISTANCE_MAX", cast=int, default=30000)

NB_CORRECTION_DISPLAYED = decouple.config(
    "NB_CORRECTION_DISPLAYED", cast=int, default=100
)

STATS = {
    "POSTHOG_BASE_URL": decouple.config(
        "POSTHOG_API_URL",
        default="https://eu.posthog.com",
        cast=str,
    ),
    "POSTHOG_PROJECT_ID": decouple.config(
        "POSTHOG_STATS_PROJECT_ID",
        default=23277,
        cast=int,
    ),
    "POSTHOG_PERSONAL_API_KEY": decouple.config(
        "POSTHOG_PERSONAL_API_KEY",
        default="dummy_posthog_key",
        cast=str,
    ),
}

# Security
# --------
SECRET_KEY = decouple.config("SECRET_KEY")
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# SECURE_PROXY_SSL_HEADER / USE_X_FORWARDED_HOST / USE_X_FORWARDED_PORT
# are set in production.py (only meaningful behind a reverse proxy with HTTPS).
BLOCK_ROBOTS = decouple.config("BLOCK_ROBOTS", default=False, cast=bool)
ENVIRONMENT = decouple.config("ENVIRONMENT", default="development", cast=str)
VERSION = decouple.config("CONTAINER_VERSION", default="version", cast=str)
APP = decouple.config("APP", default="local", cast=str)
BASE_URL = decouple.config(
    "BASE_URL",
    default="http://quefairedemesdechets.ademe.local",
    cast=str,
)
BASE_HOST = urlparse(BASE_URL).hostname
ALLOWED_HOSTS = [
    BASE_HOST,
    *decouple.config("ALLOWED_HOSTS", default="", cast=str).split(","),
]

# Application definition
# ----------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sitemaps",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.postgres",
    "django_extensions",
    "import_export",
    "widget_tweaks",
    "dsfr",
    "django.forms",
    "colorfield",
    "core",
    "stats",
    "search",
    "qfdmd",
    "qfdmo",
    "infotri",
    "data",
    "adminsortable2",
    "corsheaders",
    "django_lookbook",
    "djangoql",
]

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# RGAA 11.10 : marque les champs facultatifs avec « (Optional) » plutôt que
# les champs obligatoires avec un astérisque, conformément à la
# recommandation DSFR
DSFR_MARK_OPTIONAL_FIELDS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "qfdmd.middleware.RequestEnhancementMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "qfdmd.middleware.BetaMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "qf_django_cache",
    },
}

X_FRAME_OPTIONS = "ALLOWALL"

# Logging
# -------
# Override via LOGLEVEL env var (default: INFO).

LOGLEVEL = decouple.config(
    "LOGLEVEL",
    default="info",
    cast=str,
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"hide_staticfiles": {"()": "core.logging.SkipStaticFilter"}},
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "default": {
            "format": "[%(asctime)s] [%(name)s] [%(levelname)s] : %(message)s",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
            "level": LOGLEVEL,
        },
        "qfdmo": {
            "handlers": ["console"],
            "level": LOGLEVEL,
        },
        "data": {"handlers": ["console"], "level": LOGLEVEL},
        "qfdmd": {"handlers": ["console"], "level": LOGLEVEL},
    },
}
# In dev.py the hide_staticfiles filter is added back; in production it stays off.

ROOT_URLCONF = "core.urls"


def context_processors():
    return [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
        "core.context_processors.environment",
        "core.context_processors.content",
        "core.context_processors.global_context",
        "dsfr.context_processors.site_config",
    ]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                *context_processors(),
                # Sites faciles
                "wagtail.contrib.settings.context_processors.settings",
                "wagtailmenus.context_processors.wagtailmenus",
                "sites_conformes.content_manager.context_processors.skiplinks",
                "sites_conformes.content_manager.context_processors.mega_menus",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# EMAIL_BACKEND — overridden in dev.py (console) and production.py (SMTP via env)


# Database
# --------
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASE_URL = decouple.config(
    "DATABASE_URL",
    default="postgis://webapp:webapp@localhost:6543/qfdmo",  # pragma: allowlist secret  # noqa: E501
    cast=str,
)

DEFAULT_DATABASE_SETTINGS = {
    **dj_database_url.parse(DATABASE_URL),
    "ENGINE": "django.contrib.gis.db.backends.postgis",
}

DB_WEBAPP_SAMPLE = decouple.config(
    "DB_WEBAPP_SAMPLE",
    default="postgis://webapp_sample:webapp_sample@localhost:6543/webapp_sample",  # pragma: allowlist secret  # noqa: E501
    cast=str,
)

WEBAPP_SAMPLE_DATABASE_SETTINGS = {
    **dj_database_url.parse(DB_WEBAPP_SAMPLE),
    "ENGINE": "django.contrib.gis.db.backends.postgis",
}

DB_WAREHOUSE = decouple.config(
    "DB_WAREHOUSE",
    cast=str,
    default="postgis://warehouse:warehouse@localhost:6543/warehouse",  # pragma: allowlist secret  # noqa: E501
)

WAREHOUSE_DATABASE_SETTINGS = {
    **dj_database_url.parse(DB_WAREHOUSE),
    "ENGINE": "django.contrib.gis.db.backends.postgis",
}

DATABASES = {
    "default": DEFAULT_DATABASE_SETTINGS,
    "warehouse": WAREHOUSE_DATABASE_SETTINGS,
    "webapp_sample": WEBAPP_SAMPLE_DATABASE_SETTINGS,
}

REMOTE_WEBAPP_SERVERNAME = "webapp_server"
REMOTE_WEBAPP_SCHEMANAME = "webapp_public"
REMOTE_WAREHOUSE_SERVERNAME = "warehouse_server"
REMOTE_WAREHOUSE_SCHEMANAME = "warehouse_public"

CONN_HEALTH_CHECKS = True
CONN_MAX_AGE = decouple.config("CONN_MAX_AGE", cast=int, default=0)


# Password validation
# -------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "admin:login"


# Internationalization
# --------------------
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = "fr"
USE_L10N = True

WAGTAIL_I18N_ENABLED = True

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("en", "English"),
    ("fr", "Français"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# --------------------------------------
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static" / "to_collect",
    BASE_DIR / "static" / "compiled",
]

WHITENOISE_KEEP_ONLY_HASHED_FILES = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Production uses S3Storage for default — overridden in production.py.

# Import / export settings
# ------------------------
IMPORT_EXPORT_TMP_STORAGE_CLASS = "import_export.tmp_storages.MediaStorage"
IMPORT_FORMATS = [CSV, XLSX, XLS]
DJANGO_IMPORT_EXPORT_LIMIT = decouple.config(
    "DJANGO_IMPORT_EXPORT_LIMIT", cast=int, default=1000
)


# Tally form ids
# --------------
ADDRESS_SUGGESTION_FORM = decouple.config(
    "ADDRESS_SUGGESTION_FORM", default="https://tally.so/r/wzy9ZZ", cast=str
)
UPDATE_SUGGESTION_FORM = decouple.config(
    "UPDATE_SUGGESTION_FORM", default="https://tally.so/r/3xMqd9", cast=str
)
FEEDBACK_FORM = decouple.config(
    "FEEDBACK_FORM", default="https://tally.so/r/3EW88q", cast=str
)
CONTACT_FORM = decouple.config(
    "CONTACT_FORM", default="https://tally.so/r/wzYveR", cast=str
)
ASSISTANT_SURVEY_FORM = decouple.config(
    "ASSISTANT_SURVEY_FORM", default="https://tally.so/r/wvNgx0", cast=str
)

# Notion settings
# --------------
NOTION = {
    "TOKEN": decouple.config("NOTION_TOKEN", default=""),
    "CONTACT_FORM_DATABASE_ID": decouple.config(
        "NOTION_CONTACT_FORM_DATABASE_ID", default=""
    ),
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = decouple.config(
    "DATA_UPLOAD_MAX_NUMBER_FIELDS", default=10000, cast=int
)


# Wagtail settings
# ----------------
SILENCED_SYSTEM_CHECKS = ["wagtailadmin.W002"]
HOST_PROTO = decouple.config("HOST_PROTO", default="https")
WAGTAIL_SITE_NAME = "Que faire de mes objets et déchets"
WAGTAILADMIN_BASE_URL = BASE_URL
WAGTAIL_AUTOSAVE_INTERVAL = 0
WAGTAIL_EDITING_SESSION_PING_INTERVAL = 30000
MODELSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "modelsearch.backends.database",
        "SEARCH_CONFIG": "wagtail_french",
        "FUZZY_ALGORITHM": "trigram",
        "FUZZY_SIMILARITY_THRESHOLD": 0.2,
        "FUZZY_PREFIX_BOOST": 0.5,
    }
}

INSTALLED_APPS.extend(
    [
        # Sites faciles
        "sites_conformes",
        "sites_conformes.core",
        "sites_conformes.menus",
        "sites_conformes.blog",
        "sites_conformes.content_manager",
        "sites_conformes.events",
        "wagtail.contrib.settings",
        "sites_conformes.forms",
        "wagtail_modeladmin",
        "wagtailmenus",
        "wagtail_localize",
        "wagtail_localize.locales",
        "wagtailmarkdown",
        "wagtail_honeypot",
        # wagtail
        "wagtail.contrib.forms",
        "wagtail.contrib.redirects",
        "wagtail.embeds",
        "wagtail.sites",
        "wagtail.users",
        "wagtail.snippets",
        "wagtail.documents",
        "wagtail.images",
        "modelsearch",
        "wagtail.admin",
        "wagtail.contrib.typed_table_block",
        "wagtail",
        "wagtail.contrib.routable_page",
        "modelcluster",
        "taggit",
    ]
)
WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MIDDLEWARE.extend(
    [
        "wagtail.contrib.redirects.middleware.RedirectMiddleware",
        "django.middleware.locale.LocaleMiddleware",
    ]
)


# UI
# ---
LOOKBOOK = {
    "preview_base": ["previews"],
    "show_previews": decouple.config("SHOE_PREVIEWS", default=True, cast=bool),
}
