# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "uv"
    directories:
      - "/webapp"
      - "/data-platform"
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00" # UTC
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
  - package-ecosystem: "npm"
    directory: "/webapp"
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:15" # UTC
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
    groups:
      babel:
        patterns:
          - "@babel/*"
      parcel:
        patterns:
          - "@parcel/*"
          - "parcel"
      protobufjs:
        patterns:
          - "@protobufjs/*"
          - "protobufjs"
      swc:
        patterns:
          - "@swc/*"
          - "swc"
      mapbox:
        patterns:
          - "@mapbox/*"
          - "mapbox*"
      sentry:
        patterns:
          - "@sentry/*"
          - "sentry*"
      jest:
        patterns:
          - "*jest*"
      eslint:
        patterns:
          - "*eslint*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:30" # UTC
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
  - package-ecosystem: "terraform"
    directories:
      - "/infrastructure/modules/*"
      - "/infrastructure/environments/*/*"
    open-pull-requests-limit: 100
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:45" # UTC
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
