/*
Schema generated by scripts/db_schema_create_from_csv.py
 - Strict on ID-like fields (e.g. siren, siret etc...)
 - Loose on other fields to avoid pipeline failures for variable data
 - VARCHAR for the same reason we don't control the data
 - {{table_name}} so that no one can run this by mistake AND
    to facilitate table name replacement in Python
 - Indexes to improve performance

*/

CREATE TABLE {{table_name}} (
  "code_commune" VARCHAR(5), -- 🟡 on reste scrict
  "nom_commune" VARCHAR(100), -- 100 -> 150
  "code_arrondissement" VARCHAR(4), -- 🟡 on reste scrict
  "nom_arrondissement" VARCHAR(100), -- 100 -> 150
  "code_departement" VARCHAR(3), -- 🟡 on reste scrict
  "nom_departement" VARCHAR(100), -- 100 -> 150
  "code_epci" VARCHAR(9), -- 🟡 on reste scrict
  "nom_epci" VARCHAR(100), -- 100 -> 150
  "code_region" VARCHAR(2), -- 🟡 on reste scrict
  "nom_region" VARCHAR(100), -- 100 -> 150
  "code_aire_d_attraction_des_villes" VARCHAR(3), -- 🟡 on reste scrict
  "nom_aire_d_attraction_des_villes" VARCHAR(100), -- 100 -> 150
  "code_bassin_de_vie" VARCHAR(5), -- 🟡 on reste scrict
  "nom_bassin_de_vie" VARCHAR(100), -- 100 -> 150
  "code_unite_urbaine" VARCHAR(5), -- 🟡 on reste scrict
  "nom_unite_urbaine" VARCHAR(100), -- 100 -> 150
  "code_zone_d_emploi" VARCHAR(5), -- 🟡 on reste scrict
  "nom_zone_d_emploi" VARCHAR(100) -- 100 -> 150
);

/* Constraints
Just to verify that our import is working correctly
*/
ALTER TABLE {{table_name}}
ADD CONSTRAINT pk_{{table_name}} PRIMARY KEY (code_commune);
