name: 🌚 CD

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: 🤖 CI
    uses: ./.github/workflows/ci.yml

  airflow_docker:
    name: 🐳 Airflow Docker
    uses: ./.github/workflows/airflow_docker.yml

  webapp:
    name: 🟠 Webapp
    uses: ./.github/workflows/_deploy-webapp.yml
    secrets: inherit # pragma: allowlist secret`
    needs: [ci]
    with:
      environment: preprod

  airflow:
    name: 🟠 Airflow
    uses: ./.github/workflows/_deploy-airflow.yml
    secrets: inherit # pragma: allowlist secret`
    needs: [ci, airflow_docker]
    with:
      environment: preprod

  # Common release-drafter configuration
  # From https://github.com/marketplace/actions/release-drafter
  # Uncomment when anchor are supported in GitHub Actions
  # See : https://github.com/actions/runner/issues/1182
  # _release_drafter: &release_drafter
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   name: 🔢 Release
  #   steps:
  #     - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
  #       with:
  #         config-name: release-config.yml
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Standard release draft update
  update_release_draft:
    # Uncomment when anchor are supported in GitHub Actions
    # See : https://github.com/actions/runner/issues/1182
    # <<: *release_drafter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: 🔢 Release
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [webapp]
    if: ${{ !contains( github.ref_name, 'hotfix') }}

  # Hotfix-only release draft update
  update_release_draft_for_hotfix:
    # Uncomment when anchor are supported in GitHub Actions
    # See : https://github.com/actions/runner/issues/1182
    # <<: *release_drafter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: 🔢 Release
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ contains( github.ref_name, 'hotfix') }}
