name: Setup Frontend Environment
description: Install Node.js and npm dependencies

inputs:
  build:
    description: "Build frontend assets"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".tool-versions"
        cache: "npm"
        cache-dependency-path: "webapp/package-lock.json"

    - name: Install npm dependencies
      shell: bash
      run: npm ci
      working-directory: webapp

    - name: Build assets
      if: inputs.build == 'true'
      shell: bash
      run: npm run build
      working-directory: webapp
