name: Setup Frontend Environment
description: Install Node.js and npm dependencies

inputs:
  build:
    description: "Build frontend assets"
    required: false
    default: "false"
  working-directory:
    description: "Working directory"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".tool-versions"
        cache: "npm"
        cache-dependency-path: ${{ inputs.working-directory && format('{0}/package-lock.json', inputs.working-directory) || 'package-lock.json' }}

    - name: Install npm dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}

    - name: Build assets
      if: inputs.build == 'true'
      shell: bash
      run: npm run build
      working-directory: ${{ inputs.working-directory }}
