name: "Setup Frontend Environment"
description: "Installs Node.js and npm dependencies with caching"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".tool-versions"
        cache: "npm"

    - name: Install npm dependencies
      run: npm ci
      shell: bash
