/*
Schema generated by scripts/db_schema_create_from_csv.py
 - Strict on ID-like fields (e.g. siren, siret etc...)
 - Loose on other fields to avoid pipeline failures for variable data
 - VARCHAR for the same reason we don't control the data
 - {{table_name}} so that no one can run this by mistake AND
    to facilitate table name replacement in Python
 - Indexes to improve performance

*/

CREATE TABLE {{table_name}} (
  "TYPECOM" VARCHAR(4), -- 🟡 on reste scrict : COM ou COMD
  "COM" VARCHAR(5), -- 🟡 on reste scrict
  "REG" VARCHAR(2), -- 🟡 on reste scrict
  "DEP" VARCHAR(3), -- 🟡 on reste scrict
  "CTCD" VARCHAR(4), -- 🟡 on reste scrict
  "ARR" VARCHAR(4), -- 🟡 on reste scrict
  "TNCC" VARCHAR(5), -- 🟡 on reste scrict
  "NCC" VARCHAR(100), -- 🟡 on reste scrict
  "NCCENR" VARCHAR(100), -- 🟡 on reste scrict
  "LIBELLE" VARCHAR(100), -- 100 -> 150
  "CAN" VARCHAR(5), -- 🟡 on reste scrict
  "COMPARENT" VARCHAR(5) -- 🟡 on reste scrict
);
