# Generated by Django 5.1.1 on 2024-10-12 07:55
# inspired by https://github.com/django/django/blob/e03440291b0599934da73b7dfbd2ccf7ec7270d8/django/core/management/commands/inspectdb.py

from django.apps import apps
from django.core.management.base import BaseCommand

from core.models.tools import compare_model_vs_table


class Command(BaseCommand):
    help = """
Compare les champs d'un modèle Django avec les colonnes d'une table de base de données
"""

    def add_arguments(self, parser):

        parser.add_argument(
            "--model_name", type=str, help="Nom du modèle Django (ex: DisplayedActeur)"
        )

        parser.add_argument(
            "--table_name", type=str, help="Nom de la table (ex: exposure_carte_acteur)"
        )

    def handle(self, *args, **options):
        model_name = options["model_name"]
        table_name = options["table_name"]

        try:
            model_class = apps.get_model("qfdmo", model_name)
        except LookupError:
            self.stdout.write(self.style.ERROR(f"Le modèle {model_name} n'existe pas"))
            return

        if compare_model_vs_table(model_class, table_name):
            self.stdout.write(self.style.SUCCESS("✓"))
        else:
            self.stdout.write(self.style.ERROR("✗"))
