import logging

from django.core.management.base import BaseCommand

from qfdmo.models import Objet, SousCategorieObjet

objet_list = [
    [
        "179 : autre équipement électronique",
        "Accessoire automobile (et deux-roues) électronique",
        "Détecteur radar",
        "Radar de stationnement",
        "Allume-cigare",
    ],
    [
        "199 : matériel Médical",
        "Aiguille usagée (médicale)",
        "Aiguille à stylo",
        "Aiguille de transfert",
        "Aiguille seule (médicale)",
    ],
    ["178 : matériel Photo/ciné", "Appareil photo jetable", "Appareil photo"],
    ["178 : matériel Photo/ciné", "Appareil photo numérique"],
    [
        "194 : article De Maroquinerie",
        "Articles en cuir (hors chaussures)",
        "Ceinture en cuir",
        "Gants en cuir",
        "Portefeuille en cuir",
        "Sacoche en cuir",
        "Sac à main en cuir",
        "Maroquinerie",
        "Blouson en cuir",
        "Pantalon en cuir",
        "Bracelet en cuir",
    ],
    [
        "172 : gros Appareil électroménager Hors Froid",
        "Aspirateur",
        "Equipement d'entretien",
    ],
    ["177 : matériel Hifi/vidéo", "Autoradio", "Radio"],
    ["177 : matériel Hifi/vidéo", "Baladeur", "Walkman", "MP3"],
    [
        "179 : autre équipement électronique",
        "Batterie (hors batterie de voiture)",
        "Accumulateur",
    ],
    ["189 : article De Vaisselle", "Biberon en plastique", "Biberon"],
    ["196 : bijou/montre", "Bijou fantaisie (accessoires de mode)"],
    ["198 : autre Matériel De Sport", "Bodyboard", "Surf"],
    [
        "195 : paire De Chaussures",
        "Bottes en caoutchouc",
        "Bottes de pluie",
        "Bottes de pêche",
    ],
    ["186 : objet De Décoration", "Bougie en cire", "Chandelle", "Cierge", "Bougie"],
    ["198 : autre Matériel De Sport", "Bouteille de plongée"],
    ["185 : meuble", "Canapé", "Canapé-lit"],
    ["173 : petit Appareil électroménager", "Carte RFID", "Clé RFID"],
    [
        "173 : petit Appareil électroménager",
        "Carte à puce (bancaire, de téléphone, d'identité)",
    ],
    [
        "173 : petit Appareil électroménager",
        "Cartouche d'impression (à jet d'encre, laser)",
    ],
    ["198 : autre Matériel De Sport", "Casque"],
    ["199 : matériel Médical", "Cathéter", "Cathéter tout en un"],
    [
        "180 : CD/DVD/jeu Vidéo",
        "CD/DVD, cassette (avec ou sans boîtier)",
        "Blu-ray",
        "CD-ROM",
        "Disque (album)",
        "CD",
        "DVD",
        "CDRom",
    ],
    ["179 : autre équipement électronique", "Chargeur"],
    ["172 : gros Appareil électroménager Hors Froid", "Chauffe-eau"],
    [
        "195 : paire De Chaussures",
        "Chaussures",
        "Bottes",
        "Bottines",
        "Baskets",
        "Tennis",
        "Chaussons",
        "Pantoufles",
        "Savattes",
        "Souliers",
        "Après-ski",
        "Babouches",
        "Boots",
        "Escarpins",
        "Mocassins",
        "Nu-pieds",
        "Tongs",
        "Sabots",
        "Sandales",
        "Snow-boot",
        "Ballerines",
    ],
    ["179 : autre équipement électronique", "Cigarette électronique", "puff"],
    ["176 : matériel Informatique", "Clé USB"],
    ["198 : autre Matériel De Sport", "Corde usée"],
    ["189 : article De Vaisselle", "Couteau de cuisine", "Canif"],
    ["189 : article De Vaisselle", "Couverts en métal"],
    ["171 : gros Appareil électroménager Froid", "Cuisinière électrique"],
    ["174 : écran", "Écran informatique", "écran"],
    [
        "173 : petit Appareil électroménager",
        "Équipement Électrique et Électronique (EEE)",
        "Rasoir électrique",
        "Caméscope",
        "Chaîne hi-fi",
        "Enceinte",
        "Radio-réveil",
        "Répondeur",
        "Jouet télécommandé",
        "Lampe torche",
        "Barbecue électrique",
        "Machine à coudre",
        "Magnétoscope",
        "Jouet électrique",
        "Scie sauteuse",
        "Réveil matin",
        "Machine à pain",
        "Télécommande",
    ],
    ["172 : gros Appareil électroménager Hors Froid", "Four électrique"],
    ["193 : vêtement", "Fourrure naturelle"],
    ["193 : vêtement", "Fourrure synthétique"],
    ["172 : gros Appareil électroménager Hors Froid", "Gazinière"],
    ["189 : article De Vaisselle", "Gourde"],
    [
        "179 : autre équipement électronique",
        "GPS",
        "Avertisseur de radars",
        "Assistant de conduite",
    ],
    [
        "171 : gros Appareil électroménager Froid",
        "Gros électroménager",
        "Congélateur",
        "Freezer",
        "Lave-vaisselle",
        "Sèche-linge",
        "Hotte",
        "Plaque de cuisson",
        "Climatiseur",
    ],
    ["173 : petit Appareil électroménager", "Guirlande électrique"],
    ["172 : gros Appareil électroménager Hors Froid", "Halogène"],
    ["177 : matériel Hifi/vidéo", "Haut-parleurs", "Enceintes", "Baffles"],
    ["176 : matériel Informatique", "Imprimante"],
    [
        "182 : instrument De Musique",
        "Instrument de musique électrique",
        "Instrument de musique électronique",
        "Guitare électrique",
        "Synthétiseur",
        "Piano électrique",
    ],
    ["193 : vêtement", "Jean"],
    ["180 : CD/DVD/jeu Vidéo", "Jeu vidéo (cassette ou cartouche DS, PS3, Xbox...)"],
    [
        "192 : jouet",
        "Jouet (non électronique)",
        "Jeu de société",
        "Jeu (non électrique)",
        "Figurine",
        "Jeu de construction",
        "Poupon",
        "Poupée",
        "Accessoires pour poupon ou poupée",
        "Poupée mannequin",
        "Maison de poupée",
        "Mobilier de poupée",
        "Vêtements de poupon ou poupée",
        "Peluche",
        "Marionnette",
        "marionnette",
        "Décor de marionnettes",
        "Jouet premier âge",
        "Jeu d'imitation",
        "Jouet à promener",
        "Jouet à pousser",
        "Jouet de bain",
        "Jouet éducatif",
        "Mobile",
        "Véhicule miniature",
        "Voiture non motorisé",
        "Camion non motorisé",
        "Avion non motorisé",
        "Bateau non motorisé",
        "Véhicule à friction",
        "Pâte à modeler",
        "Ballon de baudruche",
        "Carte à collectionner",
        "Vignette à collectionner",
        "Costume d'enfant (- de 14 ans)",
        "Décor pour figurines",
        "Instrument de musique jouet",
        "Farces et attrapes",
        "Jeu de magie",
        "Jeu scientifique",
        "Jeu de chimiste",
        "Porteur (jouet)",
        "tricycle enfant (jouet)",
        "Skateboard d'enfant (jouet)",
        "Trottinette enfant (jouet)",
        "Bicyclette enfant (jouet)",
        "Ensemble cosmétique pour enfant (jouet)",
        "Babyfoot pour enfant (jouet)",
        "Arme factice (jouet)",
        "Echasse",
        "Ballon sauteur",
        "Pelle à neige (luge)",
        "Pataugette",
        "J'eu d'eau",
        "Pistolet à eau",
        "Maison de jardin pour enfant",
        "Trampoline (jouet)",
        "Toboggan",
        "Casse-tête",
        "Jeu de cartes",
        "Jeu de dés",
        "Jeu de plateau",
        "Jeu de stratégie",
        "Jeu de voyage",
        "Puzzle",
        "Maquette",
        "Jeu (non électronique)",
        "Jeu de plage",
        "Jeu de sable (seau, pelle, râteau...)",
        "Draisienne",
        "Loisirs créatifs pour enfants (jouet)",
        "Articles de sport d'extérieur pour enfant (jouet : raquette, boule de pétanque en plastique...)",
        "Luge d'enfant (jouet)",
    ],
    ["187 : luminaire", "Lampe (ou luminaire) sans ampoule", "Lustre"],
    ["177 : matériel Hifi/vidéo", "Lecteur DVD"],
    ["187 : luminaire", "LED", "Lampe à LED"],
    [
        "186 : objet De Décoration",
        "Linge de maison",
        "Tablier",
        "Draps",
        "Serviette de bain",
        "Rideaux",
        "Voilages",
        "Taie d'oreiller",
        "Parure de lit",
        "Gigoteuse",
        "Alèse",
        "Protège-matelas",
        "Drap de plage",
        "Peignoir",
        "Tapis de bain",
        "Nappe",
        "Sous-nappe",
        "Chemin de table",
        "Set de table",
        "Torchon",
        "Panneau japonais",
        "Mouchoir en tissu",
        "Housse",
    ],
    ["185 : meuble", "Lit (hors matelas)", "Lit pliant", "Lit de camp"],
    ["181 : livre", "Livre", "Bande-dessinée (album)"],
    ["172 : gros Appareil électroménager Hors Froid", "Machine à laver", "Lave-linge"],
    ["183 : outil De Bricolage/jardinage", "Marteau"],
    ["185 : meuble", "Matelas (en mousse, à ressorts...)"],
    [
        "173 : petit Appareil électroménager",
        "Matériel électrique passif (prise, adaptateur, câbles, cordons)",
        "Prise",
        "Rallonge",
        "Multiprise",
        "Cordon",
        "Câble",
    ],
    [
        "185 : meuble",
        "Meuble",
        "Etagère",
        "Bibliothèque",
        "Cadre de lit",
        "Placard",
        "Buffet",
        "Table de chevet",
        "Chaise",
        "Table",
        "Eléments de cuisine",
        "Lit",
        "Commode",
        "Table à langer",
        "Table de jardin",
        "Chaise de jardin",
        "Banc",
        "Ilot central",
        "Vaisselier",
        "Garde-manger",
        "Coffre",
        "Penderie",
        "Fauteuil",
        "Armoire",
        "Guéridon",
        "Argentier",
        "Bibus",
        "Chiffonnier",
        "Confiturier",
        "Console",
        "Caisson de meuble",
        "rallonge et extension de table",
        "Console murale",
        "Façade de porte",
        "Façade de tiroir",
        "Lingère",
        "Meuble de bar",
        "Meuble range CD",
        "Meuble d'aquarium",
        "Meuble de téléphone",
        "Meuble TV",
        "Ottomane",
        "Paravent",
        "Piétement de table",
        "Plateau de table",
        "Réhausse TV",
        "Repose-pied",
        "Table gigogne",
        "Tiroir",
        "Amortisseur mécanique pour meuble",
        "Boite de rangement",
        "Range bouteille",
        "Support mural d'accrochage",
        "Compas pour meuble",
        "Cube de rangement",
        "Etagère  (caisson, murale, de bureau, à épices, à vin, à chapeaux…)",
        "Filet de rangement",
        "Fileur",
        "Kit coulissant",
        "Meuble de hotte",
        "Pieds de meuble",
        "Porte-manteaux sur pied",
        "Porte battante de meuble",
        "Raccord de meubles modulaires",
        "Rangement coulissant pour caisson",
        "Rayonnage",
        "Structure de rangement",
        "Tiroir motorisé",
        "Tourillon",
        "Arbre à chat",
        "Quincaillerie de meuble",
        "Tréteau",
        "Tasseau",
        "Bande de chant",
        "Bouton de meuble",
        "Poignée de meuble",
        "Housse de dosseret",
        "Loquetaux",
        "Mobilier animalier",
        "Panier à linge",
        "Panneau de meuble",
        "Housse de table à repasser",
        "Servante d'atelier",
        "Accessoire pour meuble (taquet, équerre, patte, charnière, vis spécifiquement dédiées)",
        "Armoire-lit",
        "Bac de rangement",
        "Bac de rangement à roulettes",
        "Coiffeuse",
        "Couchette enfant",
        "Dosseret",
        "Dressing",
        "Lit d'appoint",
        "Lit évolutif",
        "Lit pont",
        "Lit relevable",
        "Lit rétractable",
        "Malle",
        "Portant",
        "Semainier (meuble)",
        "Tiroir de lit",
        "Table de massage",
        "Pupitre",
        "Valet",
        "Bloc tiroir",
        "Structure de lit",
        "Tringle à penderie",
        "Hamac à peluches",
        "Cloisonette de séparation",
        "Table basse",
        "Patère",
        "Tête de lit",
        "Lit superposé",
        "Tapis à chat ou chien",
        "Vitrine",
        "Bureau",
        "Bandeau de four",
        "Caisson (meuble)",
        "Casier à bouteille",
        "Casserolier",
        "Corniche",
        "Crémaillère",
        "Desserte",
        "Escabeau solidaire d'un meuble",
        "Etabli",
        "Casier à vin",
        "Façade de placard (coulissante, pliante ou pivotante)",
        "Façade de lave-vasselle",
        "Hûche à pain",
        "Poubelle (indépendante ou intégrée)",
        "Joue de finition",
        "Mange-débout",
        "Meuble de cuisine (haut et bas)",
        "Meuble d'évier",
        "Meuble de tri",
        "Meuble colonne",
        "Meuble de micro-ondes",
        "Meuble range-bouteilles",
        "Plan de travail",
        "Plinthe de meuble",
        "Egouttoir",
        "Range-couvert",
        "Armoire de toilette",
        "Crédence adhésive",
        "revêtement de meuble (portes de placard, plan de travail...)",
        "Socle de caisson",
        "Table de préparation",
        "Table encastrable",
        "Caisson à tiroirs (y compris à roulettes)",
        "Colonne de rangement",
        "Meuble sous vasque",
        "Rangement sous lavabo",
        "Siège de bain",
        "Plan à langer",
        "Tablette murale",
        "Range-outils",
        "Support de barbecue",
        "Bout de canapé",
        "Caisson de rangement pour bureau (y compris à roulettes)",
        "Chariot d'imprimante",
        "Chevalet d'écriture",
        "Meuble classeur",
        "Meuble de séparation",
        "Piétement de meuble (bureau, siège, table...)",
        "Cloisonnette de séparation amovible de jardon (visuelle ou phonique)",
        "Support brosse WC",
        "Porte-savon",
        "Accessoire de pose ou d'accrochage (dévidoir, dérouleur, distributeur, support...)",
        "Support de plancha",
        "Table (à manger, d'extérieur, de jardin, de camping, de pique-nique)",
        "Meuble à langer",
        "Meuble de ragement",
        "Porte-revue sur pied",
        "Plateau de bureau",
        "Retour et angle de bureau",
        "Secrétaire",
        "Support pour ordinateur",
        "Sur-meuble de bureau",
        "Tableau d'écriture",
        "Tablette coulissante pour clavier",
        "Table pour ordinateur portable",
        "Voile de fond de bureau",
        "Table de camping pique-nique pliante portable avec 4 sieges",
        "Table et ses 4 sièges solidaires pliables dans une valisette",
        "Serre-bûches",
        "Range-bûches",
        "Table de rempotage",
        "Support de jardinière",
        "Housse de protection de meuble",
        "Assise médicale (non électrique, non motorisée)",
        "Transat",
        "bain de soleil",
        "chaise longue",
        "Balancelle de jardin",
        "Banc-coffre",
    ],
    ["173 : petit Appareil électroménager", "Micro-ondes", "Four micro-ondes"],
    ["186 : objet De Décoration", "Miroir (glace)"],
    [
        "185 : meuble",
        "Mobilier de bureau",
        "Caisson",
        "Chaise de bureau",
        "Desserte informatique",
        "Crédence",
    ],
    ["179 : autre équipement électronique", "Montre électronique", "Montre connectée"],
    ["173 : petit Appareil électroménager", "Montre mécanique"],
    ["186 : objet De Décoration", "Moquette"],
    ["176 : matériel Informatique", "Ordinateur fixe", "PC fixe"],
    ["176 : matériel Informatique", "Ordinateur portable", "PC portable"],
    [
        "183 : outil De Bricolage/jardinage",
        "Outil électrique (bricolage, jardinage)",
        "Perceuse",
        "Visseuse",
        "Ponceuse",
        "Taille-haie",
        "Tronçonneuse",
        "Scie circulaire",
        "Disqueuse",
    ],
    [
        "183 : outil De Bricolage/jardinage",
        "Outil manuel (bricolage, jardinage)",
        "Tournevis",
        "Scie (non électrique)",
        "Pince (outil de bricolage)",
        "Cutter",
        "Masse (outil de bricolage)",
        "Maillet",
        "Lime (outil de bricolage)",
        "Râpe (outil de bricolage)",
        "Tenaille",
        "Clé (outil de bricolage)",
        "Douille (outil de bricolage)",
    ],
    [
        "173 : petit Appareil électroménager",
        "Petit électroménager",
        "Rice-cooker",
        "Bouilloire",
        "Grille-pain",
        "Toaster",
        "Ventilateur",
        "Mini-aspirateur",
        "Robot",
        "Mixeur",
        "Blender",
        "Cafetière",
        "Machine à café",
        "Couteau électrique",
        "Hachoir",
        "Fer à repasser",
        "Centrale vapeur",
        "Friteuse",
        "Grill",
        "Raclette",
        "Nettoyeur haute pression",
        "Karcher",
        "Batteur",
    ],
    ["193 : vêtement", "Plumes (et duvets)", "Doudoune", "Anorak"],
    ["186 : objet De Décoration", "Pot de fleurs"],
    [
        "172 : gros Appareil électroménager Hors Froid",
        "Radiateur électrique",
        "Chauffage électrique",
    ],
    [
        "171 : gros Appareil électroménager Froid",
        "Réfrigérateur",
        "Frigidaire",
        "Frigo",
    ],
    ["173 : petit Appareil électroménager", "Robot-aspirateur"],
    ["198 : autre Matériel De Sport", "Rollers", "Patins"],
    [
        "173 : petit Appareil électroménager",
        "Sèche-cheveux",
        "Lisseur",
        "Fer à friser",
        "Fer à lisser",
    ],
    ["190 : linge De Maison", "Serviette en tissu"],
    ["173 : petit Appareil électroménager", "Sirène (alarme)", "Alarme"],
    ["198 : autre Matériel De Sport", "Skate-board", "Planche à roulettes", "Skate"],
    ["185 : meuble", "Table à repasser", "Planche à repasser"],
    ["185 : meuble", "Tableau en ardoise"],
    ["179 : autre équipement électronique", "Téléphone fixe"],
    [
        "175 : smartphone",
        "Tablette",
        "Console de jeux",
        "Téléphone mobile",
        "Smartphone",
    ],
    ["174 : écran", "Téléviseur", "Télévision", "TV"],
    ["186 : objet De Décoration", "Textiles", "Tapis", "Natte"],
    ["179 : autre équipement électronique", "Thermomètre digital"],
    ["173 : petit Appareil électroménager", "Tondeuse à barbe"],
    ["183 : outil De Bricolage/jardinage", "Tondeuse à gazon électrique"],
    ["183 : outil De Bricolage/jardinage", "Tondeuse à gazon mécanique"],
    [
        "183 : outil De Bricolage/jardinage",
        "Tondeuse à gazon thermique",
        "Débroussailleuse thermique",
        "Coupe bordure thermique",
        "Aspirateur souffleur thermique, aspirateur souffleur broyeur thermique",
        "Souffleur thermique",
        "Broyeur thermique  à végétaux",
        "Pulvérisateur thermique,  Atomiseur thermique à dos",
        "Taille-haie thermique",
        "Tronçonneuse thermique",
        "Motobineuse thermique",
        "Motoculteur thermique",
        "Microbineuse thermique",
        "Tarière thermique",
        "Scarificateur thermique",
        "Démousseur thermique",
        "Aérateur démousseur thermique",
        "Pompe à eau thermique",
        "Outil multifonctions thermique combisystème ou multisystème",
        "Nettoyeur à haute pression thermique",
        "Fraise à neige thermique",
        "Scie à bûches thermique",
        "Fendeur de bûches thermique",
    ],
    ["179 : autre équipement électronique", "Train électrique (jouet)"],
    ["179 : autre équipement électronique", "Transformateur électrique"],
    ["198 : autre Matériel De Sport", "Trottinette"],
    ["187 : luminaire", "Tube fluorescent", "Néon"],
    ["189 : article De Vaisselle", "Ustensile de cuisine"],
    [
        "189 : article De Vaisselle",
        "Vaisselle",
        "Tasse",
        "Mug",
        "Fourchette",
        "Cuillère",
        "Assiette",
        "Casserole",
        "Bol",
    ],
    [
        "197 : vélo",
        "Vélo (hors vélo électrique)",
        "Cycle",
        "Bicyclette",
        "Bécane (biclou)",
        "Tandem",
    ],
    ["197 : vélo", "Vélo électrique", "Vélo à assistance électrique (VAE)"],
    ["186 : objet De Décoration", "Verre (ayant contenu une bougie)"],
    ["189 : article De Vaisselle", "Verre à boire"],
    ["193 : vêtement", "Vêtement souillé"],
    [
        "193 : vêtement",
        "Vêtement (propre et sec)",
        "Pull",
        "T-shirt",
        "Pantalon",
        "Short",
        "Bermuda",
        "Pantacourt",
        "Maillot de bain",
        "Chaussettes",
        "Bonnet",
        "Gant",
        "Echarpe",
        "Chemise",
        "Polo",
        "Veste",
        "Costume",
        "Gilet",
        "Sweat",
        "Caleçon",
        "Slip",
        "Boxer",
        "Caban",
        "Duffle-coat",
        "Trench",
        "Legging",
        "Jupe",
        "Robe",
        "Collant",
        "Mouffle",
        "Mitaine",
        "Foulard",
        "Sous-vêtement",
        "Lingerie",
        "Culotte",
        "Manteau",
        "Soutien-gorge",
    ],
    [
        "179 : autre équipement électronique",
        "Vieil appareil électrique ou électronique",
    ],
    ["179 : autre équipement électronique", "Voiture de course électrique (jouet)"],
    [
        "198 : autre Matériel De Sport",
        "Article de sport",
        "Accessoire de canoë kayak non électrique",
        "Accessoire de trottinette (roue, poignée, autre composant plastique)",
        "Accessoire de vélo (antivol, bagagerie, panier, sonnette, pompe, gourde, bidon et porte-bidon)",
        "Appareil de fitness non électrique",
        "Article pour la pêche à la ligne",
        "Aviron",
        "Accessoire de sport (baseball, basketball, football, handball, football américain, hockey, rugby, volley, handball, Athlétisme, gymnastique, yoga, pilate, danse, fitness, musculation, capoeira, cheerleading, cirque, fléchettes)",
        "ballon",
        "Bâton de ski",
        "BMX",
        "But de football",
        "Mini-but",
        "Cerf-volant",
        "Chariot de golf",
        "club de golf",
        "Composant de vélo",
        "Deltaplane",
        "Equipement de musculation non électrique",
        "Equipement de piscine",
        "hameçon",
        "kimono",
        "Mât de windsurf",
        "Matériel d'athlétisme (haie, starting-block, bâton, témoin, javelot, poids, disque, marteau, matériel pour saut en longueur et hauteur…)",
        "Matériel de voile (Dérive, gouvernail < 2,5 m)",
        "Matériel d'entraînement sportif (mini-haie, marquage au sol, plot, cône de sport…)",
        "pantalon d'escrime",
        "Parachute",
        "Parapente",
        "Porte-bébé pour vélo",
        "Portique",
        "Poteau, mini poteau de foot",
        "Raft",
        "Sac de frappe",
        "Sac de golf",
        "Sac de randonnée avec ceinture ventrale",
        "Short rembourré",
        "Snowboard",
        "Stand-up paddle (gonflable ou rigide)",
        "Tapis de sol",
        "Vélo adulte hors vélo à assistance électrique",
        "Vélo enfant",
        "Volant",
        "Wakeboard",
        "Wishbone de windsurf",
        "Arc",
        "Accessoire aquafitness",
        "pince-nez (piscine)",
        "Article de natation",
        "Bonnet de bain",
        "Babyfoot",
        "Boomerang",
        "Frisbee",
        "Vortex",
        "Bouclier (Pad) de boxe",
        "Ceinture de judo",
        "Cercle de basket",
        "Equipement de ski de randonnée (pelle, sonde...)",
        "Elliptique",
        "Elastiband",
        "Fitness tube",
        "Filet (football, volley-ball, badminton, tennis, tennis de table...)",
        "Etui de raquette (tennis, badminton, squash, tennis de table...)",
        "Filet de mini-tennis (filet + pieds)",
        "Foil (windsurf, kitesurf...)",
        "Jeu de palets",
        "Jeu de quilles",
        "Masque de ski ou de snowboard",
        "Matériel d'aquagym",
        "Matériel de cirque (diabolo, assiettes chinoises, balles et anneaux de jonglages...)",
        "Moulinet de canne à pêche",
        "Matériel en néoprène (chaussons, gants, cagoules, mitaines, surchausses...)",
        "Palet de hockey",
        "Panneau de basket",
        "Panier de basket",
        "Cadre de vélo",
        "Guidon de vélo",
        "Rayon de vélo",
        "Punch paddle (boxe)",
        "Rack de musculation",
        "Rameur",
        "Shorty, veste, combinaison en néoprène enfant",
        "Slackline",
        "Speedball",
        "Step de gymnastique",
        "Trampoline",
        "Poteau, mini poteau de rugby",
        "Mini poteau gonflable de rugby",
        "Equipement d'équitation (hors équipement de protection individuelle, chaussants et vêtements)",
        "Travel bag (bagagerie sportive)",
    ],
    [
        "198 : autre Matériel De Sport",
        "Balle de sport (gymnastique, yoga, pilates, musculation, capoeira, cheerleading, cirque)",
        "Balançoire",
        "Balle de golf",
        "Balle de sport de raquette (badminton, squash, ping-pong)",
        "Balle de baseball",
        "Batte de baseball",
        "Boule de billard",
        "Boule de pétanque",
        "Canne à pêche",
        "Cible (chasse, tir sportif, ball-trap, tir à l'arc, fléchettes)",
        "Combinaison (triathlon, nage eau libre, plongée, surf)",
        "Combinaison de ski",
        "Crosse de hockey",
        "Embarcation < 2,5m",
        "Fixation (ski, snowboard)",
        "Fixation murale sac de frappe",
        "Flèche",
        "Fléchette",
        "Housse du Surf",
        "Laisse de promenade de canicrosse",
        "Luge",
        "Pagaie",
        "Palme",
        "Pièce détachée skate-board",
        "Planche de bodyboard",
        "Planche de kite-surf",
        "Planche de surf (en mousse ou rigide)",
        "Planche de windsurf",
        "Pompe (vélo, sports nautiques)",
        "Rame",
        "Pelle d'aviron",
        "Raquette (tennis, badminton, squash, ping-pong...)",
        "Tenue de cycliste",
        "Table de billard",
        "Table de ping-pong",
        "Tente",
        "Trottinette non électrique",
        "Veste d'escrime",
        "Voile de windsurf",
        "Housse de sac",
        "Corde pour canicross",
        "Glacière rigide",
        "Housse de skis",
        "Housse de chaussures de ski",
        "Housse de snowboard",
        "Housse de surf",
        "Machine de musculation développé-couché",
        "Fourche de vélo",
        "Potence de vélo",
        "Poignée de vélo",
        "Jante de vélo",
        "Pédale de vélo",
        "Chaîne de vélo",
        "Planche de sport nautique (surf, kitesurf, windsurf, bodyboard)",
        "Pompe (vélo, sports nautiques...)",
        "Pièce détachée de vélo (moyeu, jeu de direction, plateau, dérailleur, poignée, chaîne, cadre, guidon, fourche...)",
    ],
    ["198 : autre Matériel De Sport", "Balle de tennis"],
    [
        "198 : autre Matériel De Sport",
        "Chaussons d'escalade",
        "Chaussures à crampons",
        "Chaussures de cyclisme",
        "Chaussures de ski",
        "Chaussures de surf",
        "Filets et poteaux  (tennis, badminton, squash, ping-pong, volley)",
        "Guètres de sport",
        "Patins à glace, de hockey sur glace, de curling",
        "Poids, haltères",
        "Raquettes de ski",
        "Skis",
        "Skis nautiques",
        "Tees",
        "chaussons de danse",
        "Chaussons de gymnastique",
        "Pointes d'athlétisme",
        "Lunettes de piscine",
        "palmes",
        "plaquettes (natation)",
        "Boots de snowboard",
        "Pattes d'ours (boxe)",
    ],
    [
        "198 : autre Matériel De Sport",
        "Matériel de protection individuelle (sport)",
        "Bouée, planche, matériel d'aide à la flottaison",
        "Brassard de flottaison",
        "Casque de protection (ski, vélo, football américain, hockey, roller skate, skate board, bombe d'équitation, alpinisme, escalade, varappe, canyoning, patinage artistique, hockey sur glace, curling…)",
        "Ceinture et gilet de sauvetage textile",
        "Chambre à air de vélo",
        "Coquille de protection",
        "Corde, cordelette, harnais et longe de canicrosse",
        "Coudière",
        "Crashpad",
        "Epaulière",
        "Gants (gardien de foot, vélo, voile, golf, escrime, boxe…)",
        "Genouillère",
        "Harnais, mousqueton, dégaine, assurage, poulie, bloqueur, coinceur (Matériel d'alpinisme, escalade, varappe, canyoning, camping)",
        "Lunettes de sports de montagne (parapente, parachute, deltaplane…)",
        "Matériel de voile (harnais de rappel, trapèze, accastillage, poulie, manille, mousqueton, drisse, cordage…) < 2,5 m,",
        "Piolet",
        "Pneu de vélo",
        "Protège-tibia",
        "Tuba, masque de plongée",
        "Protège-poignet",
        "Coque de protection de handball",
        "Corde, cordelette et longe d'escalade",
        "Crampons de chaussures de montagne",
        "Dorsale",
        "Equipement de ski de randonnée (pelle, sonde)",
        "Matériel d'escalade (harnais, mousqueton, dégaine, assurage, poulie, bloqueur, coinceur)",
        "Matériel d'alpinisme",
        "Matériel de Varappe",
        "Matériel de canyoning",
        "Masque d'escrime",
        "Matériel de protection du cavalier (bombe, gilet...)",
        "Suspente de parapente et parachute",
    ],
    [
        "198 : autre Matériel De Sport",
        "Arme d'entraînement",
        "Epée",
        "Fleuret",
        "Dague",
        "Couteau (chasse)",
        "Cartouche, douille usagée, balle (tir sportif)",
    ],
    ["193 : vêtement", "Couvre-chef", "Chapeau", "Béret", "Casquette", "Toque"],
    ["186 : objet De Décoration", "Cage pour animaux", "Volière", "Niche"],
    ["174 : écran", "Ecran plat"],
    ["174 : écran", "Ecran à tube cathodique"],
    [
        "186 : objet De Décoration",
        "Produit d'ameublement rembourré",
        "Couette",
        "Traversin",
        "Coussin",
        "Sac de couchage",
        "Panier pour animaux",
        "Edredon",
        "Surmatelas",
        "Polochon",
        "Housse rembourrée (chaise, canapé)",
        "Tapis d'éveil",
        "Turbulette",
        "Tour de lit rembourré",
        "Coussin d'allaitement",
        "Oreiller ergonomique",
        "Coussin d'assise ou de dossier",
        "Coussin pour animaux",
        "Oreiller",
    ],
    ["187 : luminaire", "Ampoule", "lampes"],
    ["179 : autre équipement électronique", "Calculatrice"],
    [
        "179 : autre équipement électronique",
        "Panneaux photovoltaïques",
        "PV",
        "Centrale photovoltaïque",
        "Panneaux solaires",
    ],
    [
        "186 : objet De Décoration",
        "Rideaux et leurs accessoires",
        "Bande d'accrochage de rideau",
        "Bande d'ancrage de rideau",
        "Bouton de tringle à rideau",
        "Décoration textile à suspendre",
        "Doublure occultante thermique",
        "Fausse peau de mouton",
        "Guirlande décoration en tissu",
        "Macramé",
        "Peau de bête",
        "Rideau obscurcissant",
        "Rideau occultant",
        "Rideau phonique",
        "Rideau tamisant",
        "Rideau thermique",
        "Rideau",
        "Rideau moustiquaire",
        "Set d'angle",
        "Store alvéolaire",
        "Store bateau",
        "Store californien",
        "Store enrouleur",
        "Store japonais",
        "Store occultant",
        "Store plissé",
        "Store pour fenêtre de toit",
        "Store vénitien",
        "Structure de penderie",
        "Support de fixation (rideau, penderie)",
        "Tissage mural macramé",
        "Tissu mural",
        "Toile tendue",
        "Tour de lit",
        "Tringle à vêtement",
        "Tringle à rideau",
        "Voilage tamisant",
        "Voilage transparent",
        "Voile d'ombrage",
    ],
    [
        "186 : objet De Décoration",
        "Carpette",
        "Paillassonextérieur",
        "Paillasson intérieur",
        "Thibaude",
    ],
    [
        "171 : gros Appareil électroménager Froid",
        "Gros appareil électroménager (froid)",
    ],
    [
        "172 : gros Appareil électroménager Hors Froid",
        "Gros appareil électroménager (hors froid)",
    ],
    ["173 : petit Appareil électroménager", "Petit électroménager"],
    ["174 : écran" "Écran"],
    ["175 : smartphone", "Smartphone, tablette, console"],
    ["176 : matériel Informatique", "Matériel informatique (ordinateur)"],
    ["177 : matériel Hifi/vidéo", "Matériel hifi, vidéo"],
    ["178 : matériel Photo/ciné", "Matériel photo, cinéma"],
    ["179 : autre équipement électronique", "Autre équipement électronique"],
    ["180 : CD/DVD/jeu Vidéo", "CD, DVD, jeu vidéo"],
    ["181 : livre", "Livre"],
    ["182 : instrument De Musique", "Instrument de musique"],
    ["183 : outil De Bricolage/jardinage", "Arrosoir"],
    ["183 : outil De Bricolage/jardinage", "Outil de bricolage, jardinage"],
    ["184 : Jardin (mobilier, accessoires)", "Accessoire, meuble de jardin"],
    ["185 : meuble", "Meuble"],
    ["186 : objet De Décoration", "Décoration"],
    ["187 : luminaire", "Luminaire"],
    ["189 : article De Vaisselle", "Vaisselle"],
    ["190 : linge De Maison", "Linge de maison"],
    ["191 : objet De Puériculture", "Puériculture"],
    ["192 : jouet", "Jouet"],
    ["193 : vêtement", "Vêtement"],
    ["194 : article De Maroquinerie", "Maroquinerie"],
    ["195 : paire De Chaussures", "Chaussures"],
    ["196 : bijou/montre", "Bijou, montre"],
    ["197 : vélo", "Vélo"],
    ["198 : autre Matériel De Sport", "Autre matériel de sport"],
    ["199 : matériel Médical", "Matériel médical"],
]


class Command(BaseCommand):
    help = "Injest objet with its category"

    def handle(self, *args, **options):
        for objet_by_cat in objet_list:
            sous_cat_num = objet_by_cat[0].split(" : ")[0]
            sous_cat = SousCategorieObjet.objects.get(lvao_id=sous_cat_num)
            for objet in objet_by_cat[1:]:
                (obj, created) = Objet.objects.get_or_create(
                    nom=objet, defaults={"sous_categorie": sous_cat}
                )
                if created:
                    logging.info(f"Created {obj}")
                else:
                    logging.warning(f"Already exists {obj}")
