# Generated by Django 5.1.4 on 2025-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_suggestion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestion",
            options={"verbose_name": "1️⃣ Suggestion"},
        ),
        migrations.AlterModelOptions(
            name="suggestioncohorte",
            options={"verbose_name": "📦 Cohorte"},
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "À valider"),
                    ("REJETEE", "Rejetée"),
                    ("ATRAITER", "À traiter"),
                    ("ENCOURS", "En cours de traitement"),
                    ("ERREUR", "Fini en erreur"),
                    ("SUCCES", "Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestioncohorte",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "Suggestions à valider"),
                    ("ENCOURS", "Suggestions en cours de traitement"),
                    ("SUCCES", "Suggestions traitées"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
    ]
