# Generated by Django 5.2.7 on 2025-11-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_alter_suggestion_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancache",
            name="modifie_le",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestiongroupe",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestionlog",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="parametres",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="raison",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="suggestion_modele",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
