# Generated by Django 5.2.9 on 2025-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_alter_suggestionunitaire_parametres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancache",
            name="modifie_le",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestiongroupe",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="parametres",
            field=models.JSONField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Fini en erreur"),
                    ("SUCCES", "✅ Fini avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
    ]
