# Generated by Django 5.2.9 on 2026-01-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_alter_suggestiongroupe_acteur_and_more"),
        ("qfdmo", "0187_alter_acteur_identifiant_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestiongroupe",
            name="parent_revision_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_groupes_from_parent",
                to="qfdmo.revisionacteur",
            ),
        ),
        migrations.AddField(
            model_name="suggestionunitaire",
            name="parent_revision_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_unitaires_from_parent",
                to="qfdmo.revisionacteur",
            ),
        ),
    ]
