name: Restore Django Database
description: Restore PostgreSQL database from dump file

inputs:
  database-url:
    description: 'PostgreSQL database URL'
    required: true
  database-dump-path:
    description: 'Path to database dump file'
    required: false
    default: 'database-dump.pgdump'

runs:
  using: composite
  steps:
    - name: Restore PostgreSQL database
      shell: bash
      run: pg_restore -d ${{ inputs.database-url }} --clean --if-exists ${{ inputs.database-dump-path }} || true
