# Generated by Django 6.0.2 on 2026-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Un terme de recherche désactivé ne s'affichera nulle part. \nOn le conserve en base de données pour conserver les redirections",
                verbose_name="Désactivé",
            ),
        ),
    ]
