# From exhaustive_acteurs, build acteurs tables which will be used to display them in the opendata

version: 2

models:
  - name: marts_opendata_filtered_acteur
    description: "Vue sur les acteurs affichés sur la opendata"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: description
        description: "La description de l'acteur"
      - name: acteur_type_id
        description: "Le type d'acteur"
      - name: adresse
        description: "L'adresse de l'acteur"
      - name: adresse_complement
        description: "L'adresse complémentaire de l'acteur"
      - name: code_postal
        description: "Le code postal de l'acteur"
      - name: ville
        description: "La ville de l'acteur"
      - name: url
        description: "L'URL de l'acteur"
      - name: email
        description: "L'email de l'acteur"
      - name: location
        description: "La localisation de l'acteur"
      - name: telephone
        description: "Le numéro de téléphone de l'acteur"
      - name: nom_commercial
        description: "Le nom commercial de l'acteur"
      - name: nom_officiel
        description: "Le nom officiel de l'acteur"
      - name: siren
        description: "Le numéro SIREN de l'acteur"
      - name: siret
        description: "Le numéro SIRET de l'acteur"
      - name: source_id
        description: "L'identifiant source de l'acteur"
      - name: identifiant_externe
        description: "L'identifiant externe de l'acteur"
      - name: naf_principal
        description: "Le code NAF principal de l'acteur"
      - name: commentaires
        description: "Les commentaires de l'acteur"
      - name: horaires_osm
        description: "Les horaires OSM de l'acteur"
      - name: horaires_description
        description: "La description des horaires de l'acteur"
      - name: public_accueilli
        description: "Le public accueilli par l'acteur"
      - name: reprise
        description: "La reprise de l'acteur"
      - name: exclusivite_de_reprisereparation
        description: "L'exclusivité de la réparation de l'acteur"
      - name: uniquement_sur_rdv
        description: "Le fait que l'acteur soit uniquement sur RDV"
      - name: consignes_dacces
        description: "Les consignes d'accès de l'acteur"
      - name: action_principale_id
        description: "L'action principale de l'acteur"
      - name: modifie_le
        description: "La date de modification de l'acteur"
        data_tests:
          - not_null
      - name: parent_id
        description: "L'identifiant du parent de l'acteur"
      - name: cree_le
        description: "La date de création de l'acteur"
        data_tests:
          - not_null
      - name: statut
        description: "Le statut de l'acteur"
        data_tests:
          - not_null
    config:
      materialized: ephemeral
  - name: marts_opendata_filtered_parentpropositionservice
    description: "Table temporaire pour calculer les parents des propositions de service"
    columns:
      - name: id
        description: "L'identifiant de la proposition de service"
        data_tests:
          - not_null
      - name: parent_id
        description: "L'identifiant du parent de la proposition de service"
        data_tests:
          - not_null
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: action_id
        description: "L'identifiant de l'action"
        data_tests:
          - not_null
    config:
      materialized: ephemeral
  - name: marts_opendata_filtered_propositionservice
    description: "Vue sur les propositions de service affichées sur la opendata"
    columns:
      - name: id
        description: "L'identifiant de la proposition de service"
        data_tests:
          - not_null
          - unique
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: action_id
        description: "L'identifiant de l'action"
        data_tests:
          - not_null
    config:
      materialized: ephemeral
  - name: marts_opendata_propositionservice
    description: "Vue sur les propositions de service affichées sur la opendata"
    columns:
      - name: id
        description: "L'identifiant de la proposition de service"
        data_tests:
          - not_null
          - unique
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: action_id
        description: "L'identifiant de l'action"
        data_tests:
          - not_null
    config:
      materialized: table
      indexes:
        - columns: ['acteur_id', 'action_id']
          unique: true
        - columns: ['acteur_id']
          type: hash
        - columns: ['action_id']
          type: hash
        - columns: ['id']
          type: hash
      constraints:
        - type: foreign_key
          columns: [acteur_id]
          ref_columns: [identifiant_unique]
          ref_table: marts_opendata_acteur
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [action_id]
          ref_columns: [id]
          ref_table: qfdmo_action
          deferrable: true
          initially_deferred: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - action_id
  - name: marts_opendata_propositionservice_sous_categories
    description: "Vue sur les sous-catégories des propositions de service affichées sur la opendata"
    columns:
      - name: id
        description: "L'identifiant de la sous-catégorie"
        data_tests:
          - not_null
      - name: propositionservice_id
        description: "L'identifiant de la proposition de service"
        data_tests:
          - not_null
      - name: souscategorieobjet_id
        description: "L'identifiant de la sous-catégorie"
        data_tests:
          - not_null
    config:
      materialized: table
      indexes:
        - columns: ['propositionservice_id', 'souscategorieobjet_id']
          unique: true
        - columns: ['propositionservice_id']
          type: hash
        - columns: ['souscategorieobjet_id']
          type: hash
      constraints:
        - type: foreign_key
          columns: [propositionservice_id]
          ref_columns: [id]
          ref_table: marts_opendata_propositionservice
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [souscategorieobjet_id]
          ref_columns: [id]
          ref_table: qfdmo_souscategorieobjet
          deferrable: true
          initially_deferred: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - propositionservice_id
            - souscategorieobjet_id

  - name: marts_opendata_acteur_acteur_services
    description: "Lien entre acteur de la opendata et acteur_services"
    columns:
      - name: id
        description: "L'identifiant du lien entre acteur et acteur_services"
        data_tests:
          - not_null
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: acteurservice_id
        description: "L'identifiant du service"
        data_tests:
          - not_null
    config:
      materialized: table
      indexes:
        - columns: ['acteur_id', 'acteurservice_id']
          unique: true
        - columns: ['acteur_id']
          type: hash
        - columns: ['acteurservice_id']
          type: hash
      constraints:
        - type: foreign_key
          columns: [acteur_id]
          ref_columns: [identifiant_unique]
          ref_table: marts_opendata_acteur
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [acteurservice_id]
          ref_columns: [id]
          ref_table: qfdmo_acteurservice
          deferrable: true
          initially_deferred: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - acteurservice_id

  - name: marts_opendata_acteur_labels
    description: "Lien entre acteur de la opendata et labels"
    columns:
      - name: id
        description: "L'identifiant du lien entre acteur et label"
        data_tests:
          - not_null
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: labelqualite_id
        description: "L'identifiant du label"
        data_tests:
          - not_null
    config:
      materialized: table
      indexes:
        - columns: ['acteur_id', 'labelqualite_id']
          unique: true
        - columns: ['acteur_id']
          type: hash
        - columns: ['labelqualite_id']
          type: hash
      constraints:
        - type: foreign_key
          columns: [acteur_id]
          ref_columns: [identifiant_unique]
          ref_table: marts_opendata_acteur
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [labelqualite_id]
          ref_columns: [id]
          ref_table: qfdmo_labelqualite
          deferrable: true
          initially_deferred: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - labelqualite_id

  - name: marts_opendata_acteur_sources
    description: "Lien entre acteur de la opendata et sources"
    columns:
      - name: id
        description: "L'identifiant de la source"
        data_tests:
          - not_null
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: source_id
        description: "L'identifiant de la source"
        data_tests:
          - not_null
    config:
      materialized: table
      indexes:
        - columns: ['acteur_id', 'source_id']
          unique: true
        - columns: ['acteur_id']
          type: hash
        - columns: ['source_id']
          type: hash
      constraints:
        - type: foreign_key
          columns: [acteur_id]
          ref_columns: [identifiant_unique]
          ref_table: marts_opendata_acteur
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [source_id]
          ref_columns: [id]
          ref_table: qfdmo_source
          deferrable: true
  - name: marts_opendata_acteur
    description: "Vue sur les acteurs affichés sur la opendata"
    columns:
      - name: uuid
        description: "L'identifiant unique de l'acteur"
        data_tests:
          - not_null
          - unique
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
        data_tests:
          - not_null
          - unique
    config:
      materialized: table
      indexes:
        - columns: ['modifie_le', 'identifiant_unique']
          type: btree
        - columns: ['identifiant_unique']
          type: btree
          unique: true
        - columns: ['code_postal']
          type: btree
        - columns: ['nom']
          type: btree
        - columns: ['siren']
          type: btree
        - columns: ['siret']
          type: btree
        - columns: ['source_id']
          type: hash
        - columns: ['ville']
          type: btree
        - columns: ['acteur_type_id']
          type: hash
        - columns: ['location']
          type: gist
      constraints:
        - type: foreign_key
          columns: [acteur_type_id]
          ref_columns: [id]
          ref_table: qfdmo_acteurtype
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [action_principale_id]
          ref_columns: [id]
          ref_table: qfdmo_action
          deferrable: true
          initially_deferred: true
        - type: foreign_key
          columns: [source_id]
          ref_columns: [id]
          ref_table: qfdmo_source
          deferrable: true
          initially_deferred: true
