# Generated by Django 4.2.3 on 2023-08-07 13:02

from typing import List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("lvao_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategorieObjet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Catégorie d'objets",
                "verbose_name_plural": "Catégories d'objets",
            },
        ),
        migrations.CreateModel(
            name="EntiteService",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("lvao_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service proposé par l'entité",
                "verbose_name_plural": "Services proposés par l'entité",
            },
        ),
        migrations.CreateModel(
            name="EntiteType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("lvao_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "verbose_name": "Type d'entité",
                "verbose_name_plural": "Types d'entité",
            },
        ),
        migrations.CreateModel(
            name="SousCategorieObjet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("lvao_id", models.IntegerField(blank=True, null=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.categorieobjet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous catégorie d'objets",
                "verbose_name_plural": "Sous catégories d'objets",
            },
        ),
    ]
