# Generated by Django 4.2.3 on 2023-08-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LVAOBase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                (
                    "identifiant_unique",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Acteur LVAO",
                "verbose_name_plural": "Acteurs LVAO",
            },
        ),
        migrations.CreateModel(
            name="LVAOBaseRevision",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lvao_node_id", models.IntegerField()),
                ("lvao_revision_id", models.IntegerField(null=True, unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adresse_complement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                ("multi_base", models.BooleanField(default=False)),
                (
                    "nom_commercial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_officiel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("publie", models.BooleanField(default=False)),
                ("manuel", models.BooleanField(default=False)),
                ("label_reparacteur", models.BooleanField(default=False)),
                ("siret", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "source_donnee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "identifiant_externe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actions",
                    models.ManyToManyField(related_name="actions", to="qfdmo.action"),
                ),
                (
                    "entite_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.entitetype",
                    ),
                ),
                (
                    "lvao_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lvao_base_revisions",
                        to="qfdmo.lvaobase",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="services", to="qfdmo.entiteservice"
                    ),
                ),
                (
                    "sous_categories",
                    models.ManyToManyField(
                        related_name="sous_categories", to="qfdmo.souscategorieobjet"
                    ),
                ),
            ],
            options={
                "verbose_name": "Révision Acteur LVAO",
                "verbose_name_plural": "Révision Acteurs LVAO",
            },
        ),
    ]
