# Generated by Django 4.2.3 on 2023-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0002_lvaobase"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntiteService",
            new_name="ActeurService",
        ),
        migrations.RenameModel(
            old_name="EntiteType",
            new_name="ActeurType",
        ),
        migrations.AlterModelOptions(
            name="acteurservice",
            options={
                "verbose_name": "Service proposé",
                "verbose_name_plural": "Services proposés",
            },
        ),
        migrations.AlterModelOptions(
            name="acteurtype",
            options={
                "verbose_name": "Type d'acteur",
                "verbose_name_plural": "Types d'acteur",
            },
        ),
        migrations.RenameField(
            model_name="lvaobaserevision",
            old_name="entite_type",
            new_name="acteur_type",
        ),
        migrations.RemoveField(
            model_name="lvaobaserevision",
            name="services",
        ),
        migrations.AddField(
            model_name="lvaobaserevision",
            name="acteur_services",
            field=models.ManyToManyField(
                related_name="acteur_services", to="qfdmo.acteurservice"
            ),
        ),
    ]
