# Generated by Django 4.2.3 on 2023-08-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0002_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("lvao_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Activities",
            },
        ),
    ]
