# Generated by Django 4.2.3 on 2023-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0003_rename_entiteservice_acteurservice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteurservice",
            name="actions",
            field=models.ManyToManyField(to="qfdmo.action"),
        ),
    ]
