# Generated by Django 4.2.4 on 2023-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0005_reemploiacteur_propositionservice_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReemploiActeur",
            new_name="EconomieCirculaireActeur",
        ),
        migrations.AlterModelOptions(
            name="economiecirculaireacteur",
            options={
                "verbose_name": "Acteur de l'économie circulaire",
                "verbose_name_plural": "Acteurs de l'économie circulaire",
            },
        ),
        migrations.RemoveConstraint(
            model_name="propositionservice",
            name="unique_by_acteur_action_service",
        ),
        migrations.RenameField(
            model_name="propositionservice",
            old_name="reemploi_acteur",
            new_name="economie_circulaire_acteur",
        ),
        migrations.AddConstraint(
            model_name="propositionservice",
            constraint=models.UniqueConstraint(
                fields=("economie_circulaire_acteur", "action", "acteur_service"),
                name="unique_by_acteur_action_service",
            ),
        ),
    ]
