# Generated by Django 4.2.4 on 2023-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0007_rename_economiecirculaireacteur_acteur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionDirection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("nom_affiche", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Direction de l'action",
                "verbose_name_plural": "Directions de l'action",
            },
        ),
        migrations.AddField(
            model_name="action",
            name="nom_affiche",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="action",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="action",
            name="directions",
            field=models.ManyToManyField(to="qfdmo.actiondirection"),
        ),
    ]
