# Generated by Django 4.2.4 on 2023-09-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0008_actiondirection_action_nom_affiche_action_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiondirection",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
