# Generated by Django 4.2.4 on 2023-09-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0009_actiondirection_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
