# Generated by Django 4.2.4 on 2023-09-15 08:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0010_action_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionActeur",
            fields=[
                ("nom", models.CharField(max_length=255)),
                (
                    "identifiant_unique",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adresse_complement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                ("multi_base", models.BooleanField(default=False)),
                (
                    "nom_commercial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_officiel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("manuel", models.BooleanField(default=False)),
                ("label_reparacteur", models.BooleanField(default=False)),
                ("siret", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "source_donnee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "identifiant_externe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Révision de l'Acteur",
                "verbose_name_plural": "Révisions des Acteurs",
            },
        ),
        migrations.CreateModel(
            name="RevisionPropositionService",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Proposition de service",
                "verbose_name_plural": "Proposition de service",
            },
        ),
        migrations.RemoveConstraint(
            model_name="propositionservice",
            name="unique_by_acteur_action_service",
        ),
        migrations.AlterField(
            model_name="propositionservice",
            name="acteur_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qfdmo.acteurservice"
            ),
        ),
        migrations.AlterField(
            model_name="propositionservice",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qfdmo.action"
            ),
        ),
        migrations.AlterField(
            model_name="propositionservice",
            name="sous_categories",
            field=models.ManyToManyField(to="qfdmo.souscategorieobjet"),
        ),
        migrations.AddField(
            model_name="revisionpropositionservice",
            name="acteur_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qfdmo.acteurservice"
            ),
        ),
        migrations.AddField(
            model_name="revisionpropositionservice",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qfdmo.action"
            ),
        ),
        migrations.AddField(
            model_name="revisionpropositionservice",
            name="revision_acteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposition_services",
                to="qfdmo.revisionacteur",
            ),
        ),
        migrations.AddField(
            model_name="revisionpropositionservice",
            name="sous_categories",
            field=models.ManyToManyField(to="qfdmo.souscategorieobjet"),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="acteur_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurtype",
            ),
        ),
    ]
