# Generated by Django 4.2.4 on 2023-09-15 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0011_revisionacteur_revisionpropositionservice_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                SELECT
                      COALESCE(ra.id, a.id) as id
                    , COALESCE(ra.nom, a.nom) as nom
                    , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                    , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                    , COALESCE(ra.adresse, a.adresse) as adresse
                    , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                    , COALESCE(ra.code_postal, a.code_postal) as code_postal
                    , COALESCE(ra.ville, a.ville) as ville
                    , COALESCE(ra.url, a.url) as url
                    , COALESCE(ra.email, a.email) as email
                    , COALESCE(ra.location, a.location) as location
                    , COALESCE(ra.telephone, a.telephone) as telephone
                    , COALESCE(ra.multi_base, a.multi_base) as multi_base
                    , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                    , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                    , COALESCE(ra.manuel, a.manuel) as manuel
                    , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                    , COALESCE(ra.siret, a.siret) as siret
                    , COALESCE(ra.source_donnee, a.source_donnee) as source_donnee
                    , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                FROM qfdmo_acteur a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.id = a.id
            """,
            "DROP MATERIALIZED VIEW qfdmo_finalacteur;",
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX ON qfdmo_finalacteur(id);
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW qfdmo_finalpropositionservice AS
                SELECT row_number() OVER (ORDER BY a.id) as id,
                    a.id AS acteur_id,
                    COALESCE(rps.action_id, ps.action_id) AS action_id,
                    COALESCE(rps.acteur_service_id, ps.acteur_service_id) AS acteur_service_id
                FROM qfdmo_acteur AS a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON a.id = ra.id
                LEFT OUTER JOIN qfdmo_propositionservice AS ps ON ps.acteur_id = a.id AND ra.id IS NULL
                LEFT OUTER JOIN qfdmo_revisionpropositionservice AS rps ON rps.revision_acteur_id = a.id
            """,
            "DROP MATERIALIZED VIEW qfdmo_finalpropositionservice;",
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX ON qfdmo_finalpropositionservice(id);
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW qfdmo_finalpropositionservice_sous_categories AS
                SELECT row_number() OVER (ORDER BY a.id) as id,
                	fps.id AS finalpropositionservice_id,
                    COALESCE(rps_sc.souscategorieobjet_id, ps_sc.souscategorieobjet_id) AS souscategorieobjet_id
                FROM qfdmo_acteur AS a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON a.id = ra.id
                LEFT OUTER JOIN qfdmo_propositionservice AS ps ON ps.acteur_id = a.id AND ra.id IS NULL
                LEFT OUTER JOIN qfdmo_revisionpropositionservice AS rps ON rps.revision_acteur_id = a.id
                LEFT OUTER JOIN qfdmo_finalpropositionservice AS fps ON fps.acteur_id = a.id AND fps.action_id = COALESCE(rps.action_id, ps.action_id) and COALESCE(rps.acteur_service_id, ps.acteur_service_id) = fps.acteur_service_id
                LEFT OUTER JOIN qfdmo_propositionservice_sous_categories AS ps_sc ON ps_sc.propositionservice_id = ps.id AND ps.id IS NOT NULL
                LEFT OUTER JOIN qfdmo_revisionpropositionservice_sous_categories AS rps_sc ON rps_sc.revisionpropositionservice_id = rps.id AND rps.id IS NOT NULL
                WHERE (rps_sc.revisionpropositionservice_id IS NOT NULL OR ps_sc.propositionservice_id IS NOT NULL)
            """,
            "DROP MATERIALIZED VIEW qfdmo_finalpropositionservice_sous_categories;",
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX ON qfdmo_finalpropositionservice_sous_categories(id);
            """,
            migrations.RunSQL.noop,
        ),
    ]
