# Generated by Django 4.2.4 on 2023-09-25 15:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0012_create_materialized_view_20230915_0918"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acteur",
            options={
                "verbose_name": "ACTEUR de l'EC - IMPORTÉ",
                "verbose_name_plural": "ACTEURS de l'EC - IMPORTÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="revisionacteur",
            options={
                "verbose_name": "ACTEUR de l'EC - CORRIGÉ",
                "verbose_name_plural": "ACTEURS de l'EC - CORRIGÉ",
            },
        ),
    ]
