# Generated by Django 4.2.4 on 2023-09-25 15:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0013_update_verbose_name"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name="Objet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.souscategorieobjet",
                        related_name="objets",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
