# Generated by Django 4.2.5 on 2023-09-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0014_create_objet"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteurtype",
            name="nom_affiche",
            field=models.CharField(default="?", max_length=255),
        )
    ]
