# Generated by Django 4.2.5 on 2023-10-11 10:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


def before_migration(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    Acteur.objects.filter(source_donnee__isnull=True).update(source_donnee="Equipe")
    Acteur.objects.filter(source_donnee="").update(source_donnee="Equipe")
    # for acteur in Acteur.objects.filter(source_donnee__isnull=True):
    #     if acteur.source_donnee not in source_donnees:
    #         source_donnee = SourceDonnee.objects.create(nom=acteur.source_donnee)
    #         source_donnees[acteur.source_donnee] = source_donnee
    #         acteur.source = source_donnee
    #         acteur.save()
    #     else:
    #         acteur.source = source_donnees[acteur.source_donnee]
    #         acteur.save()


def after_migration(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    SourceDonnee = apps.get_model("qfdmo", "SourceDonnee")
    source_donnees = {}
    for acteur in Acteur.objects.all():
        if acteur.source_donnee not in source_donnees:
            source_donnee = SourceDonnee.objects.create(nom=acteur.source_donnee)
            source_donnees[acteur.source_donnee] = source_donnee
            acteur.source = source_donnee
            acteur.save()
        else:
            acteur.source = source_donnees[acteur.source_donnee]
            acteur.save()


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0016_action_couleur_and_more"),
    ]

    operations = [
        # FIXME : run a migration to set the default value for
        # - source_id
        # - identifiant_externe
        # - identifiant unique
        # migrations.RunPython(plop, migrations.RunPython.noop),
        migrations.CreateModel(
            name="SourceDonnee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("afficher", models.BooleanField(default=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "verbose_name": "Source de données",
                "verbose_name_plural": "Sources de données",
            },
        ),
        migrations.AlterModelOptions(
            name="propositionservice",
            options={
                "verbose_name": "PROPOSITION DE SERVICE - IMPORTÉ",
                "verbose_name_plural": "PROPOSITIONS DE SERVICE - IMPORTÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="revisionpropositionservice",
            options={
                "verbose_name": "PROPOSITION DE SERVICE - CORRIGÉ",
                "verbose_name_plural": "PROPOSITIONS DE SERVICE - CORRIGÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="souscategorieobjet",
            options={
                "ordering": ["nom"],
                "verbose_name": "Sous catégorie d'objets",
                "verbose_name_plural": "Sous catégories d'objets",
            },
        ),
        migrations.AddField(
            model_name="acteur",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "actif"),
                    ("INACTIF", "inactif"),
                    ("SUPPRIME", "supprimé"),
                ],
                default="ACTIF",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "actif"),
                    ("INACTIF", "inactif"),
                    ("SUPPRIME", "supprimé"),
                ],
                default="ACTIF",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_unique",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="couleur",
            field=models.CharField(
                blank=True,
                default="yellow-tournesol",
                help_text="Couleur du badge à choisir dans le DSFR\nCouleur dispoible : blue-france, green-tilleul-verveine, green-bourgeon, green-emeraude,\ngreen-menthe, green-archipel, blue-ecume, blue-cumulus, purple-glycine, pink-macaron,\npink-tuile, yellow-tournesol, yellow-moutarde, orange-terre-battue, brown-cafe-creme,\nbrown-caramel, brown-opera, beige-gris-galet",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icône du badge à choisir dans le <a href='https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones' target='_blank'>DSFR</a>",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_unique",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="acteur",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.sourcedonnee",
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.sourcedonnee",
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="acteur_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qfdmo.acteurtype"
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW qfdmo_finalacteur;
            CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                SELECT
                      COALESCE(ra.id, a.id) as id
                    , COALESCE(ra.nom, a.nom) as nom
                    , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                    , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                    , COALESCE(ra.adresse, a.adresse) as adresse
                    , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                    , COALESCE(ra.code_postal, a.code_postal) as code_postal
                    , COALESCE(ra.ville, a.ville) as ville
                    , COALESCE(ra.url, a.url) as url
                    , COALESCE(ra.email, a.email) as email
                    , COALESCE(ra.location, a.location) as location
                    , COALESCE(ra.telephone, a.telephone) as telephone
                    , COALESCE(ra.multi_base, a.multi_base) as multi_base
                    , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                    , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                    , COALESCE(ra.manuel, a.manuel) as manuel
                    , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                    , COALESCE(ra.siret, a.siret) as siret
                    , COALESCE(ra.source_donnee, a.source_donnee) as source_donnee
                    , COALESCE(ra.source_id, a.source_id) as source_id
                    , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                    , COALESCE(ra.statut, a.statut) as statut
                FROM qfdmo_acteur a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.id = a.id;
                CREATE UNIQUE INDEX ON qfdmo_finalacteur(id);
            """,
            """
            DROP MATERIALIZED VIEW qfdmo_finalacteur;
            CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                SELECT
                      COALESCE(ra.id, a.id) as id
                    , COALESCE(ra.nom, a.nom) as nom
                    , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                    , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                    , COALESCE(ra.adresse, a.adresse) as adresse
                    , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                    , COALESCE(ra.code_postal, a.code_postal) as code_postal
                    , COALESCE(ra.ville, a.ville) as ville
                    , COALESCE(ra.url, a.url) as url
                    , COALESCE(ra.email, a.email) as email
                    , COALESCE(ra.location, a.location) as location
                    , COALESCE(ra.telephone, a.telephone) as telephone
                    , COALESCE(ra.multi_base, a.multi_base) as multi_base
                    , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                    , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                    , COALESCE(ra.manuel, a.manuel) as manuel
                    , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                    , COALESCE(ra.siret, a.siret) as siret
                    , COALESCE(ra.source_donnee, a.source_donnee) as source_donnee
                    , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                FROM qfdmo_acteur a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.id = a.id;
                CREATE UNIQUE INDEX ON qfdmo_finalacteur(id);
            """,
        ),
    ]
