# Generated by Django 4.2.5 on 2023-10-13 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0017_sourcedonnee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalActeur",
            fields=[
                ("nom", models.CharField(max_length=255)),
                ("identifiant_unique", models.CharField(max_length=255, unique=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adresse_complement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                ("multi_base", models.BooleanField(default=False)),
                (
                    "nom_commercial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_officiel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("manuel", models.BooleanField(default=False)),
                ("label_reparacteur", models.BooleanField(default=False)),
                ("siret", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "source_donnee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "identifiant_externe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "actif"),
                            ("INACTIF", "inactif"),
                            ("SUPPRIME", "supprimé"),
                        ],
                        default="ACTIF",
                        max_length=255,
                    ),
                ),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "ACTEUR de l'EC - AFFICHÉ",
                "verbose_name_plural": "ACTEURS de l'EC - AFFICHÉ",
                "db_table": "qfdmo_finalacteur",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FinalPropositionService",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Proposition de service",
                "verbose_name_plural": "Proposition de service",
                "db_table": "qfdmo_finalpropositionservice",
                "managed": False,
            },
        ),
    ]
