# Generated by Django 4.2.5 on 2023-10-16 08:22

import random
import string

import unidecode
from django.db import migrations


def set_default_acteur_fields(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    ActeurType = apps.get_model("qfdmo", "ActeurType")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")

    # manage not null source de données
    Acteur.objects.filter(source_donnee__isnull=True).update(source_donnee="equipe")
    Acteur.objects.filter(source_donnee="").update(source_donnee="equipe")

    # manage not null acteur type
    for acteur in Acteur.objects.filter(acteur_type__isnull=True):
        acteur_type = ActeurType.objects.get(nom="ess")
        acteur.acteur_type = acteur_type
        acteur.save()

    # manage not null identifiant externe
    for acteur in Acteur.objects.filter(identifiant_externe__isnull=True):
        acteur.identifiant_externe = "".join(
            random.choices(string.ascii_uppercase, k=12)
        )
        acteur.identifiant_unique = (
            unidecode.unidecode(acteur.source_donnee).lower()
            + "_"
            + acteur.identifiant_externe
        )
        acteur.save()

    # manage not null identifiant unique
    for acteur in Acteur.objects.filter(identifiant_unique__isnull=True):
        if not acteur.identifiant_externe:
            acteur.identifiant_externe = "".join(
                random.choices(string.ascii_uppercase, k=12)
            )
        acteur.identifiant_unique = (
            unidecode.unidecode(acteur.source_donnee).lower()
            + "_"
            + acteur.identifiant_externe
        )
        acteur.save()
    for revision_acteur in RevisionActeur.objects.filter(
        identifiant_unique__isnull=True
    ):
        acteur = Acteur.objects.get(id=revision_acteur.id)
        revision_acteur.identifiant_unique = acteur.identifiant_unique
        revision_acteur.save()


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0017_finalacteur_finalpropositionservice"),
    ]

    operations = [
        migrations.RunPython(set_default_acteur_fields, migrations.RunPython.noop),
    ]
