# Generated by Django 4.2.5 on 2023-10-16 09:12

import unidecode
from django.db import migrations, models


def set_acteur_source(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    Source = apps.get_model("qfdmo", "Source")

    for acteur in Acteur.objects.values("source_donnee").distinct():
        source = Source.objects.get_or_create(
            nom=unidecode.unidecode(acteur["source_donnee"]).lower()
        )[0]
        Acteur.objects.filter(source_donnee=acteur["source_donnee"]).update(
            source_id=source.id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0019_source_and_more"),
    ]

    operations = [
        migrations.RunPython(set_acteur_source, migrations.RunPython.noop),
    ]
