# Generated by Django 4.2.5 on 2023-10-16 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0020_set_acteur_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acteur",
            name="source_donnee",
        ),
        migrations.RemoveField(
            model_name="revisionacteur",
            name="source_donnee",
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS qfdmo_finalacteur;
            CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                SELECT
                      COALESCE(ra.id, a.id) as id
                    , COALESCE(ra.nom, a.nom) as nom
                    , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                    , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                    , COALESCE(ra.adresse, a.adresse) as adresse
                    , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                    , COALESCE(ra.code_postal, a.code_postal) as code_postal
                    , COALESCE(ra.ville, a.ville) as ville
                    , COALESCE(ra.url, a.url) as url
                    , COALESCE(ra.email, a.email) as email
                    , COALESCE(ra.location, a.location) as location
                    , COALESCE(ra.telephone, a.telephone) as telephone
                    , COALESCE(ra.multi_base, a.multi_base) as multi_base
                    , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                    , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                    , COALESCE(ra.manuel, a.manuel) as manuel
                    , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                    , COALESCE(ra.siret, a.siret) as siret
                    , COALESCE(ra.source_id, a.source_id) as source_id
                    , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                    , COALESCE(ra.statut, a.statut) as statut
                FROM qfdmo_acteur a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.id = a.id;
                CREATE UNIQUE INDEX ON qfdmo_finalacteur(id);
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS qfdmo_finalacteur;
            CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                SELECT
                      COALESCE(ra.id, a.id) as id
                    , COALESCE(ra.nom, a.nom) as nom
                    , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                    , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                    , COALESCE(ra.adresse, a.adresse) as adresse
                    , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                    , COALESCE(ra.code_postal, a.code_postal) as code_postal
                    , COALESCE(ra.ville, a.ville) as ville
                    , COALESCE(ra.url, a.url) as url
                    , COALESCE(ra.email, a.email) as email
                    , COALESCE(ra.location, a.location) as location
                    , COALESCE(ra.telephone, a.telephone) as telephone
                    , COALESCE(ra.multi_base, a.multi_base) as multi_base
                    , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                    , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                    , COALESCE(ra.manuel, a.manuel) as manuel
                    , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                    , COALESCE(ra.siret, a.siret) as siret
                    , COALESCE(ra.source_donnee, a.source_donnee) as source_donnee
                    , COALESCE(ra.source_id, a.source_id) as source_id
                    , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                    , COALESCE(ra.statut, a.statut) as statut
                FROM qfdmo_acteur a
                LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.id = a.id;
                CREATE UNIQUE INDEX ON qfdmo_finalacteur(id);
            """,
        ),
    ]
