# Generated by Django 4.2.5 on 2023-10-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0021_remove_acteur_source_donnee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdresseVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="equipe", max_length=255)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adresse_complement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("adresse_valide", models.BooleanField(default=False)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("geoloc_valide", models.BooleanField(default=False)),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresse_verifications",
                        to="qfdmo.acteur",
                        to_field="identifiant_unique",
                    ),
                ),
            ],
        ),
    ]
