# Generated by Django 4.2.6 on 2023-10-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0022_acteur_cree_le_acteur_modifie_le_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_unique",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_unique",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
