# Generated by Django 4.2.6 on 2023-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0023_alter_acteur_identifiant_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctionacteur",
            name="correction_statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("IGNORE", "Ignoré"),
                    ("PAS_DE_MODIF", "Pas de modification"),
                    ("ACCEPTE", "Accepté"),
                    ("REJETE", "Rejeté"),
                ],
                default="ACTIF",
                max_length=255,
            ),
        ),
    ]
