# Generated by Django 4.2.6 on 2023-10-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0026_remove_acteur_id_remove_revisionacteur_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctionacteur",
            name="final_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="corrections",
                to="qfdmo.finalacteur",
                to_field="identifiant_unique",
            ),
        ),
        migrations.AlterField(
            model_name="correctionacteur",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
