# Generated by Django 4.2.6 on 2023-10-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0028_finalpropositionservice_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionacteur",
            name="nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
