# Generated by Django 4.2.6 on 2023-11-05 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0029_alter_revisionacteur_nom"),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX location_idx on qfdmo_finalacteur USING SPGIST (location);
            """,
            """
                DROP INDEX location_idx;
            """,
        ),
    ]
