# Generated by Django 4.2.6 on 2023-11-06 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0030_create_location_index"),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX finalpropositionservice_id_idx on qfdmo_finalpropositionservice_sous_categories(finalpropositionservice_id);
            """,
            """
                DROP INDEX finalpropositionservice_id_idx;
            """,
        ),
    ]
