# Generated by Django 4.2.6 on 2023-11-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0031_create_finalpropositionservice_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctionacteur",
            name="final_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="corrections",
                to="qfdmo.finalacteur",
            ),
        ),
    ]
