# Generated by Django 4.2.7 on 2023-11-13 11:19

import django.db.models.deletion
from django.db import migrations, models


def update_service_nom_affiche(apps, schema_editor):
    ActeurService = apps.get_model("qfdmo", "ActeurService")
    for acteur_service in ActeurService.objects.all():
        acteur_service.nom_affiche = acteur_service.nom
        acteur_service.save()


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0032_create_indexes_on_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteurservice",
            name="nom_affiche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(update_service_nom_affiche, migrations.RunPython.noop),
    ]
