# Generated by Django 4.2.7 on 2023-11-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0033_acteurservice_nom_affiche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="directions",
            field=models.ManyToManyField(
                related_name="actions", to="qfdmo.actiondirection"
            ),
        ),
    ]
