# Generated by Django 4.2.7 on 2023-11-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0034_directions_actions_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icône du badge à choisir dans le <a href='https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icones' rel='noopener' target='_blank'>DSFR</a>",
                max_length=255,
                null=True,
            ),
        ),
    ]
