# Generated by Django 4.2.7 on 2023-11-29 15:41

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0035_alter_action_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="horaires",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AddField(
            model_name="correctionacteur",
            name="horaires",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="horaires",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.RunSQL(
            """
                    DROP MATERIALIZED VIEW IF EXISTS qfdmo_finalacteur;
                    CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                        SELECT
                            COALESCE(ra.nom, a.nom) as nom
                            , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                            , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                            , COALESCE(ra.adresse, a.adresse) as adresse
                            , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                            , COALESCE(ra.code_postal, a.code_postal) as code_postal
                            , COALESCE(ra.ville, a.ville) as ville
                            , COALESCE(ra.url, a.url) as url
                            , COALESCE(ra.email, a.email) as email
                            , COALESCE(ra.location, a.location) as location
                            , COALESCE(ra.telephone, a.telephone) as telephone
                            , COALESCE(ra.multi_base, a.multi_base) as multi_base
                            , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                            , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                            , COALESCE(ra.manuel, a.manuel) as manuel
                            , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                            , COALESCE(ra.siret, a.siret) as siret
                            , COALESCE(ra.source_id, a.source_id) as source_id
                            , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                            , COALESCE(ra.statut, a.statut) as statut
                            , COALESCE(ra.cree_le, a.cree_le) as cree_le
                            , COALESCE(ra.modifie_le, a.modifie_le) as modifie_le
                            , COALESCE(ra.naf_principal, a.naf_principal) as naf_principal
                            , COALESCE(ra.commentaires, a.commentaires) as commentaires
                            , COALESCE(ra.horaires, a.horaires) as horaires
                        FROM qfdmo_acteur a
                        LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.identifiant_unique = a.identifiant_unique;
                    CREATE UNIQUE INDEX ON qfdmo_finalacteur(identifiant_unique);
            """,
            """
                    DROP MATERIALIZED VIEW IF EXISTS qfdmo_finalacteur;
                    CREATE MATERIALIZED VIEW qfdmo_finalacteur AS
                        SELECT
                            COALESCE(ra.nom, a.nom) as nom
                            , COALESCE(ra.identifiant_unique, a.identifiant_unique) as identifiant_unique
                            , COALESCE(ra.acteur_type_id, a.acteur_type_id) as acteur_type_id
                            , COALESCE(ra.adresse, a.adresse) as adresse
                            , COALESCE(ra.adresse_complement, a.adresse_complement) as adresse_complement
                            , COALESCE(ra.code_postal, a.code_postal) as code_postal
                            , COALESCE(ra.ville, a.ville) as ville
                            , COALESCE(ra.url, a.url) as url
                            , COALESCE(ra.email, a.email) as email
                            , COALESCE(ra.location, a.location) as location
                            , COALESCE(ra.telephone, a.telephone) as telephone
                            , COALESCE(ra.multi_base, a.multi_base) as multi_base
                            , COALESCE(ra.nom_commercial, a.nom_commercial) as nom_commercial
                            , COALESCE(ra.nom_officiel, a.nom_officiel) as nom_officiel
                            , COALESCE(ra.manuel, a.manuel) as manuel
                            , COALESCE(ra.label_reparacteur, a.label_reparacteur) as label_reparacteur
                            , COALESCE(ra.siret, a.siret) as siret
                            , COALESCE(ra.source_id, a.source_id) as source_id
                            , COALESCE(ra.identifiant_externe, a.identifiant_externe) as identifiant_externe
                            , COALESCE(ra.statut, a.statut) as statut
                            , COALESCE(ra.cree_le, a.cree_le) as cree_le
                            , COALESCE(ra.modifie_le, a.modifie_le) as modifie_le
                            , COALESCE(ra.naf_principal, a.naf_principal) as naf_principal
                            , COALESCE(ra.commentaires, a.commentaires) as commentaires
                        FROM qfdmo_acteur a
                        LEFT OUTER JOIN qfdmo_revisionacteur AS ra ON ra.identifiant_unique = a.identifiant_unique;
                    CREATE UNIQUE INDEX ON qfdmo_finalacteur(identifiant_unique);
            """,
        ),
    ]
