# Generated by Django 4.2.7 on 2023-12-21 11:10

from django.db import migrations, models


def delete_double(apps, schema_editor):
    PropositionService = apps.get_model("qfdmo", "PropositionService")
    RevisionPropositionService = apps.get_model("qfdmo", "RevisionPropositionService")

    fields_by_model = {
        PropositionService: ["acteur", "action", "acteur_service"],
        RevisionPropositionService: ["revision_acteur", "action", "acteur_service"],
    }
    for Model, fields in fields_by_model.items():
        duplicates = (
            Model.objects.values(*fields)
            .annotate(max_id=models.Max("id"), count_id=models.Count("id"))
            .filter(count_id=2)
        )

        for duplicate in duplicates:
            (
                Model.objects.filter(**{x: duplicate[x] for x in fields})
                .exclude(id=duplicate["max_id"])
                .delete()
            )


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0036_acteur_horaires"),
    ]

    operations = [
        migrations.RunPython(delete_double, migrations.RunPython.noop),
    ]
