# Generated by Django 4.2.7 on 2023-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0037_remove_duplicates_proposition_service"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="propositionservice",
            constraint=models.UniqueConstraint(
                fields=("acteur", "action", "acteur_service"),
                name="ps_unique_by_acteur_action_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionpropositionservice",
            constraint=models.UniqueConstraint(
                fields=("revision_acteur", "action", "acteur_service"),
                name="rps_unique_by_revisionacteur_action_service",
            ),
        ),
    ]
