# Generated by Django 4.2.9 on 2024-02-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0042_displayedacteurtemp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="logo_file",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
    ]
