# Generated by Django 4.2.9 on 2024-03-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0043_source_logo_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctionequipeacteur",
            options={
                "verbose_name": "ACTEUR de l'EC - CORRIGÉ (NOUVEAU À IGNORER)",
                "verbose_name_plural": "ACTEURS de l'EC - CORRIGÉ (NOUVEAU À IGNORER)",
            },
        ),
        migrations.AlterModelOptions(
            name="correctionequipepropositionservice",
            options={
                "verbose_name": "PROPOSITION DE SERVICE - CORRIGÉ (NOUVEAU À IGNORER)",
                "verbose_name_plural": "PROPOSITIONS DE SERVICE - CORRIGÉ (NOUVEAU À IGNORER)",
            },
        ),
        migrations.AlterModelOptions(
            name="displayedacteur",
            options={
                "verbose_name": "ACTEUR de l'EC - AFFICHÉ (NOUVEAU À IGNORER)",
                "verbose_name_plural": "ACTEURS de l'EC - AFFICHÉ (NOUVEAU À IGNORER)",
            },
        ),
        migrations.AlterModelOptions(
            name="displayedpropositionservice",
            options={
                "verbose_name": "Proposition de service - AFFICHÉ (NOUVEAU À IGNORER)",
                "verbose_name_plural": "Proposition de service - AFFICHÉ (NOUVEAU À IGNORER)",
            },
        ),
        migrations.AlterModelOptions(
            name="finalacteur",
            options={
                "managed": False,
                "verbose_name": "ACTEUR de l'EC - AFFICHÉ",
                "verbose_name_plural": "ACTEURS de l'EC - AFFICHÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="finalpropositionservice",
            options={
                "managed": False,
                "verbose_name": "Proposition de service - AFFICHÉ",
                "verbose_name_plural": "Propositions de service - AFFICHÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="revisionacteur",
            options={
                "verbose_name": "ACTEUR de l'EC - CORRIGÉ",
                "verbose_name_plural": "ACTEURS de l'EC - CORRIGÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="revisionpropositionservice",
            options={
                "verbose_name": "PROPOSITION DE SERVICE - CORRIGÉ",
                "verbose_name_plural": "PROPOSITIONS DE SERVICE - CORRIGÉ",
            },
        ),
    ]
