# Generated by Django 4.2.9 on 2024-03-06 14:49

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0044_alter_metaoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="afficher",
            field=models.BooleanField(default=True),
        ),
    ]
