# Generated by Django 4.2.9 on 2024-03-07 09:57

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0045_action_afficher"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteurtype",
            name="code_import",
            field=models.CharField(
                blank=True,
                help_text=(
                    "This field is used to manage the import of data."
                    " Any update can break the import data process"
                ),
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="code_import",
            field=models.CharField(
                blank=True,
                help_text=(
                    "This field is used to manage the import of data."
                    " Any update can break the import data process"
                ),
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED : please use logo_file",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos",
                validators=[qfdmo.models.acteur.validate_logo],
            ),
        ),
    ]
