# Generated by Django 4.2.9 on 2024-03-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0046_acteurtype_and_source_code_import_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="correctionequipepropositionservice",
            name="rps_unique_by_correctionequipeacteur_action_service",
        ),
        migrations.RemoveConstraint(
            model_name="revisionpropositionservice",
            name="rps_unique_by_revisionacteur_action_service",
        ),
        migrations.RenameField(
            model_name="correctionequipepropositionservice",
            old_name="revision_acteur",
            new_name="acteur",
        ),
        migrations.RenameField(
            model_name="revisionpropositionservice",
            old_name="revision_acteur",
            new_name="acteur",
        ),
        migrations.AddConstraint(
            model_name="correctionequipepropositionservice",
            constraint=models.UniqueConstraint(
                fields=("acteur", "action", "acteur_service"),
                name="rps_unique_by_correctionequipeacteur_action_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionpropositionservice",
            constraint=models.UniqueConstraint(
                fields=("acteur", "action", "acteur_service"),
                name="rps_unique_by_revisionacteur_action_service",
            ),
        ),
    ]
