# Generated by Django 4.2.9 on 2024-03-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0047_remove_correctionequipepropositionservice_rps_unique_by_correctionequipeacteur_action_service_and_mo",
        ),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE qfdmo_displayedpropositionservicetemp_sous_categories RENAME displayedpropositionservicetemp_id to displayedpropositionservice_id",
            "ALTER TABLE qfdmo_displayedpropositionservicetemp_sous_categories RENAME displayedpropositionservice_id to displayedpropositionservicetemp_id",
        ),
    ]
