# Generated by Django 4.2.9 on 2024-03-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0049_remove_final_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displayedacteur",
            options={
                "verbose_name": "ACTEUR de l'EC - AFFICHÉ",
                "verbose_name_plural": "ACTEURS de l'EC - AFFICHÉ",
            },
        ),
        migrations.AlterModelOptions(
            name="displayedpropositionservice",
            options={
                "verbose_name": "Proposition de service - AFFICHÉ",
                "verbose_name_plural": "Proposition de service - AFFICHÉ",
            },
        ),
        migrations.DeleteModel(
            name="CorrectionEquipeActeur",
        ),
        migrations.DeleteModel(
            name="CorrectionEquipePropositionService",
        ),
    ]
