# Generated by Django 4.2.9 on 2024-03-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0050_remove_correction_equipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayedPropositionServiceTempSousCategorie",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "qfdmo_displayedpropositionservicetemp_sous_categories",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="FinalPropositionService",
        ),
        migrations.DeleteModel(
            name="CorrectionActeur",
        ),
        migrations.DeleteModel(
            name="FinalActeur",
        ),
        migrations.RemoveField(
            model_name="acteur",
            name="manuel",
        ),
        migrations.RemoveField(
            model_name="acteur",
            name="multi_base",
        ),
        migrations.RemoveField(
            model_name="displayedacteur",
            name="manuel",
        ),
        migrations.RemoveField(
            model_name="displayedacteur",
            name="multi_base",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="manuel",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="multi_base",
        ),
        migrations.RemoveField(
            model_name="revisionacteur",
            name="manuel",
        ),
        migrations.RemoveField(
            model_name="revisionacteur",
            name="multi_base",
        ),
    ]
