# Generated by Django 4.2.9 on 2024-03-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0051_remove_useless_models_and_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DagRun",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dag_id", models.CharField(max_length=250)),
                ("run_id", models.CharField(max_length=250)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_VALIDATE", "To Validate"),
                            ("TO_INSERT", "To Insert"),
                            ("REJECTED", "Rejected"),
                            ("FINISHED", "Finished"),
                        ],
                        default="TO_VALIDATE",
                        max_length=50,
                    ),
                ),
                ("meta_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DagRunChange",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meta_data", models.JSONField(blank=True, null=True)),
                ("suggestion", models.JSONField(blank=True, null=True)),
                (
                    "dag_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qfdmo.dagrun"
                    ),
                ),
            ],
        ),
    ]
