# Generated by Django 4.2.9 on 2024-04-04 13:36

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0054_manage_horaires_osm_vs_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelQualite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("libelle", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="This field is used to manage the import of data. Any update can break the import data process",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("afficher", models.BooleanField(default=True)),
                (
                    "bonus",
                    models.BooleanField(
                        default=False, help_text="Ouvre les droits à un bonus financier"
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "logo_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos",
                        validators=[qfdmo.models.acteur.validate_logo],
                    ),
                ),
            ],
            options={
                "verbose_name": "Label qualité",
                "verbose_name_plural": "Labels qualité",
            },
        ),
        migrations.CreateModel(
            name="ActeurLabelQualite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "acteur",
                    models.ForeignKey(
                        db_column="displayedacteur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.displayedacteurtemp",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        db_column="labelqualite_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.labelqualite",
                    ),
                ),
            ],
            options={
                "db_table": "qfdmo_displayedacteurtemp_labels",
            },
        ),
        migrations.AddField(
            model_name="acteur",
            name="labels",
            field=models.ManyToManyField(to="qfdmo.labelqualite"),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="labels",
            field=models.ManyToManyField(to="qfdmo.labelqualite"),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="labels",
            field=models.ManyToManyField(
                through="qfdmo.ActeurLabelQualite", to="qfdmo.labelqualite"
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="labels",
            field=models.ManyToManyField(to="qfdmo.labelqualite"),
        ),
    ]
