# Generated by Django 4.2.9 on 2024-04-04 09:45

from django.db import migrations


def assign_reparacteur_label(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    LabelQualite = apps.get_model("qfdmo", "LabelQualite")

    label, _ = LabelQualite.objects.get_or_create(
        libelle="Repar'Acteur",
        code="reparacteur",
        afficher=True,
    )
    for a in Acteur.objects.filter(label_reparacteur=True):
        a.labels.add(label)


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0055_labelqualite"),
    ]

    operations = [
        migrations.RunPython(assign_reparacteur_label, migrations.RunPython.noop),
    ]
