# Generated by Django 4.2.9 on 2024-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0056_assign_reparacteur_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acteur",
            name="label_reparacteur",
        ),
        migrations.RemoveField(
            model_name="displayedacteur",
            name="label_reparacteur",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="label_reparacteur",
        ),
        migrations.RemoveField(
            model_name="revisionacteur",
            name="label_reparacteur",
        ),
    ]
