# Generated by Django 4.2.9 on 2024-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0057_remove_acteur_label_reparacteur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acteurservice",
            old_name="nom_affiche",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="acteurtype",
            old_name="nom_affiche",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="nom_affiche",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="actiondirection",
            old_name="nom_affiche",
            new_name="libelle",
        ),
    ]
