# Generated by Django 4.2.9 on 2024-04-04 16:11

from django.db import migrations, models
from django.db.models import Q


def set_code(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    for source in Source.objects.filter(Q(code="") | Q(code__isnull=True)):
        source.code = source.libelle
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0058_rename_nom_to_libelle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="nom",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="code_import",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="source",
            name="logo",
        ),
        migrations.RunPython(set_code, migrations.RunPython.noop),
    ]
