# Generated by Django 4.2.9 on 2024-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0059_refactor_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="code",
            field=models.CharField(
                help_text="This field is used to manage the import of data. Any update can break the import data process",
                max_length=255,
                unique=True,
            ),
        ),
    ]
