# Generated by Django 4.2.9 on 2024-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0061_remove_lvoa_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acteurservice",
            old_name="nom",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="acteurtype",
            old_name="nom",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="acteurtype",
            name="code_import",
        ),
    ]
