# Generated by Django 4.2.9 on 2024-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0062_rename_nom_acteurservice_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="nom",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="actiondirection",
            old_name="nom",
            new_name="code",
        ),
    ]
