# Generated by Django 4.2.9 on 2024-04-05 07:15

import django.utils.timezone
from django.db import migrations, models
from unidecode import unidecode


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0063_rename_nom_to_code_for_direction_and_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="souscategorieobjet",
            options={
                "ordering": ["libelle"],
                "verbose_name": "Sous catégorie d'objets",
                "verbose_name_plural": "Sous catégories d'objets",
            },
        ),
        migrations.AlterField(
            model_name="souscategorieobjet",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RenameField(
            model_name="categorieobjet",
            old_name="nom",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="objet",
            old_name="nom",
            new_name="libelle",
        ),
        migrations.RenameField(
            model_name="souscategorieobjet",
            old_name="nom",
            new_name="libelle",
        ),
        migrations.AddField(
            model_name="categorieobjet",
            name="code",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objet",
            name="code",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorieobjet",
            name="libelle",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="objet",
            name="libelle",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="souscategorieobjet",
            name="libelle",
            field=models.CharField(max_length=255),
        ),
    ]
