# Generated by Django 5.0.4 on 2024-04-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0066_alter_code_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieobjet",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dagrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_VALIDATE", "To Validate"),
                    ("TO_INSERT", "To Insert"),
                    ("REJECTED", "Rejected"),
                    ("FINISHED", "Finished"),
                ],
                default="TO_VALIDATE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dagrunchange",
            name="dag_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dagrunchanges",
                to="qfdmo.dagrun",
            ),
        ),
    ]
