# Generated by Django 5.0.4 on 2024-04-16 15:23

from django.db import migrations


def assign_ess(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    LabelQualite = apps.get_model("qfdmo", "LabelQualite")

    label, _ = LabelQualite.objects.get_or_create(
        code="ess",
        defaults={
            "libelle": "Enseigne de l'économie sociale et solidaire",
            "afficher": True,
            "type_enseigne": True,
            "url": "https://www.economie.gouv.fr/cedef/economie-sociale-et-solidaire",
        },
    )
    for a in Acteur.objects.filter(acteur_type__code="ess"):
        a.labels.add(label)


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0068_labelqualite_type_enseigne"),
    ]

    operations = [
        migrations.RunPython(assign_ess, migrations.RunPython.noop),
    ]
