# Generated by Django 5.0.4 on 2024-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0070_actiongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="SousCategorieObjet",
            name="afficher",
            field=models.BooleanField(default=True),
        )
    ]
