# Generated by Django 5.0.4 on 2024-05-31 06:31

from django.db import migrations


def set_sscat_afficher_false(apps, schema_editor):
    SousCategorieObjet = apps.get_model("qfdmo", "SousCategorieObjet")

    for sous_categorie_objet in SousCategorieObjet.objects.all():
        if not sous_categorie_objet.displayedpropositionservice_set.filter(
            action__afficher=True
        ).exists():
            sous_categorie_objet.afficher = False
            sous_categorie_objet.save()


def set_sscat_afficher_true(apps, schema_editor):
    SousCategorieObjet = apps.get_model("qfdmo", "SousCategorieObjet")
    SousCategorieObjet.objects.all().update(afficher=True)


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0071_objet_afficher"),
    ]

    operations = [
        migrations.RunPython(set_sscat_afficher_false, set_sscat_afficher_true),
    ]
