# Generated by Django 5.0.4 on 2024-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0072_objet_set_afficher_false"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="action",
            name="couleur",
            field=models.CharField(
                blank=True,
                default="yellow-tournesol",
                help_text="Couleur du badge à choisir dans le DSFR\nCouleurs disponibles : blue-france, green-tilleul-verveine, green-bourgeon,\ngreen-emeraude, green-menthe, green-archipel, blue-ecume, blue-cumulus, purple-glycine,\npink-macaron, pink-tuile, yellow-tournesol, yellow-moutarde, orange-terre-battue,\nbrown-cafe-creme,brown-caramel, brown-opera, beige-gris-galet, pink-tuile-850,\ngreen-menthe-850,green-bourgeon-850, yellow-moutarde-850, blue-ecume-850,\ngreen-menthe-sun-373,blue-cumulus-sun-368, orange-terre-battue-main-645,\nbrown-cafe-creme-main-782, purple-glycine-main-494, green-menthe-main-548\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="libelle_groupe",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Libellé de l'action dans le groupe",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="groupeaction",
            name="couleur",
            field=models.CharField(
                blank=True,
                default="yellow-tournesol",
                help_text="Couleur du badge à choisir dans le DSFR\nCouleurs disponibles : blue-france, green-tilleul-verveine, green-bourgeon,\ngreen-emeraude, green-menthe, green-archipel, blue-ecume, blue-cumulus, purple-glycine,\npink-macaron, pink-tuile, yellow-tournesol, yellow-moutarde, orange-terre-battue,\nbrown-cafe-creme,brown-caramel, brown-opera, beige-gris-galet, pink-tuile-850,\ngreen-menthe-850,green-bourgeon-850, yellow-moutarde-850, blue-ecume-850,\ngreen-menthe-sun-373,blue-cumulus-sun-368, orange-terre-battue-main-645,\nbrown-cafe-creme-main-782, purple-glycine-main-494, green-menthe-main-548\n",
                max_length=255,
                null=True,
            ),
        ),
    ]
