# Generated by Django 5.0.4 on 2024-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0073_alter_action_and_groupeaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dagrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_VALIDATE", "To Validate"),
                    ("TO_INSERT", "To Insert"),
                    ("REJECTED", "Rejected"),
                    ("FINISHED", "Finished"),
                ],
                default="TO_VALIDATE",
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="sous_categories",
        ),
        migrations.AddField(
            model_name="displayedpropositionservicetemp",
            name="sous_categories",
            field=models.ManyToManyField(
                through="qfdmo.DisplayedPropositionServiceTempSousCategorie",
                to="qfdmo.souscategorieobjet",
            ),
        ),
    ]
