# Generated by Django 5.0.4 on 2024-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0073_alter_action_and_groupeaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="acteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="acteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                max_length=255,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            (
                "alter table qfdmo_acteur alter column uniquement_sur_rdv"
                " SET DEFAULT false;"
                "alter table qfdmo_acteur alter column exclusivite_de_reprisereparation"
                " SET DEFAULT false;"
                "alter table qfdmo_acteur alter column cree_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_acteur alter column modifie_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_acteur alter column statut"
                " SET DEFAULT 'ACTIF';"
            ),
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (
                "alter table qfdmo_revisionacteur alter column uniquement_sur_rdv"
                " SET DEFAULT false;"
                "alter table qfdmo_revisionacteur alter column exclusivite_de_reprisereparation"
                " SET DEFAULT false;"
                "alter table qfdmo_revisionacteur alter column cree_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_revisionacteur alter column modifie_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_revisionacteur alter column statut"
                " SET DEFAULT 'ACTIF';"
            ),
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (
                "alter table qfdmo_displayedacteur alter column uniquement_sur_rdv"
                " SET DEFAULT false;"
                "alter table qfdmo_displayedacteur alter column exclusivite_de_reprisereparation"
                " SET DEFAULT false;"
                "alter table qfdmo_displayedacteur alter column cree_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_displayedacteur alter column modifie_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_displayedacteur alter column statut"
                " SET DEFAULT 'ACTIF';"
            ),
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (
                "alter table qfdmo_displayedacteurtemp alter column uniquement_sur_rdv"
                " SET DEFAULT false;"
                "alter table qfdmo_displayedacteurtemp alter column exclusivite_de_reprisereparation"
                " SET DEFAULT false;"
                "alter table qfdmo_displayedacteurtemp alter column cree_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_displayedacteurtemp alter column modifie_le"
                " SET DEFAULT NOW();"
                "alter table qfdmo_displayedacteurtemp alter column statut"
                " SET DEFAULT 'ACTIF';"
            ),
            migrations.RunSQL.noop,
        ),
    ]
