# Generated by Django 5.0.4 on 2024-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0073_alter_action_and_groupeaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                default="Particuliers et professionnels",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="acteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                default="1 pour 0",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="acteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                default="Particuliers et professionnels",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                default="1 pour 0",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                default="Particuliers et professionnels",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                default="1 pour 0",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="public_accueilli",
            field=models.CharField(
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                ],
                default="Particuliers et professionnels",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="reprise",
            field=models.CharField(
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                default="1 pour 0",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
    ]
