# Generated by Django 5.0.4 on 2024-07-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0074_alter_dagrun_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="sous_categories",
        ),
        migrations.DeleteModel(
            name="DisplayedPropositionServiceTempSousCategorie",
        ),
    ]
