# Generated by Django 5.0.4 on 2024-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0002_alter_produit_options_remove_produit_sous_categories_and_more"),
        ("qfdmo", "0074_souscategorieobjet_qfdmd_afficher_carte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="souscategorieobjet",
            name="qfdmd_produits",
            field=models.ManyToManyField(
                related_name="sous_categories",
                to="qfdmd.produit",
                verbose_name="Produits Que Faire De Mes Déchets & Objets",
            ),
        ),
    ]
