# Generated by Django 5.0.4 on 2024-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0075_souscategorieobjet_qfdmd_produits_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="souscategorieobjet",
            old_name="qfdmd_afficher_carte",
            new_name="afficher_carte",
        ),
        migrations.AddField(
            model_name="souscategorieobjet",
            name="url_carte",
            field=models.URLField(
                blank=True,
                help_text="La carte est affichée dans l'assistant si la case ci-dessus est cochée",
                max_length=255,
                verbose_name="URL de la carte",
            ),
        ),
    ]
