# Generated by Django 5.0.4 on 2024-07-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0004_remove_produit_titre_produit_libelle_and_more"),
        (
            "qfdmo",
            "0076_rename_qfdmd_afficher_carte_souscategorieobjet_afficher_carte_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="souscategorieobjet",
            name="url_carte",
        ),
        migrations.AlterField(
            model_name="souscategorieobjet",
            name="qfdmd_produits",
            field=models.ManyToManyField(
                null=True,
                related_name="sous_categories",
                to="qfdmd.produit",
                verbose_name="Produits Que Faire De Mes Déchets & Objets",
            ),
        ),
    ]
