# Generated by Django 5.0.4 on 2024-07-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0074_acteur_exclusivite_reprise_rdv_public"),
        ("qfdmo", "0076_displayedpropositionservicetempsouscategorie_and_more"),
    ]

    operations = []
