# Generated by Django 5.0.4 on 2024-07-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0076_displayedpropositionservicetempsouscategorie_and_more"),
        ("qfdmo", "0077_remove_souscategorieobjet_url_carte_and_more"),
    ]

    operations = []
