# Generated by Django 5.0.4 on 2024-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0004_remove_produit_titre_produit_libelle_and_more"),
        ("qfdmo", "0078_merge_20240708_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="souscategorieobjet",
            name="qfdmd_produits",
            field=models.ManyToManyField(
                blank=True,
                related_name="sous_categories",
                to="qfdmd.produit",
                verbose_name="Produits Que Faire De Mes Déchets & Objets",
            ),
        ),
    ]
