# Generated by Django 5.0.4 on 2024-07-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0077_acteur_exclusivite_de_reprisereparation_and_more"),
        ("qfdmo", "0079_alter_souscategorieobjet_qfdmd_produits"),
    ]

    operations = []
