# Generated by Django 5.0.4 on 2024-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0080_merge_20240710_1444"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Exclusivité de reprise/réparation",
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Exclusivité de reprise/réparation",
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Exclusivité de reprise/réparation",
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Exclusivité de reprise/réparation",
            ),
        ),
    ]
