# Generated by Django 5.0.4 on 2024-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0082_alter_acteur_exclusivite_de_reprisereparation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="uniquement_sur_rdv",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
