# Generated by Django 5.0.4 on 2024-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0083_alter_acteur_exclusivite_de_reprisereparation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
    ]
