# Generated by Django 5.0.4 on 2024-07-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0083_alter_acteur_exclusivite_de_reprisereparation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="acteur_services",
            field=models.ManyToManyField(blank=True, to="qfdmo.acteurservice"),
        ),
        migrations.CreateModel(
            name="ActeurActeurService",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "acteur",
                    models.ForeignKey(
                        db_column="displayedacteur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.displayedacteurtemp",
                    ),
                ),
                (
                    "acteur_service",
                    models.ForeignKey(
                        db_column="acteurservice_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.acteurservice",
                    ),
                ),
            ],
            options={
                "db_table": "qfdmo_displayedacteurtemp_acteur_services",
            },
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="acteur_services",
            field=models.ManyToManyField(
                blank=True,
                through="qfdmo.ActeurActeurService",
                to="qfdmo.acteurservice",
            ),
        ),
    ]
