# Generated by Django 5.0.4 on 2024-07-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0084_acteur_acteur_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedpropositionservice",
            name="acteur_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurservice",
            ),
        ),
        migrations.AlterField(
            model_name="displayedpropositionservicetemp",
            name="acteur_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurservice",
            ),
        ),
        migrations.AlterField(
            model_name="propositionservice",
            name="acteur_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurservice",
            ),
        ),
        migrations.AlterField(
            model_name="revisionpropositionservice",
            name="acteur_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurservice",
            ),
        ),
    ]
