# Generated by Django 5.0.4 on 2024-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0086_remove_duplicated_ps"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="propositionservice",
            name="ps_unique_by_acteur_action_service",
        ),
        migrations.RemoveConstraint(
            model_name="revisionpropositionservice",
            name="rps_unique_by_revisionacteur_action_service",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservice",
            name="acteur_service",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="acteur_service",
        ),
        migrations.RemoveField(
            model_name="propositionservice",
            name="acteur_service",
        ),
        migrations.RemoveField(
            model_name="revisionpropositionservice",
            name="acteur_service",
        ),
        migrations.AddConstraint(
            model_name="propositionservice",
            constraint=models.UniqueConstraint(
                fields=("acteur", "action"), name="ps_unique_by_acteur"
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionpropositionservice",
            constraint=models.UniqueConstraint(
                fields=("acteur", "action"), name="rps_unique_by_revisionacteur"
            ),
        ),
    ]
