# Generated by Django 5.0.4 on 2024-08-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0087_remove_propositionservice_ps_unique_by_acteur_action_service_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acteurservice",
            options={
                "ordering": ["libelle"],
                "verbose_name": "Service proposé",
                "verbose_name_plural": "Services proposés",
            },
        ),
    ]
