# Generated by Django 5.0.4 on 2024-08-21 07:00

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0088_alter_acteurservice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionacteur",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicats",
                to="qfdmo.revisionacteur",
                validators=[qfdmo.models.acteur.clean_parent],
            ),
        ),
    ]
