# Generated by Django 5.0.4 on 2024-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0088_alter_acteurservice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionacteur",
            name="is_parent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="parent_id",
            field=models.CharField(
                blank=True, db_column="parent_id", max_length=255, null=True
            ),
        ),
    ]
