# Generated by Django 5.0.4 on 2024-08-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0088_alter_acteurservice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
    ]
