# Generated by Django 5.0.4 on 2024-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0088_alter_acteurservice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="objet",
            name="identifiant_qfdmod",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identifiant QFDMD"
            ),
        ),
    ]
