# Generated by Django 5.0.4 on 2024-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0089_objet_identifiant_qfdmod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="libelle",
            field=models.CharField(max_length=255),
        ),
    ]
