# Generated by Django 5.0.4 on 2024-08-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0090_acteur_action_principale_and_more"),
        ("qfdmo", "0090_alter_source_libelle"),
    ]

    operations = []
