# Generated by Django 5.0.4 on 2024-08-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0089_revisionacteur_parent_and_is_parent"),
        ("qfdmo", "0091_merge_20240822_1558"),
    ]

    operations = []
