# Generated by Django 5.0.4 on 2024-09-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0092_merge_20240827_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayedacteur",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="displayed_acteurs", to="qfdmo.source"
            ),
        ),
        migrations.CreateModel(
            name="DisplayedActeurTempSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "acteur",
                    models.ForeignKey(
                        db_column="displayedacteur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.displayedacteurtemp",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_id",
                        to="qfdmo.source",
                    ),
                ),
            ],
            options={
                "db_table": "qfdmo_displayedacteurtemp_sources",
                "unique_together": {("acteur_id", "source_id")},
            },
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="displayed_acteur_temps",
                through="qfdmo.DisplayedActeurTempSource",
                to="qfdmo.source",
            ),
        ),
    ]
