# Generated by Django 5.0.4 on 2024-08-27 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0092_merge_20240827_2215"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeurActeurSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "displayed_acteur",
                    models.ForeignKey(
                        db_column="displayedacteur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acteur_source_relations",
                        to="qfdmo.displayedacteur",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="displayed_acteur_sources",
                        to="qfdmo.source",
                    ),
                ),
            ],
            options={
                "db_table": "qfdmo_displayedacteur_acteur_sources",
                "unique_together": {("displayed_acteur", "source")},
            },
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="acteur_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_displayed_acteurs",
                through="qfdmo.ActeurActeurSource",
                to="qfdmo.source",
            ),
        ),
        migrations.CreateModel(
            name="ActeurActeurSourceTemp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "displayed_acteur_temp",
                    models.ForeignKey(
                        db_column="displayedacteur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acteur_source_temp_relations",
                        to="qfdmo.displayedacteurtemp",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="displayed_acteur_temp_sources",
                        to="qfdmo.source",
                    ),
                ),
            ],
            options={
                "db_table": "qfdmo_displayedacteur_acteur_sources_temp",
                "unique_together": {("displayed_acteur_temp", "source")},
            },
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="acteur_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_displayed_acteur_temps",
                through="qfdmo.ActeurActeurSourceTemp",
                to="qfdmo.source",
            ),
        ),
    ]
