# Generated by Django 5.1.1 on 2024-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0093_displayedacteur_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="dagrunchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_VALIDATE", "To Validate"),
                    ("TO_INSERT", "To Insert"),
                    ("REJECTED", "Rejected"),
                    ("FINISHED", "Finished"),
                ],
                default="TO_VALIDATE",
                max_length=50,
            ),
        ),
    ]
