# Generated by Django 5.1.1 on 2024-10-08 16:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0094_dagrunchange_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayedacteur",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
