# Generated by Django 5.1.1 on 2024-10-10 21:44

import shortuuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0096_alter_acteurservice_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayedacteur",
            name="uuid",
            field=models.CharField(
                default=shortuuid.uuid, editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="uuid",
            field=models.CharField(
                default=shortuuid.uuid, editable=False, max_length=255
            ),
        ),
    ]
