# Generated by Django 5.1.1 on 2024-11-06 08:27

from django.db import migrations


def assign_non_reparacteur_cma(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    source_cma_historique = Source(
        libelle="CMA historique - non-reparacteur",
        code="cma_historique",
        afficher=False,
    )
    source_cma_historique.save()
    Acteur.objects.filter(
        source__code="CMA - Chambre des métiers et de l'artisanat"
    ).exclude(labels__code="reparacteur").update(source=source_cma_historique)
    RevisionActeur.objects.filter(
        identifiant_unique__in=Acteur.objects.filter(
            source=source_cma_historique
        ).values_list("identifiant_unique", flat=True)
    ).update(source=source_cma_historique)


def unassign_non_reparacteur_cma(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    source_cma = Source.objects.get(code="CMA - Chambre des métiers et de l'artisanat")
    source_cma_historique = Source.objects.get(code="cma_historique")
    source_lvao = Source.objects.get(code="Longue Vie Aux Objets")
    RevisionActeur.objects.filter(
        identifiant_unique__in=Acteur.objects.filter(
            source=source_cma_historique
        ).values_list("identifiant_unique", flat=True)
    ).update(source=source_lvao)
    Acteur.objects.filter(source=source_cma_historique).update(source=source_cma)
    source_cma_historique.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0098_alter_action_couleur_alter_groupeaction_couleur"),
    ]

    operations = [
        migrations.RunPython(assign_non_reparacteur_cma, unassign_non_reparacteur_cma)
    ]
