# Generated by Django 5.1.1 on 2024-11-07 10:27

from typing import List, Tuple

import colorfield.fields
from django.db import migrations

action_couleur_mapping = [
    ("orange-terre-battue", "orange-terre-battue-main-645"),
    ("purple-glycine", "purple-glycine-main-494"),
    ("green-archipel", "green-menthe-main-548"),
    ("yellow-moutarde", "yellow-tournesol-moon-922-active"),
    ("blue-france", "blue-cumulus-main-526"),
    ("brown-caramel", "brown-cafe-creme-main-782"),
]

groupe_action_couleur_mapping: List[List[str]] = [
    ["trier", "purple-glycine-975", "purple-glycine-main-494"],
    ["vendre_acheter", "brown-cafe-creme-950", "brown-cafe-creme-main-782"],
    ["emprunter_preter_louer", "pink-tuile-975", "pink-tuile-main-556"],
    ["donner_echanger", "blue-cumulus-975", "blue-cumulus-main-526"],
    ["reparer", "green-menthe-975", "green-menthe-main-548"],
]


def set_hexadecimal_colors(apps, schema_editor):
    from dsfr_hacks.colors import DSFRColors

    Action = apps.get_model("qfdmo", "Action")
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")

    for old, new in action_couleur_mapping:
        Action.objects.filter(couleur=old).update(couleur=DSFRColors[new])

    for code, couleur_claire, couleur in groupe_action_couleur_mapping:
        GroupeAction.objects.filter(code=code).update(
            couleur=DSFRColors[couleur], couleur_claire=DSFRColors[couleur_claire]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0098_alter_action_couleur_alter_groupeaction_couleur"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeaction",
            name="couleur_claire",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[
                    ("#AEA397", "beige-gris-galet"),
                    ("#3558A2", "blue-cumulus-sun-368"),
                    ("#417DC4", "blue-cumulus"),
                    ("#bfccfb", "blue-ecume-850"),
                    ("#465F9D", "blue-ecume"),
                    ("#0055FF", "blue-france"),
                    ("#D1B781", "brown-cafe-creme-main-782"),
                    ("#D1B781", "brown-cafe-creme"),
                    ("#C08C65", "brown-caramel"),
                    ("#BD987A", "brown-opera"),
                    ("#009099", "green-archipel"),
                    ("#95e257", "green-bourgeon-850"),
                    ("#68A532", "green-bourgeon"),
                    ("#00A95F", "green-emeraude"),
                    ("#73e0cf", "green-menthe-850"),
                    ("#009081", "green-menthe-main-548"),
                    ("#37635f", "green-menthe-sun-373"),
                    ("#009081", "green-menthe"),
                    ("#B7A73F", "green-tilleul-verveine"),
                    ("#E4794A", "orange-terre-battue-main-645"),
                    ("#E4794A", "orange-terre-battue"),
                    ("#E18B76", "pink-macaron"),
                    ("#fcbfb7", "pink-tuile-850"),
                    ("#CE614A", "pink-tuile"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#A558A0", "purple-glycine"),
                    ("#fcc63a", "yellow-moutarde-850"),
                    ("#C3992A", "yellow-moutarde"),
                    ("#e9c53b", "yellow-tournesol"),
                    ("#bb8568", "brown-caramel-sun-425-hover"),
                    ("#FEF3FD", "purple-glycine-975"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#F3F6FE", "blue-cumulus-975"),
                    ("#417DC4", "blue-cumulus-main-526"),
                    ("#D1B781", "brown-cafe-creme-main-78"),
                    ("#F7ECDB", "brown-cafe-creme-950"),
                    ("#009081", "green-menthe-main-548"),
                    ("#DFFDF7", "green-menthe-975"),
                    ("#CE614A", "pink-tuile-main-556"),
                    ("#FEF4F3", "pink-tuile-975"),
                ],
                default="#C3992A",
                image_field=None,
                max_length=255,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="couleur",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[
                    ("#AEA397", "beige-gris-galet"),
                    ("#3558A2", "blue-cumulus-sun-368"),
                    ("#417DC4", "blue-cumulus"),
                    ("#bfccfb", "blue-ecume-850"),
                    ("#465F9D", "blue-ecume"),
                    ("#0055FF", "blue-france"),
                    ("#D1B781", "brown-cafe-creme-main-782"),
                    ("#D1B781", "brown-cafe-creme"),
                    ("#C08C65", "brown-caramel"),
                    ("#BD987A", "brown-opera"),
                    ("#009099", "green-archipel"),
                    ("#95e257", "green-bourgeon-850"),
                    ("#68A532", "green-bourgeon"),
                    ("#00A95F", "green-emeraude"),
                    ("#73e0cf", "green-menthe-850"),
                    ("#009081", "green-menthe-main-548"),
                    ("#37635f", "green-menthe-sun-373"),
                    ("#009081", "green-menthe"),
                    ("#B7A73F", "green-tilleul-verveine"),
                    ("#E4794A", "orange-terre-battue-main-645"),
                    ("#E4794A", "orange-terre-battue"),
                    ("#E18B76", "pink-macaron"),
                    ("#fcbfb7", "pink-tuile-850"),
                    ("#CE614A", "pink-tuile"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#A558A0", "purple-glycine"),
                    ("#fcc63a", "yellow-moutarde-850"),
                    ("#C3992A", "yellow-moutarde"),
                    ("#e9c53b", "yellow-tournesol"),
                    ("#bb8568", "brown-caramel-sun-425-hover"),
                    ("#FEF3FD", "purple-glycine-975"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#F3F6FE", "blue-cumulus-975"),
                    ("#417DC4", "blue-cumulus-main-526"),
                    ("#D1B781", "brown-cafe-creme-main-78"),
                    ("#F7ECDB", "brown-cafe-creme-950"),
                    ("#009081", "green-menthe-main-548"),
                    ("#DFFDF7", "green-menthe-975"),
                    ("#CE614A", "pink-tuile-main-556"),
                    ("#FEF4F3", "pink-tuile-975"),
                ],
                default="#C3992A",
                help_text="Cette couleur est utilisée uniquement pour la version formulaire (épargnons).",
                image_field=None,
                max_length=255,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="groupeaction",
            name="couleur",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[
                    ("#AEA397", "beige-gris-galet"),
                    ("#3558A2", "blue-cumulus-sun-368"),
                    ("#417DC4", "blue-cumulus"),
                    ("#bfccfb", "blue-ecume-850"),
                    ("#465F9D", "blue-ecume"),
                    ("#0055FF", "blue-france"),
                    ("#D1B781", "brown-cafe-creme-main-782"),
                    ("#D1B781", "brown-cafe-creme"),
                    ("#C08C65", "brown-caramel"),
                    ("#BD987A", "brown-opera"),
                    ("#009099", "green-archipel"),
                    ("#95e257", "green-bourgeon-850"),
                    ("#68A532", "green-bourgeon"),
                    ("#00A95F", "green-emeraude"),
                    ("#73e0cf", "green-menthe-850"),
                    ("#009081", "green-menthe-main-548"),
                    ("#37635f", "green-menthe-sun-373"),
                    ("#009081", "green-menthe"),
                    ("#B7A73F", "green-tilleul-verveine"),
                    ("#E4794A", "orange-terre-battue-main-645"),
                    ("#E4794A", "orange-terre-battue"),
                    ("#E18B76", "pink-macaron"),
                    ("#fcbfb7", "pink-tuile-850"),
                    ("#CE614A", "pink-tuile"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#A558A0", "purple-glycine"),
                    ("#fcc63a", "yellow-moutarde-850"),
                    ("#C3992A", "yellow-moutarde"),
                    ("#e9c53b", "yellow-tournesol"),
                    ("#bb8568", "brown-caramel-sun-425-hover"),
                    ("#FEF3FD", "purple-glycine-975"),
                    ("#A558A0", "purple-glycine-main-494"),
                    ("#F3F6FE", "blue-cumulus-975"),
                    ("#417DC4", "blue-cumulus-main-526"),
                    ("#D1B781", "brown-cafe-creme-main-78"),
                    ("#F7ECDB", "brown-cafe-creme-950"),
                    ("#009081", "green-menthe-main-548"),
                    ("#DFFDF7", "green-menthe-975"),
                    ("#CE614A", "pink-tuile-main-556"),
                    ("#FEF4F3", "pink-tuile-975"),
                ],
                default="#C3992A",
                image_field=None,
                max_length=255,
                null=True,
                samples=None,
            ),
        ),
        migrations.RunPython(set_hexadecimal_colors, migrations.RunPython.noop),
    ]
