# Generated by Django 5.1.1 on 2024-10-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0099_alter_action_couleur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="couleur",
            new_name="couleur_foncee",
        ),
    ]
