# Generated by Django 5.1.1 on 2024-11-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0099_cma_source_update"),
        ("qfdmo", "0099_groupeaction_couleur_claire_alter_action_couleur_and_more"),
    ]

    operations = []
