# Generated by Django 5.1.1 on 2024-11-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0100_cma_source_code"),
        ("qfdmo", "0100_merge_20241107_1937"),
    ]

    operations = []
