# Generated by Django 5.1.1 on 2024-10-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0099_alter_action_couleur_squashed_0102_alter_action_couleur_claire_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="couleur_foncee",
            new_name="couleur",
        ),
    ]
