# Generated by Django 5.1.1 on 2024-12-03 07:25

from django.db import migrations


def rename_ordredespharmaciens(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    ordredespharmaciens = Source.objects.filter(
        code="Ordre National Des Pharmaciens"
    ).first()
    if ordredespharmaciens:
        ordredespharmaciens.code = "ordredespharmaciens"
        ordredespharmaciens.save()


def rollback_rename_ordredespharmaciens(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    ordredespharmaciens = Source.objects.filter(code="ordredespharmaciens").first()
    if ordredespharmaciens:
        ordredespharmaciens.code = "Ordre National Des Pharmaciens"
        ordredespharmaciens.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0103_acteur_siren_displayedacteur_siren_and_more"),
    ]

    operations = [
        migrations.RunPython(
            rename_ordredespharmaciens,
            rollback_rename_ordredespharmaciens,
        ),
    ]
