# Generated by Django 5.1.1 on 2024-11-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0105_groupeaction_couleur_claire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="couleur_claire",
        ),
    ]
