# Generated by Django 5.1.1 on 2024-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0105_bancache"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="licence",
            field=models.CharField(
                choices=[("Licence Ouverte", "Licence Ouverte"), ("ODBL", "ODBL")],
                db_default="Licence Ouverte",
                default="Licence Ouverte",
            ),
        ),
    ]
