# Generated by Django 5.1.1 on 2024-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0106_source_licence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="licence",
            field=models.CharField(
                choices=[
                    ("OPEN_LICENSE", "Licence Ouverte"),
                    ("ODBL", "ODBL"),
                    ("CC_BY_NC_SA", "CC-BY-NC-SA"),
                    ("NO_LICENSE", "Pas de licence"),
                ],
                db_default="NO_LICENSE",
                default="NO_LICENSE",
            ),
        ),
    ]
