# Generated by Django 5.1.1 on 2024-10-12 07:55

from django.db import migrations

mapping = {
    "ECODDS": {"old_code": "", "new_code": "ecodds"},
    "Emmaus Connect": {"old_code": "emmaus_connect", "new_code": "emmausconnect"},
    "RecyclOptics": {"old_code": "RecyclOptics", "new_code": "recycloptics"},
    "Emmaüs Défi": {"old_code": "", "new_code": "emmausdefi"},
    "Lunettes de Zac": {"old_code": "lunettes_de_zac", "new_code": "lunettesdezac"},
    "CRAR Normandie": {"old_code": "crar_normandie", "new_code": "crarnormandie"},
    "Syvadec": {"old_code": "", "new_code": "syvadec"},
    "ALIAPUR": {"old_code": "", "new_code": "aliapur"},
    "Ville de Paris": {"old_code": "ville_de_paris", "new_code": "villedeparis"},
    "Le REFER": {"old_code": "le_refer", "new_code": "lerefer"},
    "Origine Cycles": {"old_code": "origine_cycles", "new_code": "originecycles"},
    "Réseau National des Ressourceries et Recycleries": {
        "old_code": "reseau_national_des_ressourceries_et_recycleries",
        "new_code": "ressourceries",
    },
    "Recyclivre - Boîtes à lire": {
        "old_code": "recyclivre_-_boites_a_lire",
        "new_code": "recyclivrebal",
    },
    "Association des Ludothèques Françaises": {
        "old_code": "",
        "new_code": "ludotheques",
    },  # cas spécial, pas de code -> correction id unique -> id externe
    "Bibliothèques - Ministère de la culture": {
        "old_code": "",
        "new_code": "bibliotheques",
    },  # cas spécial, pas de code  -> correction id unique -> id externe
    "ADEME - SINOE": {
        "old_code": "",
        "new_code": "sinoe",
    },  # cas spécial, code au milieu de l'identifiant
    "ADEME - Initiatives locales": {
        "old_code": "",
        "new_code": "ademelocales",
    },  # cas spécial, pas de code
    "ADEME - Acteurs digitaux": {
        "old_code": "",
        "new_code": "ademedigitaux",
    },  # cas spécial, pas de code
    "ADEME - Initiatives nationales": {
        "old_code": "",
        "new_code": "ademenationales",
    },  # cas spécial, pas de code
    "CartEco - ESS France": {
        "old_code": "carteco_-_ess_france",
        "new_code": "carteco",
    },  # carteco & carteco_-_ess_france
    "ADEME - Locations": {
        "old_code": "",
        "new_code": "ademelocation",
    },  # cas spécial, pas de code
    # "openstreetmap": {
    #     "old_code": "",
    #     "new_code": "",
    # },  # cas spécial, que 4 points 'DEL', n'est ce pas de la contribution équipe ?
    "ADELPHE": {"old_code": "adelphe", "new_code": "adelphe"},  # 1 seul acteur ?
    "ALCOME": {"old_code": "", "new_code": "alcome"},  # 0 acteur
    "ECOMAISON": {"old_code": "ecomaison", "new_code": "ecomaison"},
    "APER": {"old_code": "", "new_code": "aper"},  # 0 acteur
    "Communauté Longue Vie Aux Objets": {
        "old_code": "communaute_longue_vie_aux_objets",
        "new_code": "communautelvao",
    },
    "Groupe Findis": {"old_code": "", "new_code": "findis"},  # cas special, pas de code
    "CITEO": {"old_code": "", "new_code": "citeo"},
    "Collectif Encore": {"old_code": "", "new_code": "encore"},
    "CYCLAMED": {"old_code": "", "new_code": "cyclamed"},
    "CYCLEVIA": {"old_code": "", "new_code": "cyclevia"},  # 0 acteur
    "DASTRI": {"old_code": "", "new_code": "dastri"},  # 0 acteur
    "Collectivité Ambert Livradois Forez": {
        "old_code": "collectivite_ambert_livradois_forez",
        "new_code": "alv",
    },
    "CMA - Chambre des métiers et de l'artisanat": {
        "old_code": "cma_reparacteur",
        "new_code": "cma",
    },
    "Fédération Envie": {"old_code": "", "new_code": "envie"},
    #    "equipe": {"old_code": "", "new_code": ""},
    "COREPILE": {"old_code": "", "new_code": "corepile"},
    "ECOLOGIC": {"old_code": "", "new_code": "ecologic"},
    "VALDELIA": {"old_code": "", "new_code": "valdelia"},
    "VALOBAT": {"old_code": "", "new_code": "valobat"},
    "ECOMINERO": {"old_code": "", "new_code": "ecominero"},
    "PYREO": {"old_code": "", "new_code": "pyreo"},
    "GIE FRP": {"old_code": "", "new_code": "giefrp"},
    "LEKO": {"old_code": "", "new_code": "leko"},
    "SCRELEC": {"old_code": "", "new_code": "screlec"},
    "TYVAL": {"old_code": "", "new_code": "tyval"},
    "REFASHION": {"old_code": "", "new_code": "refashion"},
    "Recyclivre - Point livres": {
        "old_code": "recyclivre_-_point_livres",
        "new_code": "recyclivrepl",
    },
    "ADEME_SINOE_Decheteries": {
        "old_code": "ademe_sinoe_decheteries",
        "new_code": "ademesinoedecheteries",
    },
    "Longue Vie Aux Objets": {
        "old_code": "",
        "new_code": "lvao",
    },  # il y a à boire et à manger
    "ECOSYSTEM": {"old_code": "", "new_code": "ecosystem"},
    "SOREN": {"old_code": "", "new_code": "soren"},
    "Ordre National Des Pharmaciens": {
        "old_code": "ordredespharmaciens",
        "new_code": "ordredespharmaciens",
    },
    "Leroy Merlin": {"old_code": "", "new_code": "leroymerlin"},
    "la_poste": {"old_code": "", "new_code": "laposte"},
    "cma_reparacteur": {"old_code": "cma_reparacteur", "new_code": "cmareparacteur"},
}


def update_acteur_source_code(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    DisplayedActeur = apps.get_model("qfdmo", "DisplayedActeur")
    for code, map in mapping.items():
        Source.objects.filter(code=code).update(code=map["new_code"])
        for cls in [Acteur, RevisionActeur, DisplayedActeur]:
            if map["old_code"] and map["new_code"] != map["old_code"]:
                # tous ceux dont l'identifiant_unique commence par old_code, on remplace old_code par new_code dans l'identifiant unique
                cls.objects.filter(identifiant_unique__startswith=map["old_code"])
                for acteur in cls.objects.filter(
                    identifiant_unique__startswith=map["old_code"]
                ):
                    acteur.identifiant_unique = acteur.identifiant_unique.replace(
                        map["old_code"], map["new_code"]
                    )
                    acteur.save()


def rollback_acteur_source_code(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    DisplayedActeur = apps.get_model("qfdmo", "DisplayedActeur")
    for code, map in mapping.items():
        Source.objects.filter(code=map["new_code"]).update(code=code)
        for cls in [Acteur, RevisionActeur, DisplayedActeur]:
            if map["old_code"]:
                # tous ceux dont l'identifiant_unique commence par old_code, on remplace old_code par new_code dans l'identifiant unique
                cls.objects.filter(identifiant_unique__startswith=map["new_code"])
                for acteur in cls.objects.filter(
                    identifiant_unique__startswith=map["new_code"]
                ):
                    acteur.identifiant_unique = acteur.identifiant_unique.replace(
                        map["new_code"], map["old_code"]
                    )
                    acteur.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0107_alter_source_licence"),
    ]

    operations = [
        migrations.RunPython(update_acteur_source_code, rollback_acteur_source_code),
    ]
