# Generated by Django 5.1.4 on 2025-01-09 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0109_suggestioncohorte_remove_dagrunchange_dag_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestioncohorte",
            name="pourcentage_erreurs_tolerees",
            field=models.IntegerField(
                default=0,
                help_text="Nombre d'erreurs tolérées en pourcentage",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="suggestioncohorte",
            name="type_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLUSTERING", "regroupement/déduplication des acteurs"),
                    ("SOURCE", "ingestion de source de données"),
                    ("SOURCE_AJOUT", "ingestion de source de données - nouveau acteur"),
                    (
                        "SOURCE_MISESAJOUR",
                        "ingestion de source de données - modification d'acteur existant",
                    ),
                    ("SOURCE_SUPRESSION", "ingestion de source de données"),
                    ("ENRICHISSEMENT", "suggestion d'enrichissement"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="type_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLUSTERING", "regroupement/déduplication des acteurs"),
                    ("SOURCE", "ingestion de source de données"),
                    ("SOURCE_AJOUT", "ingestion de source de données - nouveau acteur"),
                    (
                        "SOURCE_MISESAJOUR",
                        "ingestion de source de données - modification d'acteur existant",
                    ),
                    ("SOURCE_SUPRESSION", "ingestion de source de données"),
                    ("ENRICHISSEMENT", "suggestion d'enrichissement"),
                ],
                max_length=250,
            ),
        ),
    ]
