# Generated by Django 5.1.1 on 2024-12-10 17:14

from django.db import migrations, models

import qfdmo.validators


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0109_refacto_source_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
    ]
