# Generated by Django 5.1.4 on 2025-01-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0110_alter_source_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BANCache",
        ),
    ]
