# Generated by Django 5.1.4 on 2025-01-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0110_alter_source_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BANCache",
        ),
        migrations.RemoveField(
            model_name="dagrunchange",
            name="dag_run",
        ),
        migrations.DeleteModel(
            name="DagRun",
        ),
        migrations.DeleteModel(
            name="DagRunChange",
        ),
    ]
