# Generated by Django 5.1.4 on 2025-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0110_suggestioncohorte_pourcentage_erreurs_tolerees_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BANCache",
        ),
        migrations.RemoveField(
            model_name="suggestionunitaire",
            name="suggestion_cohorte",
        ),
        migrations.DeleteModel(
            name="SuggestionCohorte",
        ),
        migrations.DeleteModel(
            name="SuggestionUnitaire",
        ),
    ]
