# Generated by Django 5.1.1 on 2024-10-12 07:55

import logging

from django.db import migrations

MAPPING_ACTEUR_ID_TABLE = {
    "qfdmo_acteur": "identifiant_unique",
    "qfdmo_revisionacteur": "identifiant_unique",
    "qfdmo_acteur_acteur_services": "acteur_id",
    "qfdmo_acteur_labels": "acteur_id",
    "qfdmo_propositionservice": "acteur_id",
    "qfdmo_revisionacteur_acteur_services": "revisionacteur_id",
    "qfdmo_revisionacteur_labels": "revisionacteur_id",
    "qfdmo_revisionpropositionservice": "acteur_id",
}


def update_acteur_source_code(apps, schema_editor):
    Source = apps.get_model("qfdmo", "Source")
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")

    RevisionActeur.objects.filter(
        source__code="Communauté Longue Vie Aux Objets"
    ).update(source=Source.objects.get(code="communautelvao"))
    Acteur.objects.filter(source__code="Communauté Longue Vie Aux Objets").update(
        source=Source.objects.get(code="communautelvao")
    )

    schema_editor.execute("SET CONSTRAINTS ALL DEFERRED;")

    old_code = "communauté longue vie aux objets"
    new_code = "communautelvao"
    for table_name, acteur_id_field in MAPPING_ACTEUR_ID_TABLE.items():
        sql = f"""
            UPDATE {table_name}
            SET {acteur_id_field} = REPLACE({acteur_id_field}, %s, %s)
            WHERE {acteur_id_field} LIKE %s;
            """
        logging.warning(
            f"Executing SQL: {sql} with params: {old_code}, {new_code}, {old_code}%"
        )
        schema_editor.execute(sql, [old_code, new_code, f"{old_code}%"])
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE;")
    Source.objects.filter(code="Communauté Longue Vie Aux Objets").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0111_delete_bancache"),
    ]

    operations = [
        migrations.RunPython(update_acteur_source_code, migrations.RunPython.noop),
    ]
