# Generated by Django 5.1.4 on 2025-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0114_action_models_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="acteurservice",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[0-9a-z_]+$")),
                name="acteur_service_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="acteurtype",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[0-9a-z_]+$")),
                name="acteur_type_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[0-9a-z_]+$")),
                name="source_code_format",
            ),
        ),
    ]
