# Generated by Django 5.1.4 on 2025-01-24 09:46

from django.db import migrations


def update_empty_url(apps, schema_editor):
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    RevisionActeur.objects.filter(url="__nourl__").update(url="__empty__")


def rollback_empty_url(apps, schema_editor):
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    RevisionActeur.objects.filter(url="__empty__").update(url="__nourl__")


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0116_change_screlec_to_batribox"),
    ]

    operations = [
        migrations.RunPython(update_empty_url, rollback_empty_url),
    ]
