# Generated by Django 5.1.4 on 2025-02-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0117_update_empty_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="displayedacteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="displayedacteurtemp",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="revisionacteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
    ]
