# Generated by Django 5.1.4 on 2025-02-03 13:47

import django.contrib.gis.db.models.fields
import django.db.models.functions.datetime
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0117_update_empty_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToutActeur",
            fields=[
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identifiant_unique",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adresse_complement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nom_commercial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_officiel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("siren", models.CharField(blank=True, max_length=9, null=True)),
                ("siret", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "identifiant_externe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "actif"),
                            ("INACTIF", "inactif"),
                            ("SUPPRIME", "supprimé"),
                        ],
                        db_default="ACTIF",
                        default="ACTIF",
                        max_length=255,
                    ),
                ),
                (
                    "naf_principal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("commentaires", models.TextField(blank=True, null=True)),
                (
                    "horaires_osm",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[qfdmo.models.acteur.validate_opening_hours],
                    ),
                ),
                ("horaires_description", models.TextField(blank=True, null=True)),
                (
                    "public_accueilli",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Particuliers et professionnels",
                                "Particuliers et professionnels",
                            ),
                            ("Professionnels", "Professionnels"),
                            ("Particuliers", "Particuliers"),
                            ("Aucun", "Aucun"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reprise",
                    models.CharField(
                        blank=True,
                        choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "exclusivite_de_reprisereparation",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Exclusivité de reprise/réparation",
                    ),
                ),
                ("uniquement_sur_rdv", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ACTEUR de l'EC - AFFICHÉ",
                "verbose_name_plural": "ACTEURS de l'EC - AFFICHÉ",
                "managed": False,
            },
        ),
    ]
