# Generated by Django 5.1.4 on 2025-02-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0117_update_empty_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dagrunchange",
            name="dag_run",
        ),
        migrations.DeleteModel(
            name="DagRun",
        ),
        migrations.DeleteModel(
            name="DagRunChange",
        ),
    ]
