# Generated by Django 5.1.5 on 2025-02-11 08:42

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0119_toutacteur_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionacteur",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Acteur «chapeau» utilisé pour dédupliquer cet acteur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicats",
                to="qfdmo.revisionacteur",
                validators=[qfdmo.models.acteur.clean_parent],
                verbose_name="Dédupliqué par",
            ),
        ),
    ]
