# Generated by Django 5.1.5 on 2025-02-13 16:54

from django.db import migrations, models

import qfdmo.validators


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0120_alter_revisionacteur_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["order"], "verbose_name": "Action - Action"},
        ),
        migrations.AlterModelOptions(
            name="actiondirection",
            options={"verbose_name": "Action - Direction"},
        ),
        migrations.AlterModelOptions(
            name="categorieobjet",
            options={"verbose_name": "Objet - Catégorie"},
        ),
        migrations.AlterModelOptions(
            name="groupeaction",
            options={
                "verbose_name": "Action - Groupe d'action",
                "verbose_name_plural": "Action - Groupes d'action",
            },
        ),
        migrations.AlterModelOptions(
            name="objet",
            options={"verbose_name": "Objet - Objet"},
        ),
        migrations.AlterModelOptions(
            name="souscategorieobjet",
            options={"ordering": ["libelle"], "verbose_name": "Objet - Sous catégorie"},
        ),
        migrations.AlterField(
            model_name="action",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="actiondirection",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="groupeaction",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="labelqualite",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
    ]
