# Generated by Django 5.1.5 on 2025-02-18 16:16

from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0121_alter_action_models_and_code_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionacteur",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                validators=[qfdmo.models.acteur.email_or_empty_validator],
            ),
        ),
    ]
