# Generated by Django 5.1.5 on 2025-02-14 13:22

import shortuuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0126_vueacteur_views_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="code_postal",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="nom",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="siren",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="siret",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="ville",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="code_postal",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="nom",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siren",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siret",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="code_postal",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="nom",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siren",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siret",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="ville",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="code_postal",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siren",
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siret",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=shortuuid.uuid,
                editable=False,
                max_length=255,
            ),
        ),
    ]
