# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0127_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="adresse",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="adresse_complement",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="horaires_description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="horaires_osm",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="nom_commercial",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="nom_officiel",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="adresse",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="adresse_complement",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="horaires_description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="horaires_osm",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="nom_commercial",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="nom_officiel",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="adresse",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="adresse_complement",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="horaires_description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="horaires_osm",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="nom_commercial",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="nom_officiel",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="adresse",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="adresse_complement",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="horaires_description",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="horaires_osm",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                validators=[qfdmo.models.acteur.validate_opening_hours],
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="nom_commercial",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="nom_officiel",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="email",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=254,
                validators=[core.validators.EmptyEmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="nom",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
    ]
