# Generated by Django 5.1.7 on 2025-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0127_add_indexes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="displayedacteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="displayedacteurtemp",
            old_name="identifiant_unique",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="revisionacteur",
            old_name="identifiant_unique",
            new_name="id",
        ),
    ]
