# Generated by Django 5.1.7 on 2025-03-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0127_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeActionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="config/groupeaction/icones/",
                        verbose_name="Supplanter l'icône utilisée pour l'action",
                    ),
                ),
                (
                    "acteur_type",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Si la configuration de l'action est spécifique à un ou plusieurs types d'acteurs, ceux-ci peuvent être renseignés ici",
                        to="qfdmo.acteurtype",
                        verbose_name="Types d'acteur concernés par la configuration",
                    ),
                ),
                (
                    "groupe_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.groupeaction",
                        verbose_name="Action parente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seules les sources sélectionnées s'afficheront sur la carte",
                        to="qfdmo.source",
                        verbose_name="Source(s)",
                    ),
                ),
                (
                    "sous_categorie_objet",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seules les sous-catégories sélectionnées s'afficheront sur la carte",
                        to="qfdmo.souscategorieobjet",
                        verbose_name="Sous-catégories d'objets filtrés",
                    ),
                ),
                (
                    "groupe_action_config",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seules les groupes d'actions sélectionnés s'afficheront sur la carte",
                        to="qfdmo.groupeactionconfig",
                    ),
                ),
            ],
        ),
    ]
