# Generated by Django 5.1.7 on 2025-03-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0128_groupeactionconfig_carteconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carteconfig",
            name="groupe_action_config",
        ),
        migrations.AddField(
            model_name="groupeactionconfig",
            name="carte_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.carteconfig",
            ),
        ),
    ]
