# Generated by Django 5.1.7 on 2025-03-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0129_remove_carteconfig_groupe_action_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="nom",
            field=models.CharField(default="cyclevia", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="groupe_action",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.groupeaction",
                verbose_name="Groupe d'actions",
            ),
        ),
    ]
