# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0129_alter_acteur_not_nullable_char_fields_adresse_complement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="code_postal",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=10
            ),
        ),
    ]
