# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0130_alter_acteur_not_nullable_char_fields_code_postal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="commentaires",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
    ]
