# Generated by Django 5.1.7 on 2025-03-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0130_carteconfig_nom_carteconfig_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carteconfig",
            options={
                "verbose_name": "Carte sur mesure",
                "verbose_name_plural": "Cartes sur mesure",
            },
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="slug",
            field=models.SlugField(
                help_text="Le slug est utilisé pour générer l'url de carte, par exemple: https://quefairedemesobjets.fr/carte/<strong>cyclevia</strong>",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="source",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les sources sélectionnées s'afficheront sur la carte \nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.source",
                verbose_name="Source(s)",
            ),
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="sous_categorie_objet",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les sous-catégories sélectionnées s'afficheront sur la carte \nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.souscategorieobjet",
                verbose_name="Sous-catégories d'objets filtrés",
            ),
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="carte_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupe_action",
                to="qfdmo.carteconfig",
            ),
        ),
    ]
