# Generated by Django 5.1.7 on 2025-03-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0131_alter_carteconfig_options_alter_carteconfig_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="source",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les sources sélectionnées s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.source",
                verbose_name="Source(s)",
            ),
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="sous_categorie_objet",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les sources sélectionnées s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.souscategorieobjet",
                verbose_name="Sous-catégories d'objets filtrés",
            ),
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="carte_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupe_action_config",
                to="qfdmo.carteconfig",
            ),
        ),
    ]
