# Generated by Django 5.1.7 on 2025-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0132_alter_carteconfig_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="groupe_action",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les actions sélectionnées s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.groupeaction",
                verbose_name="Groupe d'actions",
            ),
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="sous_categorie_objet",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les objets sélectionnés s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.souscategorieobjet",
                verbose_name="Sous-catégories d'objets filtrés",
            ),
        ),
    ]
