# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0132_alter_acteur_not_nullable_char_fields_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="email",
            field=models.EmailField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="email",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=254,
                validators=[core.validators.EmptyEmailValidator()],
            ),
        ),
    ]
