# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0134_alter_acteur_not_nullable_char_fields_horaires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_externe",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="naf_principal",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
    ]
