# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0136_alter_acteur_not_nullable_char_fields_noms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="public_accueilli",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Particuliers et professionnels",
                        "Particuliers et professionnels",
                    ),
                    ("Professionnels", "Professionnels"),
                    ("Particuliers", "Particuliers"),
                    ("Aucun", "Aucun"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="reprise",
            field=models.CharField(
                blank=True,
                choices=[("1 pour 0", "1 pour 0"), ("1 pour 1", "1 pour 1"), ("", "")],
                default="",
                max_length=255,
            ),
        ),
    ]
