# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0137_alter_acteur_not_nullable_char_fields_public_reprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siren",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="siret",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=14
            ),
        ),
    ]
