# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models

import core.validators
import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0138_alter_acteur_not_nullable_char_fields_siren_siret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteurtemp",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="telephone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="url",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="ville",
            field=models.CharField(
                blank=True, db_default="", db_index=True, default="", max_length=255
            ),
        ),
    ]
