# Generated by Django 5.1.6 on 2025-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0139_alter_acteur_not_nullable_char_fields_tel_url_ville"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="siret_is_closed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Indique si le SIRET est fermé ou non dans l'Annuaire Entreprises",
                verbose_name="SIRET fermé",
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="siret_is_closed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Indique si le SIRET est fermé ou non dans l'Annuaire Entreprises",
                verbose_name="SIRET fermé",
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="siret_is_closed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Indique si le SIRET est fermé ou non dans l'Annuaire Entreprises",
                verbose_name="SIRET fermé",
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="parent_reason",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Raison du rattachement au parent",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="siret_is_closed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Indique si le SIRET est fermé ou non dans l'Annuaire Entreprises",
                verbose_name="SIRET fermé",
            ),
        ),
    ]
