# Generated by Django 5.1.7 on 2025-03-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0139_alter_acteur_not_nullable_char_fields_tel_url_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedpropositionservice",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
