# Generated by Django 5.1.7 on 2025-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0139_alter_acteur_not_nullable_char_fields_tel_url_ville"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeaction",
            name="fill",
            field=models.BooleanField(
                default=False,
                help_text="Ce champ permet de configurer un groupe d'action pour que son icône dispose d'un fond plein plutôt qu'un fond ajouré.\nC'est ce qui est utilisé par exemple sur l'action réparer",
                verbose_name="Remplissage du fond",
            ),
        ),
    ]
