# Generated by Django 5.1.7 on 2025-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0133_carteconfig_groupe_action_and_more"),
        ("qfdmo", "0139_alter_acteur_not_nullable_char_fields_tel_url_ville"),
    ]

    operations = []
