# Generated by Django 5.1.7 on 2025-04-01 13:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0140_carteconfig_groupeactionconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeactionconfig",
            name="couleur",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Si aucune couleur n'est renseignée ici, la couleur par défaut de l'action sélectionnée sera utilisée pour la bordure du pictogramme. La couleur de remplissage dupictogramme utilisera celle définie dans le .svg fourni.",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Couleur de fond utilisée pour le pictogramme",
            ),
        ),
    ]
