# Generated by Django 5.1.7 on 2025-04-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0140_merge_20250401_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="groupe_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.groupeaction",
                verbose_name="Groupe d'actions",
            ),
        ),
    ]
