# Generated by Django 5.1.7 on 2025-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0141_groupeactionconfig_couleur"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupeactionconfig",
            unique_together={("carte_config", "groupe_action", "acteur_type")},
        ),
    ]
