# Generated by Django 5.1.7 on 2025-04-01 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0141_alter_groupeactionconfig_groupe_action"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupeactionconfig",
            unique_together={("carte_config", "groupe_action", "acteur_type")},
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="carte_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupe_action_config",
                to="qfdmo.carteconfig",
            ),
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="groupe_action",
            field=models.ForeignKey(
                blank=True,
                help_text="La configuration peut être limitée à un type d'actaction spécifique. Auquel cas il doit être indiqué ici.\nSi aucune action n'est renseignée, cette configuration s'appliquera à tout type d'acteur.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.groupeaction",
                verbose_name="Groupe d'action",
            ),
        ),
        migrations.AlterField(
            model_name="groupeactionconfig",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="L'icône doit être au format SVG. ",
                null=True,
                upload_to="config/groupeaction/icones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="Supplanter l'icône utilisée pour l'action",
            ),
        ),
        migrations.RemoveField(
            model_name="groupeactionconfig",
            name="acteur_type",
        ),
        migrations.AddField(
            model_name="groupeactionconfig",
            name="acteur_type",
            field=models.ForeignKey(
                blank=True,
                help_text="La configuration peut être limitée à un type d'acteur spécifique. Auquel cas il doit être indiqué ici.\nSi aucun type d'acteur n'est renseigné, cette configuration s'appliquera à tout type d'acteur.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.acteurtype",
                verbose_name="Types d'acteur concernés par la configuration",
            ),
        ),
    ]
