# Generated by Django 5.1.7 on 2025-04-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0142_alter_groupeactionconfig_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupeactionconfig",
            name="couleur",
        ),
    ]
