# Generated by Django 5.1.6 on 2025-04-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0140_drop_views"),
        ("qfdmo", "0144_alter_groupeactionconfig_groupe_action"),
    ]

    operations = []
