# Generated by Django 5.1.6 on 2025-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0147_groupeaction_fill_alter_action_couleur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="hide_legend",
            field=models.BooleanField(default=False),
        ),
    ]
