# Generated by Django 5.1.6 on 2025-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0148_carteconfig_hide_legend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="hide_legend",
            field=models.BooleanField(
                default=False,
                help_text="Cocher cette case cache la légende affichée en bas à gauche de la carte en desktop et au dessus de celle-ci en mobile",
                verbose_name="Cacher la légende",
            ),
        ),
    ]
