# Generated by Django 5.1.8 on 2025-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0151_acteur_acteur_unique_by_source_and_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="no_branding",
            field=models.BooleanField(
                default=False,
                help_text="Supprime le logo dans l'entête de la carte ainsi que le bouton Infos. Ce mode est utilisé essentiellement pour la carte affichée dans l'assistant",
                verbose_name="Supprimer le branding",
            ),
        ),
    ]
