# Generated by Django 5.1.8 on 2025-05-22 07:49

import logging
import subprocess

from django.conf import settings
from django.db import migrations


def copy_schema(apps, schema_editor):

    logging.warning(
        f"pg_dump -d {settings.DATABASE_URL} --schema=public --schema-only | psql -d {settings.DB_READONLY}"
    )
    subprocess.run(
        [
            f"pg_dump -d {settings.DATABASE_URL} --schema=public --schema-only | psql -d {settings.DB_READONLY}",
        ],
        check=True,
        shell=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0152_schema_warehouse"),
    ]

    database = "default"

    atomic = False

    operations = [
        migrations.RunPython(copy_schema, migrations.RunPython.noop),
        migrations.RunSQL(
            """
            CREATE PUBLICATION copy_to_webapp FOR TABLES IN SCHEMA public;
            """,
            """
            DROP PUBLICATION IF EXISTS copy_to_webapp;
            """,
        ),
    ]
