# Generated by Django 5.1.8 on 2025-05-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0152_carteconfig_no_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="preview_content",
            field=models.TextField(
                blank=True,
                help_text="Ce texte s'affiche avant que l'utilisateur n'ait fait une recherche dans la carte",
                verbose_name="Contenu de l'écran de prévisualisation",
            ),
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="preview_title",
            field=models.CharField(
                blank=True,
                help_text="Ce titre s'affiche avant que l'utilisateur n'ait fait une recherche dans la carte",
                verbose_name="Titre de l'écran de prévisualisation",
            ),
        ),
    ]
