# Generated by Django 5.1.8 on 2025-06-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0152_schema_warehouse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vueacteur",
            options={
                "managed": False,
                "verbose_name": "ACTEUR de l'EC - Vue sur l'acteur",
                "verbose_name_plural": "ACTEURS de l'EC - Vues sur tous les acteurs",
            },
        ),
    ]
