# Generated by Django 5.1.8 on 2025-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0152_schema_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="no_branding",
            field=models.BooleanField(
                default=False,
                help_text="Supprime le logo dans l'entête de la carte ainsi que le bouton Infos. Ce mode est utilisé essentiellement pour la carte affichée dans l'assistant",
                verbose_name="Supprimer le branding",
            ),
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="preview_content",
            field=models.TextField(
                blank=True,
                help_text="Ce texte s'affiche avant que l'utilisateur n'ait fait une recherche dans la carte",
                verbose_name="Contenu de l'écran de prévisualisation",
            ),
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="preview_title",
            field=models.CharField(
                blank=True,
                help_text="Ce titre s'affiche avant que l'utilisateur n'ait fait une recherche dans la carte",
                verbose_name="Titre de l'écran de prévisualisation",
            ),
        ),
    ]
