# Generated by Django 5.1.8 on 2025-05-22 07:56

from django.db import connections, migrations


def create_subscription(apps, schema_editor):
    # Utiliser la connexion readonly explicitement
    with connections["readonly"].cursor() as cursor:
        cursor.execute(
            """
            CREATE SUBSCRIPTION copy_to_webapp_subscription
            CONNECTION
            'host=warehouse-db port=5432 dbname=qfdmo user=qfdmo password=qfdmo'
            PUBLICATION copy_to_webapp;
        """
        )


def drop_subscription(apps, schema_editor):
    # Utiliser la connexion readonly explicitement
    with connections["readonly"].cursor() as cursor:
        cursor.execute(
            """
            DROP SUBSCRIPTION IF EXISTS copy_to_webapp_subscription;
        """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0153_create_publication"),
    ]

    database = "readonly"

    atomic = False

    operations = [
        migrations.RunPython(
            create_subscription,
            drop_subscription,
        ),
    ]
