# Generated by Django 5.1.8 on 2025-05-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0152_schema_warehouse"),
        ("qfdmo", "0153_carteconfig_preview_content_and_more"),
    ]

    operations = []
