# Generated by Django 5.1.8 on 2025-06-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0153_alter_vueacteur_options"),
        ("qfdmo", "0153_carteconfig_no_branding_carteconfig_preview_content_and_more"),
    ]

    operations = []
