# Generated by Django 5.1.8 on 2025-06-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0153_alter_vueacteur_options"),
        ("qfdmo", "0154_merge_20250527_1025"),
    ]

    operations = []
