# Generated by Django 5.1.8 on 2025-06-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0155_alter_carteconfig_slug"),
        ("qfdmo", "0155_remove_explorer_tables"),
    ]

    operations = []
