# Generated by Django 5.1.8 on 2025-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0153_carteconfig_no_branding_carteconfig_preview_content_and_more"),
        ("qfdmo", "0155_merge_20250602_1527"),
    ]

    operations = []
