# Generated by Django 5.1.8 on 2025-06-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0154_merge_20250604_1615"),
        ("qfdmo", "0156_merge_20250604_1610"),
    ]

    operations = []
