# Generated by Django 5.1.6 on 2025-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0156_merge_20250605_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedpropositionservice",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
