# Generated by Django 5.1.8 on 2025-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0157_alter_displayedpropositionservice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="slug",
            field=models.SlugField(
                help_text="Le slug est utilisé pour générer l'url de carte, par exemple: https://quefairedemesobjets.fr/carte/<strong>cyclevia</strong><br>Le slug est utilisé pour le script avec l'attribut <code>data-slug</code>, par exemple : <br/><code>&lt;script src='https://quefairedemesobjets.ademe.fr/static/carte.js' data-slug='cyclevia'&gt;&lt;/script&gt;</code>",
                unique=True,
            ),
        ),
    ]
