# Generated by Django 5.2.3 on 2025-06-27 13:17

from django.db import migrations


def create_action_rapporter(apps, schema_editor):
    Action = apps.get_model("qfdmo", "Action")
    ActionDirection = apps.get_model("qfdmo", "ActionDirection")
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")
    # Prevent this update from failing if the groupe action already exists with the
    # appropriate code in the database
    GroupeAction.objects.filter("donner_echanger").update(
        code="donner_echanger_rapporter"
    )
    action = Action.objects.create(
        code="rapporter",
        libelle="rapporter",
        libelle_groupe="Je rapporte",
        order=10,
        description="Rapporter ses contenants réutilisables",
        afficher=False,
        couleur="#cab300",
        icon="fr-icon-arrow-up-down-line",
        groupe_action__code="donner_echanger_rapporter",
    )
    action_direction_jai = ActionDirection.objects.get(code="jai")
    action.directions.add(action_direction_jai)
    action_trier = Action.objects.get(code="trier")
    action_trier.order = 11
    action_trier.save()


def remove_action_rapporter(apps, schema_editor):
    Action = apps.get_model("qfdmo", "Action")
    Action.objects.filter(code="rapporter").delete()
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")

    GroupeAction.objects.filter(code="donner_echanger_rapporter").update(
        code="donner_echanger"
    )
    action_trier = Action.objects.get(code="trier")
    action_trier.order = 10
    action_trier.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0159_connect_public_to_warehouse"),
    ]

    operations = [
        migrations.RunPython(create_action_rapporter, remove_action_rapporter)
    ]
