# Generated by Django 5.1.8 on 2025-06-19 10:26

from django.db import migrations


def title_addresses(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    RevisionActeur = apps.get_model("qfdmo", "RevisionActeur")
    count = 0
    for cls in [Acteur, RevisionActeur]:
        for acteur in cls.objects.all():
            count += 1
            if count % 1000 == 0:
                print(f"Processed {count} acteur/revisionacteur")
            for field in ["adresse", "adresse_complement", "ville"]:
                if getattr(acteur, field):
                    setattr(acteur, field, getattr(acteur, field).title())
            acteur.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0159_connect_public_to_warehouse"),
    ]

    operations = [
        migrations.RunPython(
            title_addresses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
