# Generated by Django 5.2.4 on 2025-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0161_carteconfig_acteur_type_carteconfig_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="consignes_dacces",
            field=models.TextField(
                blank=True, db_default="", default="", verbose_name="Consignes d'accès"
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="consignes_dacces",
            field=models.TextField(
                blank=True, db_default="", default="", verbose_name="Consignes d'accès"
            ),
        ),
        migrations.AddField(
            model_name="displayedacteurtemp",
            name="consignes_dacces",
            field=models.TextField(
                blank=True, db_default="", default="", verbose_name="Consignes d'accès"
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="consignes_dacces",
            field=models.TextField(
                blank=True, db_default="", default="", verbose_name="Consignes d'accès"
            ),
        ),
    ]
