# Generated by Django 5.2.4 on 2025-08-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0162_acteur_consignes_dacces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="acteur_services",
        ),
        migrations.RemoveField(
            model_name="acteurlabelqualite",
            name="acteur",
        ),
        migrations.RemoveField(
            model_name="acteurlabelqualite",
            name="label",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="acteur_type",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="action_principale",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="source",
        ),
        migrations.RemoveField(
            model_name="displayedacteurtemp",
            name="sources",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="acteur",
        ),
        # migrations.RemoveField(
        #     model_name="displayedacteurtempsource",
        #     name="acteur",
        # ),
        migrations.AlterUniqueTogether(
            name="displayedacteurtempsource",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="displayedacteurtempsource",
            name="source",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="action",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetemp",
            name="sous_categories",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetempsouscategorie",
            name="proposition_service",
        ),
        migrations.RemoveField(
            model_name="displayedpropositionservicetempsouscategorie",
            name="sous_categorie_objet",
        ),
        migrations.DeleteModel(
            name="ActeurActeurService",
        ),
        migrations.DeleteModel(
            name="ActeurLabelQualite",
        ),
        migrations.DeleteModel(
            name="DisplayedActeurTemp",
        ),
        migrations.DeleteModel(
            name="DisplayedActeurTempSource",
        ),
        migrations.DeleteModel(
            name="DisplayedPropositionServiceTemp",
        ),
        migrations.DeleteModel(
            name="DisplayedPropositionServiceTempSousCategorie",
        ),
    ]
