# Generated by Django 5.2.4 on 2025-08-11 07:03

from django.db import migrations, models

import qfdmo.validators


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0164_rebuild_remote_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieobjet",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="objet",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="souscategorieobjet",
            name="code",
            field=models.CharField(
                help_text="Ce champ est utilisé lors de l'import de données, il ne doit pas être mis à jour sous peine de casser l'import de données",
                max_length=255,
                unique=True,
                validators=[qfdmo.validators.CodeValidator()],
            ),
        ),
    ]
