# Generated by Django 5.2.4 on 2025-08-11 06:18

import json
import os

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    # This data migration was meant to run once on production.
    # This need to be disabled now that it ran to prevent issues during testing.
    return
    # # Skip during tests
    # if os.environ.get("PYTEST_CURRENT_TEST"):
    #     return

    # Objet = apps.get_model("qfdmo", "Objet")
    # Objet.objects.filter(code="equipement de ski de randonnée (pelle, sonde)").delete()


def update_categorieobjets_code(apps, schema_editor):
    # This data migration was meant to run once on production.
    # This need to be disabled now that it ran to prevent issues during testing.
    return

    # Skip during tests
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return

    CategorieObjet = apps.get_model("qfdmo", "CategorieObjet")
    with open("qfdmo/migrations/fixtures/categorieobjets.json", "r") as f:
        categories = json.load(f)
        for old_code, new_code in categories.items():
            cat = CategorieObjet.objects.get(code=old_code)
            cat.code = new_code
            cat.save()


def update_souscategorieobjets_code(apps, schema_editor):
    # This data migration was meant to run once on production.
    # This need to be disabled now that it ran to prevent issues during testing.
    return

    # Skip during tests
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return

    SousCategorieObjet = apps.get_model("qfdmo", "SousCategorieObjet")
    with open("qfdmo/migrations/fixtures/souscategorieobjets.json", "r") as f:
        sous_categories = json.load(f)
        for old_code, new_code in sous_categories.items():
            sous_cat = SousCategorieObjet.objects.get(code=old_code)
            sous_cat.code = new_code
            sous_cat.save()


def update_objets_code(apps, schema_editor):
    # This data migration was meant to run once on production.
    # This need to be disabled now that it ran to prevent issues during testing.
    return

    # Skip during tests
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return

    Objet = apps.get_model("qfdmo", "Objet")
    with open("qfdmo/migrations/fixtures/objets.json", "r") as f:
        objets = json.load(f)
        for old_code, new_code in objets.items():
            obj = Objet.objects.get(code=old_code)
            obj.code = new_code
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0165_code_for_objets_and_categories"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.RunPython(update_categorieobjets_code),
        migrations.RunPython(update_souscategorieobjets_code),
        migrations.RunPython(update_objets_code),
    ]
