# Generated by Django 5.2.4 on 2025-08-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0167_serviceadomicile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acteur",
            options={
                "permissions": [
                    ("forceadd_acteur", "Can add an acteur (for debug purposes)"),
                    ("forceupdate_acteur", "Can update an acteur (for debug purposes)"),
                    ("forcedelete_acteur", "Can delete an acteur (for debug purposes)"),
                ],
                "verbose_name": "ACTEUR de l'EC - IMPORTÉ",
                "verbose_name_plural": "ACTEURS de l'EC - IMPORTÉ",
            },
        ),
    ]
