# Generated by Django 5.2.4 on 2025-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0167_rename_hide_legend_carteconfig_cacher_legende_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="mode_affichage",
            field=models.CharField(
                choices=[("carte", "Carte"), ("liste", "Liste")],
                default="carte",
                help_text="Ce choix permet de définir le mode d'affichage par défaut de la carte. Le mode liste affiche une liste d'acteurs tandis qu'une carte affiche un fond de carte.",
                verbose_name="Mode d'affichage par défaut",
            ),
        ),
    ]
