# Generated by Django 5.2.5 on 2025-08-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0167_serviceadomicile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="perimetreadomicile",
            name="acteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perimetre_adomiciles",
                to="qfdmo.acteur",
            ),
        ),
        migrations.AlterField(
            model_name="perimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revisionperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="vueperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
                max_length=255,
            ),
        ),
    ]
