# Generated by Django 5.2.5 on 2025-08-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0168_alter_displayedperimetreadomicile_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedperimetreadomicile",
            name="acteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perimetre_adomiciles",
                to="qfdmo.displayedacteur",
            ),
        ),
        migrations.AlterField(
            model_name="revisionperimetreadomicile",
            name="acteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perimetre_adomiciles",
                to="qfdmo.revisionacteur",
            ),
        ),
        migrations.AlterField(
            model_name="vueperimetreadomicile",
            name="acteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perimetre_adomiciles",
                to="qfdmo.vueacteur",
            ),
        ),
    ]
