# Generated by Django 5.2.5 on 2025-08-25 09:28

from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0169_alter_displayedperimetreadomicile_acteur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayedperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="displayedperimetreadomicile",
            name="value",
            field=models.CharField(
                validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="perimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="perimetreadomicile",
            name="value",
            field=models.CharField(
                validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="revisionperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="revisionperimetreadomicile",
            name="value",
            field=models.CharField(
                validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="vueperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="vueperimetreadomicile",
            name="value",
            field=models.CharField(
                validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
    ]
