# Generated by Django 5.2.5 on 2025-08-25 12:48

from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0169_rename_hide_legend_carteconfig_cacher_legende_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displayedperimetreadomicile",
            name="value",
        ),
        migrations.RemoveField(
            model_name="perimetreadomicile",
            name="value",
        ),
        migrations.RemoveField(
            model_name="revisionperimetreadomicile",
            name="value",
        ),
        migrations.RemoveField(
            model_name="vueperimetreadomicile",
            name="value",
        ),
        migrations.AddField(
            model_name="displayedperimetreadomicile",
            name="valeur",
            field=models.CharField(
                blank=True, validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AddField(
            model_name="perimetreadomicile",
            name="valeur",
            field=models.CharField(
                blank=True, validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AddField(
            model_name="revisionperimetreadomicile",
            name="valeur",
            field=models.CharField(
                blank=True, validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AddField(
            model_name="vueperimetreadomicile",
            name="valeur",
            field=models.CharField(
                blank=True, validators=[qfdmo.models.acteur.DepartementOrNumValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="displayedperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                    ("DROM_TOM", "DROM TOM"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="perimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                    ("DROM_TOM", "DROM TOM"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="revisionperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                    ("DROM_TOM", "DROM TOM"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
        migrations.AlterField(
            model_name="vueperimetreadomicile",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPARTEMENTAL", "Départemental"),
                    ("KILOMETRIQUE", "Kilométrique"),
                    ("FRANCE_METROPOLITAINE", "France métropolitaine (Corse incluse)"),
                    ("DROM_TOM", "DROM TOM"),
                ],
                default="KILOMETRIQUE",
            ),
        ),
    ]
