# Generated by Django 5.2.5 on 2025-09-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0170_update_perimetre_adomicile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carteconfig",
            options={
                "ordering": ("nom",),
                "verbose_name": "Carte sur mesure",
                "verbose_name_plural": "Cartes sur mesure",
            },
        ),
    ]
