# Generated by Django 5.2.5 on 2025-08-26 07:17

from django.db import migrations, models
from slugify import slugify


def populate_objet_slug(apps, schema_editor):
    Objet = apps.get_model("qfdmo", "Objet")
    for objet in Objet.objects.all():
        objet.slug = slugify(objet.libelle)
        objet.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0170_update_perimetre_adomicile"),
    ]

    operations = [
        migrations.AddField(
            model_name="objet",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_objet_slug,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
