# Generated by Django 5.2.5 on 2025-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0171_objet_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objet",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
