# Generated by Django 5.2.5 on 2025-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0171_alter_carteconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vueacteur",
            name="enfants_liste",
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="enfants_nombre",
            field=models.IntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_dans_carte",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_dans_opendata",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_parent",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="latitude",
            field=models.FloatField(default=0.0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="longitude",
            field=models.FloatField(default=0.0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="revision_existe",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
