# Generated by Django 5.2.5 on 2025-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0172_vueacteur_enfants_liste_vueacteur_enfants_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                ],
                default="SUR_PLACE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                ],
                default="SUR_PLACE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                ],
                default="SUR_PLACE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                ],
                default="SUR_PLACE",
                max_length=255,
                null=True,
            ),
        ),
    ]
