# Generated by Django 5.2.5 on 2025-09-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0174_souscategorieobjet_reemploi_possible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="souscategorieobjet",
            name="afficher",
        ),
        migrations.RemoveField(
            model_name="souscategorieobjet",
            name="afficher_carte",
        ),
    ]
