# Generated by Django 5.2.5 on 2025-09-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0174_souscategorieobjet_reemploi_possible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objet",
            options={
                "verbose_name": "Objet - Objet - OBSOLETE",
                "verbose_name_plural": "Objet - Objets - OBSOLETE",
            },
        ),
    ]
