# Generated by Django 5.2.5 on 2025-09-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0175_alter_objet_options"),
        ("qfdmo", "0175_carteconfig_direction"),
    ]

    operations = []
