# Generated by Django 5.2.7 on 2025-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0176_merge_20250924_1802"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carteconfig",
            old_name="label",
            new_name="label_qualite",
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre",
            field=models.BooleanField(
                default=False,
                help_text="Affiche le label dans la modale de filtres affichée sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre_label",
            field=models.CharField(
                blank=True,
                help_text="Configure le label affiché dans le champ de formulaire dans le panel de filtres sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre_texte_d_aide",
            field=models.CharField(
                blank=True,
                help_text="Configure le texte d'aide affiché dans le champ de formulaire dans le panel de filtres sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="labels"),
        ),
        migrations.AlterField(
            model_name="labelqualite",
            name="afficher",
            field=models.BooleanField(
                default=True,
                help_text="Affiche le label côté frontend, notamment dans les fiches acteur",
            ),
        ),
    ]
