# Generated by Django 5.2.7 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0177_carteconfig_solution_temporaire_a_supprimer_des_que_possible_parametres_url",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="displayedacteur",
            name="code_commune_insee",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="code_epci",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="nom_epci",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
