# Generated by Django 5.2.7 on 2025-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0177_rename_label_carteconfig_label_qualite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="nombre_d_acteurs_affiches",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="carteconfig",
            name="label_qualite",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ce champ agit comme un filtre des résultats affichés.<br/> Si les labels sélectionnés correspondent aux labels affichés dans la modale de filtres de la carte, alors ceux-ci seront cochés par défaut.<br/>\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.labelqualite",
                verbose_name="Label(s) qualité",
            ),
        ),
    ]
