# Generated by Django 5.2.7 on 2025-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0177_remove_displayedacteur_url_labelqualite_filtre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelqualite",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="labels"),
        ),
    ]
