# Generated by Django 5.2.7 on 2025-11-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0177_carteconfig_solution_temporaire_a_supprimer_des_que_possible_parametres_url",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EPCI",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="code_commune_insee",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="code_commune_insee",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="epci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.epci",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="epci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmo.epci",
            ),
        ),
    ]
