# Generated by Django 5.2.7 on 2025-11-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmo",
            "0177_carteconfig_solution_temporaire_a_supprimer_des_que_possible_parametres_url",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carteconfig",
            name="label",
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="label_qualite",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ce champ agit comme un filtre des résultats affichés.<br/> Si les labels sélectionnés correspondent aux labels affichés dans la modale de filtres de la carte, alors ceux-ci seront cochés par défaut.<br/>\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.labelqualite",
                verbose_name="Label(s) qualité",
            ),
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="nombre_d_acteurs_affiches",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre",
            field=models.BooleanField(
                default=False,
                help_text="Affiche le label dans la modale de filtres affichée sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre_label",
            field=models.CharField(
                blank=True,
                help_text="Configure le label affiché dans le champ de formulaire dans le panel de filtres sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="filtre_texte_d_aide",
            field=models.CharField(
                blank=True,
                help_text="Configure le texte d'aide affiché dans le champ de formulaire dans le panel de filtres sur la carte ou le mode liste",
            ),
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="labels"),
        ),
        migrations.AlterField(
            model_name="labelqualite",
            name="afficher",
            field=models.BooleanField(
                default=True,
                help_text="Affiche le label côté frontend, notamment dans les fiches acteur",
            ),
        ),
    ]
