# Generated by Django 5.2.7 on 2025-10-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0178_labelqualite_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carteconfig",
            old_name="label",
            new_name="label_qualite",
        ),
    ]
