# Generated by Django 5.2.8 on 2025-11-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0181_alter_acteur_location_alter_displayedacteur_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labelqualite",
            old_name="logo",
            new_name="logo_filtre",
        ),
    ]
