# Generated by Django 5.2.8 on 2025-11-20 14:17

from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0182_rename_labelqualite_logo_to_logo_filtre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labelqualite",
            options={
                "ordering": ["order"],
                "verbose_name": "Label qualité",
                "verbose_name_plural": "Labels qualité",
            },
        ),
        migrations.AddField(
            model_name="labelqualite",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="labelqualite",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                help_text="Version miniature du logo : PNG 32x32 pixels maximum, 50 Ko max. Utilisé dans : fiches acteurs sur la carte, export open data API. Contraintes strictes : exactement 32x32 pixels.",
                null=True,
                upload_to="logos",
                validators=[qfdmo.models.acteur.validate_logo],
                verbose_name="Logo pour carte et open data (PNG 32x32px)",
            ),
        ),
        migrations.AlterField(
            model_name="labelqualite",
            name="logo_filtre",
            field=models.FileField(
                blank=True,
                help_text="Logo affiché dans le panneau de filtres de la carte. Format SVG recommandé pour une qualité optimale. Utilisé dans : modale de filtres côté utilisateur.",
                null=True,
                upload_to="labels",
                verbose_name="Logo pour les filtres (SVG recommandé)",
            ),
        ),
    ]
