# Generated by Django 5.2.9 on 2025-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0183_alter_labelqualite_options_labelqualite_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayedacteur",
            name="latitude",
            field=models.FloatField(
                db_index=True, editable=False, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="longitude",
            field=models.FloatField(
                db_index=True, editable=False, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="latitude",
            field=models.FloatField(
                db_index=True, editable=False, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="longitude",
            field=models.FloatField(
                db_index=True, editable=False, null=True, verbose_name="Longitude"
            ),
        ),
    ]
