# Generated by Django 5.2.9 on 2025-12-17 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0183_alter_labelqualite_options_labelqualite_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Définir une zone géographique pour limiter l'affichage de la carte à une région spécifique",
                null=True,
                srid=4326,
                verbose_name="Zone géographique (bounding box)",
            ),
        ),
    ]
