# Generated by Django 5.2.8 on 2025-11-28 13:06

from django.db import migrations


def update_icons_for_groupe_actions(apps, schema_editor):
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")
    GroupeAction.objects.filter(icon="fr-icon-hand-heart-line").update(
        icon="fr-icon-hand-heart"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0183_alter_labelqualite_options_labelqualite_order_and_more"),
    ]

    operations = [migrations.RunPython(update_icons_for_groupe_actions)]
