# Generated by Django 5.2.9 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0184_add_bounding_box_to_carte_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="bonus_reparation",
            field=models.BooleanField(
                default=False,
                help_text="Cocher cette case pour afficher uniquement les acteurs proposant le bonus réparation",
                verbose_name="Bonus réparation uniquement",
            ),
        ),
    ]
