# Generated by Django 5.2.8 on 2025-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0184_rename_enfants_liste_vueacteur_liste_enfants_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS qfdmo_vueacteur_sources;
            """,
            reverse_sql="""
            """,
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="vue_acteurs", to="qfdmo.source"
            ),
        ),
    ]
