# Generated by Django 5.2.9 on 2026-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmo", "0186_merge_20251219_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="identifiant_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
