# Generated by Django 5.2.8 on 2025-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0187_alter_acteur_identifiant_unique_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupeactionconfig",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="groupeactionconfig",
            constraint=models.UniqueConstraint(
                fields=("carte_config", "groupe_action", "acteur_type"),
                name="unique_carte_config_groupe_action_acteur_type",
            ),
        ),
    ]
