# Generated by Django 5.2.9 on 2026-01-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0188_alter_groupeactionconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="acteur",
            name="acteur_unique_by_source_and_external_id",
        ),
        migrations.AlterField(
            model_name="acteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AlterField(
            model_name="propositionservice",
            name="acteur",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposition_services",
                to="qfdmo.acteur",
            ),
        ),
        migrations.AlterField(
            model_name="revisionacteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AlterField(
            model_name="revisionpropositionservice",
            name="acteur",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposition_services",
                to="qfdmo.revisionacteur",
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="action_principale",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmo.action",
            ),
        ),
        migrations.AddConstraint(
            model_name="acteur",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "ACTIF")),
                fields=("source", "identifiant_externe"),
                name="acteur_unique_by_source_and_external_id",
            ),
        ),
    ]
