# Generated by Django 5.2.9 on 2026-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0188_carteconfig_cacher_filtre_objet_carteconfig_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="displayedacteur",
            name="source",
        ),
        migrations.RemoveField(
            model_name="vueacteur",
            name="source",
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="est_parent",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="L'acteur est un parent"
            ),
        ),
    ]
