# Generated by Django 5.2.9 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0188_carteconfig_cacher_filtre_objet"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="test",
            field=models.BooleanField(
                default=False,
                help_text="Cocher cette case pour marquer cette carte comme une carte"
                " de test (utilisée pour les tests e2e). Les cartes de test sont "
                " masquées par défaut dans l'interface d'administration",
                verbose_name="Carte de test",
            ),
        ),
    ]
