# Suggestion statut
SUGGESTION_AVALIDER = "AVALIDER"
SUGGESTION_REJETEE = "REJETEE"
SUGGESTION_ATRAITER = "ATRAITER"
SUGGESTION_ENCOURS = "ENCOURS"
SUGGESTION_ERREUR = "ERREUR"
SUGGESTION_SUCCES = "SUCCES"

# SuggestionCohorte type_action
SUGGESTION_CRAWL_URLS = "CRAWL_URLS"
SUGGESTION_CLUSTERING = "CLUSTERING"
SUGGESTION_SOURCE_AJOUT = "SOURCE_AJOUT"
SUGGESTION_SOURCE_MODIFICATION = "SOURCE_MODIFICATION"
SUGGESTION_SOURCE_SUPRESSION = "SOURCE_SUPRESSION"

# Public accueilli
PUBLIC_PAR = "Particuliers"
PUBLIC_PRO = "Professionnels"
PUBLIC_PRO_ET_PAR = "Particuliers et professionnels"
PUBLIC_AUCUN = "Aucun"

# Acteur statut
ACTEUR_ACTIF = "ACTIF"
ACTEUR_INACTIF = "INACTIF"
ACTEUR_SUPPRIME = "SUPPRIME"

# Reprise
REPRISE_1POUR0 = "1 pour 0"
REPRISE_1POUR1 = "1 pour 1"

# Special field values
EMPTY_ACTEUR_FIELD = "__empty__"

# To handle data we don't want to show on frontend
INFO_TO_HIDE = "[Information masquée]"
