# Suggestion statuts (pour cohorte et unitaire)
SUGGESTION_AVALIDER = "AVALIDER"
SUGGESTION_REJETER = "REJETER"
SUGGESTION_PARTIEL = "PARTIEL"
SUGGESTION_ATRAITER = "ATRAITER"
SUGGESTION_ENCOURS = "ENCOURS"
SUGGESTION_ERREUR = "ERREUR"
SUGGESTION_SUCCES = "SUCCES"

# SuggestionCohorte actions
SUGGESTION_CLUSTERING = "CLUSTERING"
SUGGESTION_SOURCE = "SOURCE"
SUGGESTION_SOURCE_AJOUT = "SOURCE_AJOUT"
SUGGESTION_SOURCE_MISESAJOUR = "SOURCE_MISESAJOUR"
SUGGESTION_SOURCE_SUPRESSION = "SOURCE_SUPRESSION"
SUGGESTION_ENRICHISSEMENT = "ENRICHISSEMENT"

# Public accueilli
PUBLIC_PAR = "Particuliers"
PUBLIC_PRO = "Professionnels"
PUBLIC_PRO_ET_PAR = "Particuliers et professionnels"
PUBLIC_AUCUN = "Aucun"

# Acteur Statuts
ACTEUR_ACTIF = "ACTIF"
ACTEUR_INACTIF = "INACTIF"
ACTEUR_SUPPRIME = "SUPPRIME"

# Reprise
REPRISE_1POUR0 = "1 pour 0"
REPRISE_1POUR1 = "1 pour 1"
