version: 2

models:
  - name: base_acteur
    description: "Acteurs Importés"
    columns:
      - name: id
        description: "L'identifiant unique de l'acteur"
        data_tests:
          - not_null
          - unique
      - name: nom
        description: "Le nom de l'acteur"
        data_tests:
          - not_null
      - name: description
        description: "La description de l'acteur"
      - name: acteur_type_id
        description: "Le type d'acteur"
      - name: adresse
        description: "L'adresse de l'acteur"
      - name: adresse_complement
        description: "L'adresse complémentaire de l'acteur"
      - name: code_postal
        description: "Le code postal de l'acteur"
      - name: ville
        description: "La ville de l'acteur"
      - name: url
        description: "L'URL de l'acteur"
      - name: email
        description: "L'email de l'acteur"
      - name: location
        description: "La localisation de l'acteur"
      - name: telephone
        description: "Le numéro de téléphone de l'acteur"
      - name: nom_commercial
        description: "Le nom commercial de l'acteur"
      - name: nom_officiel
        description: "Le nom officiel de l'acteur"
      - name: siren
        description: "Le numéro SIREN de l'acteur"
      - name: siret
        description: "Le numéro SIRET de l'acteur"
      - name: source_id
        description: "L'identifiant source de l'acteur"
      - name: identifiant_externe
        description: "L'identifiant externe de l'acteur"
      - name: naf_principal
        description: "Le code NAF principal de l'acteur"
      - name: commentaires
        description: "Les commentaires de l'acteur"
      - name: horaires_osm
        description: "Les horaires OSM de l'acteur"
      - name: horaires_description
        description: "La description des horaires de l'acteur"
      - name: public_accueilli
        description: "Le public accueilli par l'acteur"
      - name: reprise
        description: "La reprise de l'acteur"
      - name: exclusivite_de_reprisereparation
        description: "L'exclusivité de la réparation de l'acteur"
      - name: uniquement_sur_rdv
        description: "Le fait que l'acteur soit uniquement sur RDV"
      - name: action_principale_id
        description: "L'action principale de l'acteur"
      - name: modifie_le
        description: "La date de modification de l'acteur"
      - name: parent_id
        description: "L'identifiant du parent de l'acteur"
      - name: cree_le
        description: "La date de création de l'acteur"
      - name: statut
        description: "Le statut de l'acteur"
  - name: base_acteur_acteur_services
    description: "Services des acteurs"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: acteurservice_id
        description: "The acteurservice_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - acteurservice_id
  - name: base_acteur_labels
    description: "Labels des acteurs"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: labelqualite_id
        description: "The labelqualite_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - labelqualite_id
  - name: base_propositionservice
    description: "Propositions de services"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The vueacteur_id for this table"
        data_tests:
          - not_null
      - name: action_id
        description: "The action_id for this table"
        data_tests:
          - not_null
      - name: ps_id
        description: "The ps_id for this table"
      - name: rps_id
        description: "The rps_id for this table"
      - name: revision_existe
        description: "The revision_existe for this table"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - action_id
  - name: base_propositionservice_sous_categories
    description: "Sous-catégories de propositions de services"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: propositionservice_id
        description: "The propositionservice_id for this table"
        data_tests:
          - not_null
      - name: souscategorieobjet_id
        description: "The souscategorieobjet_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - propositionservice_id
            - souscategorieobjet_id
  - name: base_revisionacteur
    description: "Correction sur les acteurs"
    columns:
      - name: id
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: description
        description: "La description de l'acteur"
      - name: acteur_type_id
        description: "Le type d'acteur"
      - name: adresse
        description: "L'adresse de l'acteur"
      - name: adresse_complement
        description: "L'adresse complémentaire de l'acteur"
      - name: code_postal
        description: "Le code postal de l'acteur"
      - name: ville
        description: "La ville de l'acteur"
      - name: url
        description: "L'URL de l'acteur"
      - name: email
        description: "L'email de l'acteur"
      - name: location
        description: "La localisation de l'acteur"
      - name: telephone
        description: "Le numéro de téléphone de l'acteur"
      - name: nom_commercial
        description: "Le nom commercial de l'acteur"
      - name: nom_officiel
        description: "Le nom officiel de l'acteur"
      - name: siren
        description: "Le numéro SIREN de l'acteur"
      - name: siret
        description: "Le numéro SIRET de l'acteur"
      - name: source_id
        description: "L'identifiant source de l'acteur"
      - name: identifiant_externe
        description: "L'identifiant externe de l'acteur"
      - name: naf_principal
        description: "Le code NAF principal de l'acteur"
      - name: commentaires
        description: "Les commentaires de l'acteur"
      - name: horaires_osm
        description: "Les horaires OSM de l'acteur"
      - name: horaires_description
        description: "La description des horaires de l'acteur"
      - name: public_accueilli
        description: "Le public accueilli par l'acteur"
      - name: reprise
        description: "La reprise de l'acteur"
      - name: exclusivite_de_reprisereparation
        description: "L'exclusivité de la réparation de l'acteur"
      - name: uniquement_sur_rdv
        description: "Le fait que l'acteur soit uniquement sur RDV"
      - name: action_principale_id
        description: "L'action principale de l'acteur"
      - name: modifie_le
        description: "La date de modification de l'acteur"
      - name: parent_id
        description: "L'identifiant du parent de l'acteur"
      - name: cree_le
        description: "La date de création de l'acteur"
      - name: statut
        description: "Le statut de l'acteur"
  - name: base_revisionacteur_acteur_services
    description: "Services des acteurs"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: revisionacteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: acteurservice_id
        description: "The acteurservice_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - revisionacteur_id
            - acteurservice_id
  - name: base_revisionacteur_labels
    description: "Labels des acteurs"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: revisionacteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: labelqualite_id
        description: "The labelqualite_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - revisionacteur_id
            - labelqualite_id
  - name: base_revisionpropositionservice
    description: "Propositions de services"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The vueacteur_id for this table"
        data_tests:
          - not_null
      - name: action_id
        description: "The action_id for this table"
        data_tests:
          - not_null
      - name: ps_id
        description: "The ps_id for this table"
      - name: rps_id
        description: "The rps_id for this table"
      - name: revision_existe
        description: "The revision_existe for this table"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - acteur_id
            - action_id
  - name: base_revisionpropositionservice_sous_categories
    description: "Sous-catégories de propositions de services"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: revisionpropositionservice_id
        description: "The revisionpropositionservice_id for this table"
        data_tests:
          - not_null
      - name: souscategorieobjet_id
        description: "The souscategorieobjet_id for this table"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - revisionpropositionservice_id
            - souscategorieobjet_id
  - name: base_source
    description: "Sources"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: libelle
        description: "The libelle for this table"
        data_tests:
          - not_null
      - name: code
        description: "The code for this table"
        data_tests:
          - not_null
          - unique
      - name: afficher
        description: "The afficher for this table"
        data_tests:
          - not_null
      - name: url
        description: "The url for this table"
      - name: logo_file
        description: "The logo_file for this table"
      - name: licence
        description: "The licence for this table"
