import { expect, test } from "@playwright/test"
import {
  getIframe,
  navigateTo,
  openModal,
  searchForAurayInIframe,
  TIMEOUT,
} from "./helpers"

/**
 * Helper function to open filtres modal in iframe context and keep it open
 */
async function openFiltresModal(iframe: ReturnType<typeof getIframe>) {
  await openModal(iframe, {
    buttonSelector: { role: "button", name: /Filtres/i },
    modalDataTestId: "modal-carte:filtres",
    modalContentSelector: 'input[name="filtres-bonus"]', // Wait for a field that's always present
    closeModal: false, // Keep modal open so we can check fields
  })
}

test.describe("🎛️ Configuration Carte - Paramètre Legacy Bonus", () => {
  test("Le paramètre legacy bonus=1 en iframe initialise le filtre bonus comme coché", async ({
    page,
  }) => {
    // Navigate to the test preview page
    await navigateTo(page, "/lookbook/preview/tests/t_9_bonus_legacy_parameter_iframe")

    // Wait for the iframe to be loaded (direct iframe with bonus=1 in URL)
    const iframe = getIframe(page)
    await expect(iframe.locator("body")).toBeAttached({ timeout: TIMEOUT.DEFAULT })

    // Wait for the carte to be loaded
    await iframe
      .locator('[data-testid="carte-adresse-input"]')
      .waitFor({ timeout: TIMEOUT.DEFAULT })

    // Perform a search to make the filtres button appear
    await searchForAurayInIframe(iframe)

    // Open the filtres modal
    await openFiltresModal(iframe)

    // Verify that the bonus checkbox is checked
    const bonusCheckbox = iframe.locator('input[name="filtres-bonus"]')
    await expect(bonusCheckbox).toBeChecked({ timeout: TIMEOUT.SHORT })
  })

  test("Le paramètre legacy data-bonus='1' via script initialise le filtre bonus comme coché", async ({
    page,
  }) => {
    // Navigate to the test preview page
    await navigateTo(page, "/lookbook/preview/tests/t_10_bonus_legacy_parameter_script")

    // Wait for the iframe to be loaded (generated by carte.js with data-bonus="1")
    const iframe = getIframe(page)
    await expect(iframe.locator("body")).toBeAttached({ timeout: TIMEOUT.DEFAULT })

    // Wait for the carte to be loaded
    await iframe
      .locator('[data-testid="carte-adresse-input"]')
      .waitFor({ timeout: TIMEOUT.DEFAULT })

    // Perform a search to make the filtres button appear
    await searchForAurayInIframe(iframe)

    // Open the filtres modal
    await openFiltresModal(iframe)

    // Verify that the bonus checkbox is checked
    const bonusCheckbox = iframe.locator('input[name="filtres-bonus"]')
    await expect(bonusCheckbox).toBeChecked({ timeout: TIMEOUT.SHORT })
  })
})

test.describe("🎛️ Configuration Carte - Cacher Filtre Objet", () => {
  test("Une CarteConfig avec cacher_filtre_objet=True masque le filtre objet", async ({
    page,
  }) => {
    // Navigate to the test preview page
    await navigateTo(page, "/lookbook/preview/tests/t_11_cacher_filtre_objet")

    // Wait for the iframe to be loaded
    const iframe = getIframe(page)
    await expect(iframe.locator("body")).toBeAttached({ timeout: TIMEOUT.DEFAULT })

    // Wait for the carte to be loaded
    await iframe
      .locator('[data-testid="carte-adresse-input"]')
      .waitFor({ timeout: TIMEOUT.DEFAULT })

    // Perform a search to make the filtres button appear
    await searchForAurayInIframe(iframe)

    // Open the filtres modal
    await openFiltresModal(iframe)

    // Verify that the synonyme field is NOT present in the form
    const synonymeField = iframe.locator('input[id="id_filtres-synonyme"]')
    await expect(synonymeField).not.toBeAttached()
  })

  test("Une CarteConfig avec paramètres par défaut affiche le filtre objet", async ({
    page,
  }) => {
    // Navigate to the test preview page
    await navigateTo(page, "/lookbook/preview/tests/t_12_default_filtre_objet")

    // Wait for the iframe to be loaded
    const iframe = getIframe(page)
    await expect(iframe.locator("body")).toBeAttached({ timeout: TIMEOUT.DEFAULT })

    // Wait for the carte to be loaded
    await iframe
      .locator('[data-testid="carte-adresse-input"]')
      .waitFor({ timeout: TIMEOUT.DEFAULT })

    // Perform a search to make the filtres button appear
    await searchForAurayInIframe(iframe)

    // Open the filtres modal
    await openFiltresModal(iframe)

    // Verify that the synonyme field IS present in the form
    const synonymeField = iframe.locator('input[id="id_filtres-synonyme"]')
    await expect(synonymeField).toBeAttached({ timeout: TIMEOUT.SHORT })
    await expect(synonymeField).toBeVisible({ timeout: TIMEOUT.SHORT })
  })
})
