import { expect, test } from "@playwright/test"
import { openAdvancedFilters, searchDummyAdresse } from "./helpers"

test.describe("🗺️ Filtres Avancés Carte", () => {
  async function searchInCarteMode(page) {
    await page.locator("input#id_adresse").click()
    await page.locator("input#id_adresse").fill("Paris")
    await page
      .locator("#id_adresseautocomplete-list.autocomplete-items div:nth-of-type(2)")
      .click()
  }

  test("Filtres avancés s'ouvrent et se ferment en mode carte", async ({ page }) => {
    await page.goto(`/carte`, {
      waitUntil: "domcontentloaded",
    })
    await searchInCarteMode(page)
    await openAdvancedFilters(
      page,
      "carte-legend",
      "modal-button-carte:filtres",
      "modal-carte:filtres",
    )
  })

  test(
    "Filtres avancés s'ouvrent et se ferment en mode carte en mobile",
    { tag: ["@mobile"] },
    async ({ page }) => {
      await page.goto(`/carte`, {
        waitUntil: "domcontentloaded",
      })
      await searchInCarteMode(page)
      await openAdvancedFilters(
        page,
        "view-mode-nav",
        "modal-button-carte:filtres",
        "modal-carte:filtres",
      )
    },
  )
})
test.describe("🗺️ Affichage Légende Carte", () => {
  test("La carte affiche la légende après une recherche", async ({ page }) => {
    // Navigate to the carte page
    await page.goto(`/carte`, { waitUntil: "domcontentloaded" })

    await expect(page.getByTestId("carte-legend")).toBeHidden()

    // Fill "Adresse" autocomplete input
    await searchDummyAdresse(page)
    await expect(page.getByTestId("carte-legend")).toBeVisible()
  })
})

test.describe("🗺️ Pinpoint Active State", () => {
  test("Clicking a pinpoint adds active class and removes it from other pinpoints", async ({
    page,
  }) => {
    // Navigate to the preview page with multiple pinpoints
    await page.goto(`/lookbook/preview/components/acteur_pinpoint_multiple`, {
      waitUntil: "domcontentloaded",
    })

    const pinpoint1 = page.getByTestId("pinpoint-1").locator("a")
    const pinpoint2 = page.getByTestId("pinpoint-2").locator("a")

    // Initially, no pinpoint should have the active class
    await expect(pinpoint1).not.toHaveClass(/active-pinpoint/)
    await expect(pinpoint2).not.toHaveClass(/active-pinpoint/)

    // Click on first pinpoint
    await pinpoint1.click()
    await expect(pinpoint1).toHaveClass(/active-pinpoint/)
    await expect(pinpoint2).not.toHaveClass(/active-pinpoint/)

    // Click on second pinpoint
    await pinpoint2.click()
    await expect(pinpoint1).not.toHaveClass(/active-pinpoint/)
    await expect(pinpoint2).toHaveClass(/active-pinpoint/)

    // Click on first pinpoint again
    await pinpoint1.click()
    await expect(pinpoint1).toHaveClass(/active-pinpoint/)
    await expect(pinpoint2).not.toHaveClass(/active-pinpoint/)
  })
})

test.describe("🗺️ Mode Carte/Liste Switch with Bounding Box", () => {
  test("Bounding box is preserved when switching between Carte and Liste modes", async ({
    page,
  }) => {
    // Navigate to the test preview page that generates the iframe
    await page.goto("/lookbook/preview/tests/carte_mode_liste_switch", {
      waitUntil: "domcontentloaded",
    })

    // Wait for the iframe to be loaded (generated by carte.js)
    const iframe = page.frameLocator("iframe").first()
    await expect(iframe.locator("body")).toBeAttached({ timeout: 10000 })

    // Wait for the carte to be loaded - legend should be visible
    await iframe.locator("[data-testid='carte-legend']").waitFor({ timeout: 10000 })

    // Helper function to get the bounding box from the URL
    async function getBoundingBoxFromURL() {
      const url = await iframe.locator("body").evaluate(() => window.location.href)
      const urlParams = new URLSearchParams(url.split("?")[1])
      return urlParams.get("bounding_box") || urlParams.get("carte_map-bounding_box")
    }

    // Get initial bounding box
    const initialBoundingBox = await getBoundingBoxFromURL()
    expect(initialBoundingBox).toBeTruthy()

    // Find the Liste radio button in the segmented control and click it
    const listeButton = iframe
      .locator('input[type="radio"][value="liste"]')
      .or(iframe.locator('input[type="radio"][value="LISTE"]'))
    await expect(listeButton).toBeAttached({ timeout: 5000 })
    await listeButton.click({ force: true })

    // Verify we're in Liste mode by checking that:
    // 1. The map container is NOT visible (carte mode hidden)
    // 2. The pagination/results text is visible (liste mode shown)
    await expect(iframe.locator('[data-map-target="mapContainer"]')).not.toBeVisible({
      timeout: 30000,
    })

    // Check for liste mode indicators (pagination or results count)
    const listeModeIndicator = iframe
      .locator('span:has-text("résultats")')
      .or(iframe.locator(".fr-pagination"))
    await expect(listeModeIndicator).toBeVisible({ timeout: 5000 })

    // Click back to Carte mode
    const carteButton = iframe
      .locator('input[type="radio"][value="carte"]')
      .or(iframe.locator('input[type="radio"][value="CARTE"]'))
    await expect(carteButton).toBeAttached({ timeout: 5000 })
    await carteButton.click({ force: true })

    // Wait for mode to switch back to Carte - legend should be visible again
    await iframe.locator("[data-testid='carte-legend']").waitFor({ timeout: 10000 })

    // Check that the bounding box is still present in the URL
    const finalBoundingBox = await getBoundingBoxFromURL()
    expect(finalBoundingBox).toBeTruthy()

    // Verify that the bounding box hasn't been lost
    // Parse the JSON to compare the actual values
    const initialBbox = JSON.parse(initialBoundingBox || "{}")
    const finalBbox = JSON.parse(finalBoundingBox || "{}")
    expect(finalBbox).toEqual(initialBbox)

    // Verify that the map container is still present
    const mapContainer = iframe.locator('[data-map-target="mapContainer"]')
    await expect(mapContainer).toBeAttached()
  })
})
