# Generated by Django 5.2.3 on 2025-07-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0038_produitpage_infotri_alter_produitpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produitpage",
            old_name="gender",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="produitpage",
            old_name="number",
            new_name="nombre",
        ),
        migrations.AddField(
            model_name="produitpage",
            name="usage_unique",
            field=models.BooleanField(default=False, verbose_name="À usage unique"),
        ),
    ]
