# Generated by Django 5.2.3 on 2025-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0038_produitpage_infotri_alter_produitpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.IntegerField(
                help_text="Correspond à l'identifiant ID défini dans les données <i>Que Faire</i>.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
