# Generated by Django 5.2.3 on 2025-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0039_alter_produit_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.AutoField(
                help_text="Correspond à l'identifiant ID défini dans les données <i>Que Faire</i>.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
