# Generated by Django 5.2.3 on 2025-07-03 21:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0039_rename_gender_produitpage_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="commentaire",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
