# Generated by Django 5.2.3 on 2025-07-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0040_produitpage_commentaire"),
        ("qfdmd", "0041_alter_produit_id"),
    ]

    operations = []
