# Generated by Django 5.2.3 on 2025-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0043_alter_produitpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="titre_phrase",
            field=models.CharField(
                default="",
                help_text="Ce titre sera utilisé dans les contenus réutilisables, pour l'affichage du synonyme de recherche",
                verbose_name="Titre utilisé dans les phrases",
            ),
            preserve_default=False,
        ),
    ]
