# Generated by Django 5.2.3 on 2025-07-17 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmd", "0044_produitpage_titre_phrase"),
    ]

    operations = [
        # No-op: this used to CREATE TEXT SEARCH CONFIGURATION wagtail_french,
        # but that now happens in scripts/sql/create_extensions.sql, which
        # runs before migrate. Keeping the migration (rather than deleting
        # it) preserves the dependency chain and applied-migration history.
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
