# Generated by Django 5.2.3 on 2025-07-17 13:17

from pathlib import Path

from django.db import migrations

# Read from a shared .sql file so the migration, create_webapp_sample_db.py and
# the Makefile restore targets all run identical SQL (it is run as a dedicated
# step right after create_extensions.sql by every caller). The SQL is guarded,
# so order does not matter. This migration is the source of truth for the test
# DB and any fresh DB, which are built from migrations only.
# The file lives next to this migration (inside webapp/) so it is present on
# deployments that only ship the webapp directory, such as Scalingo.
_WAGTAIL_FRENCH_SQL = (
    Path(__file__).parent / "sql" / "create_wagtail_french_config.sql"
).read_text()


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmd", "0044_produitpage_titre_phrase"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_WAGTAIL_FRENCH_SQL,
            reverse_sql="DROP TEXT SEARCH CONFIGURATION IF EXISTS wagtail_french;",
        ),
    ]
