# Generated by Django 5.2.4 on 2025-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0050_bonus_produitpage_disable_bonus_inheritance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reusablecontent",
            name="title",
            field=models.CharField(unique=True),
        ),
    ]
