# Generated by Django 5.2.4 on 2025-08-01 13:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0051_alter_reusablecontent_title"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpagemarquetag",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="produitpagemarquetag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="produitpagematieretag",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="produitpagematieretag",
            name="tag",
        ),
        migrations.AlterModelOptions(
            name="reusablecontent",
            options={
                "verbose_name": "Contenu réutilisable",
                "verbose_name_plural": "Contenus réutilisables",
            },
        ),
        migrations.RemoveConstraint(
            model_name="produitpage",
            name="no_produit_and_synonyme_filled_in_parallel",
        ),
        migrations.RenameField(
            model_name="produitpage",
            old_name="produit",
            new_name="legacy_produit",
        ),
        migrations.RenameField(
            model_name="produitpage",
            old_name="synonyme",
            new_name="legacy_synonyme",
        ),
        migrations.AddField(
            model_name="synonymepage",
            name="titre_phrase",
            field=models.CharField(
                default="",
                help_text="Ce titre sera utilisé dans les contenus réutilisables, pour l'affichage du synonyme de recherche",
                verbose_name="Titre utilisé dans les phrases",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="content",
            field=wagtail.fields.RichTextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="title",
            field=models.CharField(unique=True, verbose_name="Titre"),
        ),
        migrations.AddConstraint(
            model_name="produitpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legacy_produit__isnull", True),
                    ("legacy_synonyme__isnull", True),
                    _connector="OR",
                ),
                name="no_produit_and_synonyme_filled_in_parallel",
            ),
        ),
        migrations.DeleteModel(
            name="ProduitPageMarqueTag",
        ),
        migrations.DeleteModel(
            name="ProduitPageMatiereTag",
        ),
    ]
