# Generated by Django 5.2.5 on 2025-09-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0061_legacyintermediateproduitpage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormPageValidationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sélectionnez la page de formulaire utilisée pour  le formulaire de contact. Celle-ci doit avoir exactement 4 champs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres des pages de formulaire",
            },
        ),
    ]
