# Generated by Django 5.2.5 on 2025-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0062_formpagevalidationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.AutoField(
                help_text="A l'origine : Correspond à l'identifiant ID défini dans les données <i>Que Faire</i>. Maintenant : Identifiant auto-généré.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RunSQL(
            "SELECT setval('qfdmd_produit_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM qfdmd_produit;",
            reverse_sql="SELECT 1;",
        ),
    ]
