# Generated by Django 5.2.7 on 2025-11-06 10:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0064_alter_produitindexpage_body_alter_produitpage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyintermediateproduitpage",
            name="produit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_wagtail_page",
                to="qfdmd.produit",
            ),
        ),
        migrations.CreateModel(
            name="LegacyIntermediateProduitPageSynonymeExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_synonyme_to_exclude",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "synonyme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="should_not_redirect_to",
                        to="qfdmd.synonyme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche synonyme",
                "verbose_name_plural": "Fiches synonyme",
            },
        ),
    ]
