# Generated by Django 5.2.9 on 2025-12-10 15:59

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0067_remove_produitpage_legacy_synonyme_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyintermediateproduitpagesynonymeexclusion",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_synonymes_to_exclude",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="legacyintermediatesynonymepage",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_synonymes",
                to="wagtailcore.page",
            ),
        ),
    ]
