# Generated by Django 5.2.9 on 2026-01-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmd",
            "0068_alter_legacyintermediateproduitpagesynonymeexclusion_page_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Suggestion",
        ),
    ]
