# Generated by Django 5.2.11 on 2026-02-23 09:12

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


def create_search_terms_for_synonymes(apps, schema_editor):
    """Create SearchTerm records for existing Synonyme instances."""
    Synonyme = apps.get_model("qfdmd", "Synonyme")
    SearchTerm = apps.get_model("search", "SearchTerm")

    for synonyme in Synonyme.objects.all():
        search_term = SearchTerm.objects.create()
        synonyme.searchterm_ptr_id = search_term.id
        synonyme.save(update_fields=["searchterm_ptr_id"])


def reverse_search_terms_for_synonymes(apps, schema_editor):
    """Reverse: delete SearchTerm records created for Synonyme instances."""
    Synonyme = apps.get_model("qfdmd", "Synonyme")
    SearchTerm = apps.get_model("search", "SearchTerm")

    search_term_ids = Synonyme.objects.exclude(
        searchterm_ptr_id__isnull=True
    ).values_list("searchterm_ptr_id", flat=True)
    SearchTerm.objects.filter(pk__in=list(search_term_ids)).delete()


def populate_search_term_produit_page(apps, schema_editor):
    ProduitPage = apps.get_model("qfdmd", "ProduitPage")
    for p in ProduitPage.objects.all():
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0072_alter_produitindexpage_body_alter_produitpage_body"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="migree_depuis_synonymes_legacy",
            field=models.BooleanField(
                default=False, verbose_name="Migration des synonymes effectuée"
            ),
        ),
        # Step 1: Add searchterm_ptr as nullable
        migrations.AddField(
            model_name="synonyme",
            name="searchterm_ptr",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="search.searchterm",
            ),
        ),
        migrations.RunPython(
            create_search_terms_for_synonymes,
            reverse_search_terms_for_synonymes,
        ),
        # Django 6.0 no longer uses CASCADE when dropping a column, so FK
        # constraints on legacy tables that reference synonyme.id must be
        # handled explicitly before we can drop that column.
        # Step A: drop the FK constraints and remap the FK values to the new PK
        migrations.RunSQL(
            sql="""
                -- Drop old FK constraints referencing synonyme.id
                ALTER TABLE qfdmd_legacyintermediateproduitpagesynonymeexclusion
                    DROP CONSTRAINT qfdmd_legacyintermed_synonyme_id_775c903b_fk_qfdmd_syn;
                ALTER TABLE qfdmd_legacyintermediatesynonymepage
                    DROP CONSTRAINT qfdmd_legacyintermed_synonyme_id_748f673c_fk_qfdmd_syn;

                -- Remap FK values: old synonyme.id → new synonyme.searchterm_ptr_id
                UPDATE qfdmd_legacyintermediateproduitpagesynonymeexclusion exc
                SET synonyme_id = syn.searchterm_ptr_id
                FROM qfdmd_synonyme syn
                WHERE exc.synonyme_id = syn.id;

                UPDATE qfdmd_legacyintermediatesynonymepage sp
                SET synonyme_id = syn.searchterm_ptr_id
                FROM qfdmd_synonyme syn
                WHERE sp.synonyme_id = syn.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step B: now id has no dependents, drop it and promote searchterm_ptr to PK
        migrations.RemoveField(
            model_name="synonyme",
            name="id",
        ),
        migrations.AlterField(
            model_name="synonyme",
            name="searchterm_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="search.searchterm",
            ),
        ),
        # Step C: re-add FK constraints now referencing the new PK
        migrations.RunSQL(
            sql="""
                ALTER TABLE qfdmd_legacyintermediateproduitpagesynonymeexclusion
                    ADD CONSTRAINT qfdmd_legacyintermed_synonyme_id_775c903b_fk_qfdmd_syn
                    FOREIGN KEY (synonyme_id)
                    REFERENCES qfdmd_synonyme(searchterm_ptr_id)
                    DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE qfdmd_legacyintermediatesynonymepage
                    ADD CONSTRAINT qfdmd_legacyintermed_synonyme_id_748f673c_fk_qfdmd_syn
                    FOREIGN KEY (synonyme_id)
                    REFERENCES qfdmd_synonyme(searchterm_ptr_id)
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="ProduitPageSearchTerm",
            fields=[
                (
                    "searchterm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchterm",
                    ),
                ),
                ("searchable_title", models.CharField()),
                (
                    "produit_page",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produit_page_search_term",
                        to="qfdmd.produitpage",
                    ),
                ),
            ],
            bases=("search.searchterm",),
        ),
        migrations.CreateModel(
            name="SearchTag",
            fields=[
                (
                    "searchterm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchterm",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "legacy_existing_synonyme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Référence vers le synonyme legacy dont ce tag est issu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_tag_reference",
                        to="qfdmd.synonyme",
                        verbose_name="Synonyme legacy associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
            bases=("search.searchterm", models.Model),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="imported_as_search_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, ce synonyme a été importé comme SearchTag et ne devrait plus apparaître dans les résultats de recherche.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_synonymes",
                to="qfdmd.searchtag",
                verbose_name="Importé comme SearchTag",
            ),
        ),
        migrations.CreateModel(
            name="TaggedSearchTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tags_items",
                        to="qfdmd.produitpage",
                    ),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_produit_page",
                        to="qfdmd.searchtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
        ),
        migrations.AddField(
            model_name="produitpage",
            name="search_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="qfdmd.TaggedSearchTag",
                to="qfdmd.SearchTag",
                verbose_name="Synonyme de recherche",
            ),
        ),
        migrations.RunPython(populate_search_term_produit_page),
    ]
