# Generated by Django 5.2.11 on 2026-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0075_synonyme_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonyme",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Un synonyme désactivé ne s'affichera nulle part. \nOn le conserve en base de données pour conserver les redirections",
                verbose_name="Désactivé",
            ),
        ),
    ]
