# Generated by Django 5.2.11 on 2026-02-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0076_homepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageSettings",
        ),
    ]
