# Generated by Django 5.2.11 on 2026-02-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0078_homepage_inherit_contentpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_title",
        ),
    ]
