# Generated by Django 6.0.2 on 2026-03-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0079_remove_homepage_hero_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synonyme",
            name="disabled",
        ),
    ]
