# Generated by Django 6.0.2 on 2026-03-24 09:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0080_remove_synonyme_disabled"),
        (
            "sites_conformes_content_manager",
            "0072_catalogindexpage_filter_selection_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sites_conformes_content_manager.contentpage",
                    ),
                ),
                (
                    "hero_subtitle",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Sous-titre"),
                ),
                (
                    "hero_search_label",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Label du champ de recherche",
                    ),
                ),
                (
                    "icons",
                    wagtail.fields.StreamField(
                        [("image", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
                        verbose_name="Icônes de la page d'accueil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page d'accueil",
            },
            bases=("sites_conformes_content_manager.contentpage",),
        ),
    ]
