# Generated by Django 6.0.2 on 2026-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0075_homepage"),
        ("qfdmd", "0080_remove_synonyme_disabled"),
    ]

    operations = []
