# Generated by Django 6.0.4 on 2026-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0082_produitpagesearchterm_cascade_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="ab_test_carte_default_view",
            field=models.BooleanField(
                default=False,
                help_text="Activer le test A/B qui sert le mode liste par défaut sur mobile à 50% des sessions (flag PostHog <code>produit-carte-default-view-mobile</code>). À activer uniquement sur les fiches sélectionnées pour l'expérience.",
                verbose_name="A/B test mode carte/liste par défaut",
            ),
        ),
    ]
