# Generated by Django 6.0.6 on 2026-07-13 13:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0087_produitindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="legacy_imported_as_produit_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, ce produit a été migré automatiquement vers cette ProduitPage par la commande migrate_produits_legacy.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_imported_produits",
                to="qfdmd.produitpage",
                verbose_name="Migré automatiquement vers la page",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="automatically_migrated_from_legacy_produit",
            field=models.BooleanField(
                default=False,
                help_text="Si cochée, cette page a été créée automatiquement à partir d'une fiche produit Django (ancien système) par la commande migrate_produits_legacy.",
                verbose_name="Produit legacy migré automatiquement",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_code",
            field=models.CharField(blank=True, verbose_name="Code (legacy)"),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_comment_les_eviter",
            field=models.TextField(
                blank=True, verbose_name="Comment consommer responsable ? (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_filieres_rep",
            field=models.CharField(
                blank=True, verbose_name="Filière(s) REP concernée(s) (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_infotri",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
                verbose_name="Infotri (legacy)",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_modifie_le",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Dernière modification du produit legacy",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_nom",
            field=models.CharField(blank=True, verbose_name="Libellé (legacy)"),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_nom_eco_organisme",
            field=models.CharField(
                blank=True, verbose_name="Nom de l'éco-organisme (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_qu_est_ce_que_j_en_fais",
            field=models.TextField(
                blank=True,
                verbose_name="Qu'est-ce que j'en fais ? - ANCIEN CHAMP (legacy)",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_qu_est_ce_que_j_en_fais_bon_etat",
            field=models.TextField(
                blank=True, verbose_name="Qu'est-ce que j'en fais ? - Bon état (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_qu_est_ce_que_j_en_fais_mauvais_etat",
            field=models.TextField(
                blank=True,
                verbose_name="Qu'est-ce que j'en fais ? - Mauvais état (legacy)",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_que_va_t_il_devenir",
            field=models.TextField(
                blank=True, verbose_name="Que va-t-il devenir ? (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="legacy_slug",
            field=models.CharField(blank=True, verbose_name="Slug (legacy)"),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="legacy_imported_as_search_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, ce synonyme a été importé comme SearchTag par la migration automatique (migrate_produits_legacy) et ne devrait plus apparaître dans les résultats de recherche. Les synonymes migrés manuellement utilisent imported_as_search_tag.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_imported_synonymes",
                to="qfdmd.searchtag",
                verbose_name="Importé automatiquement comme SearchTag",
            ),
        ),
    ]
