# Generated by Django 6.0.6 on 2026-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0087_produitindexpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_placeholder",
                    models.CharField(
                        default="exemple : canapé, téléphone, CD-ROM...",
                        help_text="Texte affiché dans le champ de recherche de la page d'accueil avant que l'utilisateur ne commence à taper.",
                        max_length=255,
                        verbose_name="Placeholder du champ de recherche (page d'accueil)",
                    ),
                ),
                (
                    "header_search_placeholder",
                    models.CharField(
                        default="Rechercher un objet ou un déchet",
                        help_text="Texte affiché dans le champ de recherche du header avant que l'utilisateur ne commence à taper.",
                        max_length=255,
                        verbose_name="Placeholder du champ de recherche (header)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de recherche",
            },
        ),
    ]
