# Generated by Django 6.0.6 on 2026-08-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0088_search_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchsettings",
            old_name="search_placeholder",
            new_name="home_search_placeholder",
        ),
    ]
