# Generated by Django 6.0.6 on 2026-08-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0088_produit_legacy_imported_as_produit_page_and_more"),
        (
            "qfdmd",
            "0089_rename_search_placeholder_searchsettings_home_search_placeholder",
        ),
    ]

    operations = []
