# Generated by Django 6.1.1 on 2026-09-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0090_conversionimmediatepage"),
        ("qfdmd", "0091_migrate_carte_sur_mesure_to_carte"),
    ]

    operations = []
