# Generated by Django 6.1.1 on 2026-09-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0090_merge_20260825_0854"),
        ("qfdmd", "0092_merge_20260910_0833"),
    ]

    operations = []
