"""

Django settings for quefairedemesobjets project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from contextlib import suppress
from pathlib import Path
from urllib.parse import urlparse

import decouple
import dj_database_url
import sentry_sdk
from import_export.formats.base_formats import CSV, XLS, XLSX
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Assistant settings
# ------------------
ASSISTANT = {
    "MATOMO_ID": decouple.config("ASSISTANT_MATOMO_ID", default=82, cast=int),
    "POSTHOG_KEY": decouple.config(
        "ASSISTANT_POSTHOG_KEY",
        default="phc_fSfhoWDOUxZdKWty16Z3XfRiAoWd1qdJK0N0z9kQHJr",  # pragma: allowlist secret  # noqa: E501
        cast=str,
    ),
}

# Carte settings
# --------------
CARTE = {
    "MATOMO_ID": decouple.config("LVAO_MATOMO_ID", default=50, cast=int),
    "GOOGLE_SEARCH_CONSOLE": "google9dfbbc61adbe3888.html",
    "POSTHOG_KEY": decouple.config(
        "LVAO_POSTHOG_KEY",
        # Staging project by default
        default="phc_L1dG5EsBjyMTTcQqFJTAQtEugtGz6C3Tdpf1g7O09si",  # pragma: allowlist secret  # noqa: E501
        cast=str,
    ),
    "DECLARATION_ACCESSIBILITE_PAGE_ID": decouple.config(
        "CARTE_DECLARATION_ACCESSBILITE_PAGE_ID",
        default=177,
        cast=int,
    ),
}
DEFAULT_MAX_SOLUTION_DISPLAYED = decouple.config(
    "DEFAULT_MAX_SOLUTION_DISPLAYED", cast=int, default=10
)
CARTE_MAX_SOLUTION_DISPLAYED = decouple.config(
    "CARTE_MAX_SOLUTION_DISPLAYED", cast=int, default=100
)
DISTANCE_MAX = decouple.config("DISTANCE_MAX", cast=int, default=30000)

GOOGLE_MAPS_API_KEY = decouple.config("GOOGLE_MAPS_API_KEY", cast=str, default="")

NB_CORRECTION_DISPLAYED = decouple.config(
    "NB_CORRECTION_DISPLAYED", cast=int, default=100
)

# CMS settings
# ------------
CMS = {
    "BASE_URL": decouple.config(
        "CMS_BASE_URL", default="https://longuevieauxobjets.ademe.fr"
    )
}

STATS = {
    "POSTHOG_BASE_URL": decouple.config(
        "POSTHOG_API_URL",
        default="https://eu.posthog.com",
        cast=str,
    ),
    "POSTHOG_PROJECT_ID": decouple.config(
        "POSTHOG_STATS_PROJECT_ID",
        default=23277,
        cast=int,
    ),
    "POSTHOG_PERSONAL_API_KEY": decouple.config(
        "POSTHOG_PERSONAL_API_KEY",
        default="dummy_posthog_key",
        cast=str,
    ),
}

# Common settings
# --------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple.config("SECRET_KEY")
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config("DEBUG", default=False, cast=bool)
STIMULUS_DEBUG = decouple.config("STIMULUS_DEBUG", default=False, cast=bool)
POSTHOG_DEBUG = decouple.config("POSTHOG_DEBUG", default=False, cast=bool)
BYPASS_ACTEUR_READONLY_FIELDS = decouple.config(
    "BYPASS_ACTEUR_READONLY_FIELDS", default=False, cast=bool
)
BLOCK_ROBOTS = decouple.config("BLOCK_ROBOTS", default=False, cast=bool)
ENVIRONMENT = decouple.config("ENVIRONMENT", default="development", cast=str)
VERSION = decouple.config("CONTAINER_VERSION", default="version", cast=str)
APP = decouple.config("APP", default="local", cast=str)
BASE_URL = decouple.config(
    "BASE_URL",
    default="http://quefairedemesdechets.ademe.local",
    cast=str,
)
BASE_HOST = urlparse(BASE_URL).hostname
ALLOWED_HOSTS = [
    BASE_HOST,
    *decouple.config("ALLOWED_HOSTS", default="", cast=str).split(","),
]

# Configure Django to trust proxy headers based on BASE_URL scheme
if urlparse(BASE_URL).scheme == "https":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True


# Application definition
# ----------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sitemaps",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_extensions",
    "import_export",
    "widget_tweaks",
    "dsfr",
    "django.forms",
    "colorfield",
    "core",
    "stats",
    "qfdmd",
    "qfdmo",
    "infotri",
    "data",
    "adminsortable2",
    "corsheaders",
    "django_lookbook",
    "djangoql",
]


FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "qfdmd.middleware.AssistantMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "qfdmd.middleware.BetaMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "database": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "lvao_django_cache",
    },
}

X_FRAME_OPTIONS = "ALLOWALL"

if DEBUG:
    # FIXME: A CSRF error can occur locally when using HTTPS.
    # It is not clear yet what causes it, it might be http host headers
    # being wrongly set when using nginx. The current workaround impacts
    # only local development and can be considered harmless, but this
    # might be nice to remove this setting someday.
    CSRF_TRUSTED_ORIGINS = [BASE_URL]
    INSTALLED_APPS.extend(["debug_toolbar", "django_browser_reload"])
    MEDIA_ROOT = "media"
    MEDIA_URL = "/media/"
    MIDDLEWARE.extend(
        [
            "debug_toolbar.middleware.DebugToolbarMiddleware",
            "django_browser_reload.middleware.BrowserReloadMiddleware",
        ]
    )

    CORS_ALLOW_ALL_ORIGINS = DEBUG


with suppress(ModuleNotFoundError):
    from debug_toolbar.settings import CONFIG_DEFAULTS

    def show_toolbar_callback(request):
        path_is_not_excluded = not any(p in request.path for p in patterns_to_exclude)

        if request.headers.get("User-Agent") == "playwright":
            return False
        if request.headers.get("Sec-Fetch-Dest") == "iframe":
            # Hide in iframe
            return False

        return path_is_not_excluded

    patterns_to_exclude = ["/lookbook", "/cms"]
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar_callback,
        "HIDE_IN_STACKTRACES": CONFIG_DEFAULTS["HIDE_IN_STACKTRACES"] + ("sentry_sdk",),
    }

LOGLEVEL = decouple.config(
    "LOGLEVEL", default="info" if DEBUG else "error", cast=str
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"hide_staticfiles": {"()": "core.logging.SkipStaticFilter"}},
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "default": {
            # exact format is not important, this is the minimum information
            "format": "[%(asctime)s] [%(name)s] [%(levelname)s] : %(message)s",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "filters": ["hide_staticfiles"] if DEBUG else [],
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
            "level": LOGLEVEL,
        },
        "qfdmo": {
            "handlers": ["console"],
            "level": LOGLEVEL,
        },
        "data": {"handlers": ["console"], "level": LOGLEVEL},
        "qfdmd": {"handlers": ["console"], "level": LOGLEVEL},
    },
}

ROOT_URLCONF = "core.urls"


def context_processors():
    return [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
        "core.context_processors.environment",
        "core.context_processors.content",
        "core.context_processors.global_context",
        "dsfr.context_processors.site_config",
    ]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                *context_processors(),
                # Sites faciles
                "wagtail.contrib.settings.context_processors.settings",
                "wagtailmenus.context_processors.wagtailmenus",
                "sites_faciles.content_manager.context_processors.skiplinks",
                "sites_faciles.content_manager.context_processors.mega_menus",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Database
# --------
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASE_URL = decouple.config(
    "DATABASE_URL",
    default="postgis://qfdmo:qfdmo@localhost:6543/qfdmo",  # pragma: allowlist secret  # noqa: E501
)

DEFAULT_DATABASE_SETTINGS = {
    **dj_database_url.parse(DATABASE_URL),
    "ENGINE": "django.contrib.gis.db.backends.postgis",
    "OPTIONS": {"options": "-c search_path=public,warehouse"},
    # FIXME : est-ce que Django à besoin d'avoir les 2 bases de données ?
}

DB_WAREHOUSE = decouple.config(
    "DB_WAREHOUSE",
    cast=str,
    default="postgis://qfdmo:qfdmo@localhost:6543/warehouse",  # pragma: allowlist secret  # noqa: E501
)
WAREHOUSE_DATABASE_SETTINGS = {
    **dj_database_url.parse(DB_WAREHOUSE),
    "ENGINE": "django.contrib.gis.db.backends.postgis",
}

DATABASES = {
    "default": DEFAULT_DATABASE_SETTINGS,
    "warehouse": WAREHOUSE_DATABASE_SETTINGS,
}

REMOTE_WEBAPP_SERVERNAME = "webapp_server"
REMOTE_WEBAPP_SCHEMANAME = "webapp_public"
REMOTE_WAREHOUSE_SERVERNAME = "warehouse_server"
REMOTE_WAREHOUSE_SCHEMANAME = "warehouse_public"

CONN_HEALTH_CHECKS = True
CONN_MAX_AGE = decouple.config("CONN_MAX_AGE", cast=int, default=0)


# Password validation
# -------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LOGIN_URL = "admin:login"


# Internationalization
# --------------------
# https://docs.djangoproject.com/en/4.2/topics/i18n/

TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = "fr-fr"


# Static files (CSS, JavaScript, Images)
# --------------------------------------
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static" / "to_collect",
    BASE_DIR / "static" / "compiled",
]


WHITENOISE_KEEP_ONLY_HASHED_FILES = True


# Sentry
# ------
sentry_sdk.init(
    dsn=decouple.config("SENTRY_DSN", cast=str, default=""),
    integrations=[DjangoIntegration()],
    environment=ENVIRONMENT,
    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=False,
    # trace only 1% of requests to get performance statistics
    traces_sample_rate=0.01,
    # By default the SDK will try to use the SENTRY_RELEASE
    # environment variable, or infer a git commit
    # SHA as release, however you may want to set
    # something more human-readable.
    # release="qfdmo@1.0.0",
)


# Insee
# -----
INSEE_KEY = decouple.config("INSEE_KEY", cast=str, default="")
INSEE_SECRET = decouple.config("INSEE_SECRET", cast=str, default="")


SHELL_PLUS_PRINT_SQL = True

# S3 bucket settings
# ------------------
AWS_ACCESS_KEY_ID = decouple.config("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = decouple.config("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = decouple.config("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = decouple.config("AWS_S3_REGION_NAME", default="")
AWS_S3_ENDPOINT_URL = decouple.config("AWS_S3_ENDPOINT_URL", default="")

STORAGES = {
    "default": {
        "BACKEND": (
            "storages.backends.s3.S3Storage"
            if AWS_ACCESS_KEY_ID
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Import / export settings
# ------------------------
IMPORT_EXPORT_TMP_STORAGE_CLASS = "import_export.tmp_storages.MediaStorage"
IMPORT_FORMATS = [CSV, XLSX, XLS]
DJANGO_IMPORT_EXPORT_LIMIT = decouple.config(
    "DJANGO_IMPORT_EXPORT_LIMIT", cast=int, default=1000
)


# Tally form ids
# --------------
ADDRESS_SUGGESTION_FORM = decouple.config(
    "ADDRESS_SUGGESTION_FORM", default="https://tally.so/r/wzy9ZZ", cast=str
)
UPDATE_SUGGESTION_FORM = decouple.config(
    "UPDATE_SUGGESTION_FORM", default="https://tally.so/r/3xMqd9", cast=str
)

FEEDBACK_FORM = decouple.config(
    "FEEDBACK_FORM", default="https://tally.so/r/3EW88q", cast=str
)
CONTACT_FORM = decouple.config(
    "CONTACT_FORM", default="https://tally.so/r/wzYveR", cast=str
)
ASSISTANT_SURVEY_FORM = decouple.config(
    "ASSISTANT_SURVEY_FORM", default="https://tally.so/r/wvNgx0", cast=str
)

# Notion settings
# --------------
NOTION = {
    "TOKEN": decouple.config("NOTION_TOKEN", default=""),
    "CONTACT_FORM_DATABASE_ID": decouple.config(
        "NOTION_CONTACT_FORM_DATABASE_ID", default=""
    ),
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = decouple.config(
    "DATA_UPLOAD_MAX_NUMBER_FIELDS", default=10000, cast=int
)


# Wagtail settings
# ----------------
SILENCED_SYSTEM_CHECKS = ["wagtailadmin.W002"]
HOST_PROTO = decouple.config("HOST_PROTO", default="https")
WAGTAIL_SITE_NAME = "Longue vie aux objets"
WAGTAILADMIN_BASE_URL = BASE_URL
WAGTAIL_SEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
        "SEARCH_CONFIG": "wagtail_french",
    }
}

INSTALLED_APPS.extend(
    [
        # Sites faciles
        "sites_faciles",
        "sites_faciles.blog",
        "sites_faciles.content_manager",
        "sites_faciles.events",
        "wagtail.contrib.settings",
        "sites_faciles.forms",
        "wagtail_modeladmin",
        "wagtailmenus",
        "wagtailmarkdown",
        "wagtail_honeypot",
        # wagtail
        "wagtail.contrib.forms",
        "wagtail.contrib.redirects",
        "wagtail.embeds",
        "wagtail.sites",
        "wagtail.users",
        "wagtail.snippets",
        "wagtail.documents",
        "wagtail.images",
        "wagtail.search",
        "wagtail.admin",
        "wagtail.contrib.typed_table_block",
        "wagtail",
        "modelcluster",
        "taggit",
    ]
)
WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]


STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


MIDDLEWARE.extend(
    [
        "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    ]
)


# UI
# ---
LOOKBOOK = {
    "preview_base": ["previews"],
    "show_previews": decouple.config("SHOE_PREVIEWS", default=True, cast=bool),
}
