"""Constants for configuring DAG schedules"""

from dataclasses import dataclass


@dataclass(frozen=True)
class TAGS:
    ABJ: str = "ABJ"  # Fillière ABJ
    ACTEURS: str = "acteurs"
    ACTEURS: str = "acteurs"
    ADEME: str = "ADEME"
    ADRESSES: str = "adresses"
    AIRFLOW: str = "airflow"
    ALIAPUR: str = "aliapur"  # eco-organisme
    ANNAIRE_ENTREPRISE: str = "annuaire-entreprise"
    APPLY: str = "application"
    ASL: str = "ASL"  # Fillière ASL
    BAN: str = "ban"
    BATRIBOX: str = "batribox"  # eco-organisme
    CARTE: str = "carte"
    CITEO: str = "citeo"  # eco-organisme
    CLEANUP: str = "cleanup"
    CLONE: str = "clone"
    CLOSED: str = "fermés"
    CLUSTER: str = "cluster"
    CLUSTERING: str = "clustering"
    CMA: str = "cma"  # Fédération
    COMMUNE_ASSOCIEE: str = "commune associée"
    COMMUNE_DELEGUEE: str = "commune déléguée"
    COMMUNE: str = "commune"
    COMPUTE: str = "compute"
    CONTOURS_ADMINISTRATIFS: str = "contours administratifs"
    COREPILE: str = "corepile"  # eco-organisme
    CP: str = "code postal"
    CRAWL: str = "crawl"
    CYCLEVIA: str = "cyclevia"  # eco-organisme
    DATA_ADEME: str = "data.ademe.fr"  # endpoint
    DATA_POINTSAPPORT_ADEME: str = "data.pointsapport.ademe.fr"
    DB: str = "db"
    DBT: str = "dbt"
    DECHETTERIE: str = "déchetterie"
    DEPARTEMENT: str = "département"
    DEPRECATED: str = "deprecated"
    DEV_TOOLS: str = "dev tools"
    E2E: str = "e2e"
    EA: str = "EA"  # Fillière EA
    ECO_ORGANISME: str = "eco-organisme"
    ECODDS: str = "ecodds"  # eco-organisme
    ECOLOGIC: str = "ecologic"  # eco-organisme
    ECOMAISON: str = "ecomaison"  # eco-organisme
    ECOPAE: str = "ecopae"  # eco-organisme
    ECOSYSTEM: str = "ecosystem"  # eco-organisme
    EEE: str = "EEE"  # Fillière EEE
    EMPAP: str = "EMPAP"  # Fillière EMPAP
    ENRICH: str = "enrich"
    EPCI: str = "epci"
    ETABLISSEMENT: str = "etablissement"
    EXPORT: str = "export"
    FEDERATION: str = "fédération"
    INSEE: str = "insee"
    JOUET: str = "JOUET"  # Fillière Jouet
    KOUMOUL: str = "koumoul"
    LAPOSTE: str = "laposte"
    LIEUX_DITS: str = "lieux-dits"
    LOGS: str = "logs"
    LUB: str = "LUB"  # Fillière Lubrifiant
    MAINTENANCE: str = "maintenance"
    NETTOYAGE: str = "nettoyage"
    OCA: str = "OCA"  # Organisme Coordonnateur Agrée
    OCAB: str = "ocab"  # OCA
    OCAD3E: str = "ocad3e"  # OCA
    OPENDATA: str = "opendata"
    ORDRE_PHARMACIENS: str = "ordre.pharmacien.fr"  # endpoint
    PA: str = "PA"  # fillière Pile et Accumulateurs
    PCHIM: str = "PCHIM"  # Fillière PCHIM
    PHARMACIES: str = "pharmacies"  # fédération
    PMCB: str = "PMCB"  # Fillière PMCB
    PNEU: str = "PNEU"  # Fillière PNEU
    PREPARE: str = "prepare"
    PYREO: str = "pyreo"  # eco-organisme
    REFASHION: str = "refashion"  # eco-organisme
    REGION: str = "région"
    REPARACTEUR: str = "reparacteur"  # Label qualité
    RGPD: str = "rgpd"
    S3: str = "s3"
    SCALEWAY: str = "scaleway"
    SINOE: str = "sinoe"
    SIREN: str = "siren"
    SIRET: str = "siret"
    SOREN: str = "soren"  # eco-organisme
    SOURCE: str = "source"
    SQL: str = "sql"
    SUGGESTIONS: str = "suggestions"
    TEMPLATE: str = "template"
    TEST: str = "test"
    TLC: str = "TLC"  # Fillière TLC
    TOUT: str = "tout"
    UNITE_LEGALE: str = "unite-legale"
    URL: str = "url"
    VALDELIA: str = "valdelia"  # eco-organisme
    VILLES: str = "villes"
    VUE: str = "vue"
    XCOM: str = "xcom"
