version: 2

models:
  - name: marts_enrich_ae_rgpd
    description: Unités légales de l'Annuaire Entreprises (AE) préfiltrés
      | et prématchés sur la base des noms/prénoms de dirigeants dont au
      | moins 1 apparait dans le nom de nos acteurs (le modèle sera ensuite
      | utilisé par un DAG Airflow pour faire du matching plus poussé via
      | python et soumettre des suggestions)
    columns:
      - name: siren
        description: "Numéro SIREN"
        data_type: varchar(9)
        data_tests:
          - not_null
          # Our model is at unite_legale level (no repetition per establishment)
          # hence SIREN should be unique. However test failing as of 2025-03-19
          # due to duplicate SIREN in our DB which is potentially OK (i.e. multiple
          # acteur locations belonging to the same parent Acteur SIREN)
          # - unique
      - name: acteur_id
        description: Identifiant unique de l'acteur
        data_tests:
          - not_null
      - name: acteur_noms_origine
        description: Nom, nom officiel et nom commercial de l'acteur regroupés
        data_tests:
          - not_null
      - name: acteur_noms_normalises
        description: Nom, nom officiel et nom commercial de l'acteur regroupés
         | & normalisés pour réduire la taille de la table, sachant
         | qu'on fait un matching plus poussés avec python par la suite
        # Ensuring we are not matching empty strings
        data_tests:
          - not_null
      - name: acteur_commentaires
        description: Commentaires de l'acteur pour debug ET si on veut faire
         | filtering avec des paramètres de DAG
      - name: ae_dirigeants_noms_prenoms
        description: Noms & prénoms de tous les dirigeants
         | regroupés & normalisés pour réduire la taille de la table, sachant
         | qu'on fait un matching plus poussés avec python par la suite
        # If we had a match then we must have at least one director's name
        data_tests:
          - not_null

  - name: marts_enrich_acteurs_closed_replaced
    description: Etablissements de l'Annuaire Entreprises (AE) qui ont été
      | fermés et remplacés par un autre établissement
    columns:
      - name: acteur_id
        description: Identifiant unique de l'acteur
        data_tests:
          - not_null
      - name: acteur_statut
        description: Statut de l'acteur dans QFDMO
      - name: acteur_siret
        description: SIRET de l'acteur fermé
        data_tests:
          - not_null
      - name: remplacer_siret
        description: SIRET de l'établissement qui remplace l'acteur fermé
        data_tests:
          - not_null
      - name: remplacer_cohorte
        description: "Si le SIRET de remplacement appartient à la même entreprise (meme_siret) ou non (autre_siret)"
        data_tests:
          - not_null
          # - accepted_values:
          #     values: ['siret_du_meme_siren', 'siret_dun_autre_siren']
      - name: acteur_nom
        description: Nom de l'acteur fermé
      - name: remplacer_nom
        description: Nom de l'établissement qui remplace l'acteur fermé
      - name: noms_nombre_mots_commun
        description: Nombre de mots en commun entre le nom de l'acteur et celui du remplaçant
        data_type: integer
      - name: acteur_commentaires
        description: Commentaires de l'acteur pour debug
      - name: naf
        description: Code NAF de l'établissement remplaçant
      - name: ville
        description: Ville de l'établissement remplaçant
      - name: code_postal
        description: Code postal de l'établissement remplaçant
      - name: adresse
        description: Adresse de l'établissement remplaçant
      - name: replacement_priority
        description: "Priorité du remplacement (1 = meilleur match)"
        data_type: integer

  - name: marts_enrich_acteurs_closed_candidates
    description: Etablissements fermés de l'Annuaire Entreprises (AE) qui pourraient être remplacés
    columns:
      - name: siret
        description: SIRET de l'établissement fermé
        data_tests:
          - not_null
      - name: unite_est_actif
        description: Si l'unité légale est toujours active
        data_type: boolean
      - name: etab_est_actif
        description: Si l'établissement est toujours actif (toujours FALSE ici)
        data_type: boolean
        data_tests:
          - accepted_values:
              values: [false]
      - name: etab_code_postal
        description: Code postal de l'établissement fermé
      - name: etab_adresse
        description: Adresse de l'établissement fermé
      - name: etab_naf
        description: Code NAF de l'établissement fermé
      - name: acteur_id
        description: Identifiant unique de l'acteur dans QFDMO
        data_tests:
          - not_null
      - name: acteur_statut
        description: Statut de l'acteur dans QFDMO
      - name: acteur_nom
        description: Nom de l'acteur dans QFDMO
      - name: acteur_nom_normalise
        description: Nom de l'acteur normalisé pour faciliter les comparaisons
      - name: acteur_commentaires
        description: Commentaires de l'acteur pour debug

