version: 2

models:
  - name: exposure_stats_acteur_revision_siren
    description: "Acteur et correction avec un SIREN différent et une source plus récente"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: source_code
        description: "Le code de la source de l'acteur"
      - name: acteur_siren
        description: "Le SIREN de l'acteur"
      - name: revision_siren
        description: "Le SIREN de la révision"
      - name: acteur_modifie_le
        description: "La date de modification de l'acteur"
      - name: revision_modifie_le
        description: "La date de modification de la révision"
    config:
      materialized: table
      tags:
        - exposure
        - stats
        - acteurs
        - revision
        - siren

  - name: exposure_stats_acteur_revision_siret
    description: "Acteur et correction avec un SIRET différent et une source plus récente"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: source_code
        description: "Le code de la source de l'acteur"
      - name: acteur_siret
        description: "Le SIRET de l'acteur"
      - name: revision_siret
        description: "Le SIRET de la révision"
      - name: acteur_modifie_le
        description: "La date de modification de l'acteur"
      - name: revision_modifie_le
        description: "La date de modification de la révision"
    config:
      materialized: table
      tags:
        - exposure
        - stats
        - acteurs
        - revision
        - siret

  - name: exposure_stats_acteur_revision_statut
    description: "Acteurs avec une révision affichée (ACTIVE) alors que l'acteur n'est pas actif"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: source_code
        description: "Le code de la source de l'acteur"
      - name: acteur_statut
        description: "Le statut de l'acteur"
      - name: revision_statut
        description: "Le statut de la révision"
    config:
      materialized: table
      tags:
        - exposure
        - stats
        - acteurs
        - revision
        - statut
        - actif

  - name: exposure_stats_acteur_siren_siret_history
    description: "Historique du nombre et taux d'acteurs visibles avec un SIREN et un SIRET. Une ligne est ajoutée à chaque exécution de dbt."
    columns:
      - name: date_snapshot
        description: "Date de l'exécution dbt"
        data_tests:
          - not_null
          - unique
      - name: nb_total
        description: "Nombre total d'acteurs visibles"
        data_tests:
          - not_null
      - name: nb_with_siren
        description: "Nombre d'acteurs visibles avec un SIREN bien formatté (9 chiffres)"
        data_tests:
          - not_null
      - name: nb_with_siren_actif
        description: "Nombre d'acteurs visibles avec un SIREN actif (AE)"
        data_tests:
          - not_null
      - name: nb_with_siren_inactive
        description: "Nombre d'acteurs visibles avec un SIREN bien formatté (9 chiffres) mais inactif"
        data_tests:
          - not_null
      - name: nb_with_siret
        description: "Nombre d'acteurs visibles avec un SIRET bien formatté (14 chiffres)"
        data_tests:
          - not_null
      - name: nb_with_siret_actif
        description: "Nombre d'acteurs visibles avec un SIRET actif (AE)"
        data_tests:
          - not_null
      - name: nb_with_siret_inactive
        description: "Nombre d'acteurs visibles avec un SIRET bien formatté (14 chiffres) mais inactif"
        data_tests:
          - not_null
      - name: rate_with_siren
        description: "Taux d'acteurs visibles avec un SIREN bien formatté (9 chiffres)"
        data_tests:
          - not_null
      - name: rate_with_siren_actif
        description: "Taux d'acteurs visibles avec un SIREN actif (AE)"
        data_tests:
          - not_null
      - name: rate_with_siren_inactive
        description: "Taux d'acteurs visibles avec un SIREN bien formatté (9 chiffres) mais inactif"
        data_tests:
          - not_null
      - name: rate_with_siret
        description: "Taux d'acteurs visibles avec un SIRET bien formatté (14 chiffres)"
        data_tests:
          - not_null
      - name: rate_with_siret_actif
        description: "Taux d'acteurs visibles avec un SIRET actif (AE)"
        data_tests:
          - not_null
      - name: rate_with_siret_inactive
        description: "Taux d'acteurs visibles avec un SIRET bien formatté (14 chiffres) mais inactif"
        data_tests:
          - not_null
      - name: rate_siren
        description: "DEPRECATED (remplacé par rate_with_siren): Taux d'acteurs visibles avec un SIREN bien formatté (9 chiffres)"
        data_tests:
          - not_null
      - name: rate_siren_actif
        description: "DEPRECATED (remplacé par rate_with_siren_actif): Taux d'acteurs visibles avec un SIREN actif (AE)"
        data_tests:
          - not_null
      - name: rate_siren_inactive
        description: "DEPRECATED (remplacé par rate_with_siren_inactive): Taux d'acteurs visibles avec un SIREN bien formatté (9 chiffres) mais inactif"
        data_tests:
          - not_null
      - name: rate_siret
        description: "DEPRECATED (remplacé par rate_with_siret): Taux d'acteurs visibles avec un SIRET bien formatté (14 chiffres)"
        data_tests:
          - not_null
      - name: rate_siret_actif
        description: "DEPRECATED (remplacé par rate_with_siret_actif): Taux d'acteurs visibles avec un SIRET actif (AE)"
        data_tests:
          - not_null
      - name: rate_siret_inactive
        description: "DEPRECATED (remplacé par rate_with_siret_inactive): Taux d'acteurs visibles avec un SIRET bien formatté (14 chiffres) mais inactif"
        data_tests:
          - not_null
    config:
        materialized: incremental
        unique_key: date_snapshot
        incremental_strategy: delete+insert
        tags:
          - exposure
          - stats
          - acteurs
          - siren
          - siret

  - name: exposure_stats_acteur_stacked_history
    description: "Historique du nombre d'acteurs empilés. Une ligne est ajoutée à chaque exécution de dbt."
    columns:
      - name: date_snapshot
        description: "Date de l'exécution dbt"
        data_tests:
          - not_null
          - unique
      - name: nb_total
        description: "Nombre total d'acteurs visibles avec coordonnées (dénominateur)"
        data_tests:
          - not_null
      - name: nb_stacked
        description: "Nombre d'acteurs empilés"
        data_tests:
          - not_null
      - name: nb_stacked_rounded
        description: "Nombre d'acteurs empilés à 11 m près (coordonnées arrondies)"
        data_tests:
          - not_null
      - name: rate_stacked
        description: "Taux d'acteurs empilés (nb_acteurs / nb_total), entre 0 et 1"
        data_tests:
          - not_null
      - name: rate_stacked_rounded
        description: "Taux d'acteurs empilés à 11 m près (nb_acteurs_stacked / nb_total), entre 0 et 1"
        data_tests:
          - not_null
    config:
        materialized: incremental
        unique_key: date_snapshot
        incremental_strategy: delete+insert
        tags:
          - exposure
          - stats
          - acteurs
          - stacked

  - name: exposure_stats_distance_nb_acteur_by_action
    description: "Statistiques de distance et nombre de solutions par action. Calcule la moyenne de distance_m et nb_solutions_100km par action et globalement (TOUTES_ACTIONS)."
    columns:
      - name: date_snapshot
        description: "Date de l'exécution dbt"
        data_tests:
          - not_null
      - name: action_id
        description: "ID de l'action (NULL pour la ligne globale TOUTES_ACTIONS)"
      - name: action_code
        description: "Code de l'action ou 'TOUTES_ACTIONS' pour le calcul global"
        data_tests:
          - not_null
      - name: avg_distance_m
        description: "Distance moyenne en mètres vers l'acteur le plus proche"
        data_tests:
          - not_null
      - name: avg_nb_solutions_100km
        description: "Nombre moyen de solutions dans un rayon de 100km"
        data_tests:
          - not_null
      - name: nb_positions
        description: "Nombre de positions utilisées pour le calcul"
        data_tests:
          - not_null
    config:
      materialized: incremental
      unique_key: [date_snapshot, action_code]
      incremental_strategy: delete+insert
      tags:
        - exposure
        - stats
        - acteurs
        - distance
        - action