version: 2

models:
  - name: marts_acteur_no_siren_actif
    description: "Acteurs visibles sans SIREN actif (AE)"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: siren
        description: "Le SIREN de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - siren
        - actif

  - name: marts_acteur_no_siret_actif
    description: "Acteurs visibles sans SIRET actif (AE)"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: siret
        description: "Le SIRET de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - siret
        - actif

  - name: marts_acteur_revision
    description: "Acteurs avec une révision"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: nom
        description: "Le nom de l'acteur"
      - name: source_code
        description: "Le code de la source de l'acteur"
      - name: acteur_siren
        description: "Le SIREN de l'acteur"
      - name: acteur_siret
        description: "Le SIRET de l'acteur"
      - name: acteur_statut
        description: "Le statut de l'acteur"
      - name: acteur_modifie_le
        description: "La date de modification de l'acteur"
      - name: revision_siren
        description: "Le SIREN de la révision"
      - name: revision_siret
        description: "Le SIRET de la révision"
      - name: revision_statut
        description: "Le statut de la révision"
      - name: revision_modifie_le
        description: "La date de modification de la révision"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - revision
        - statut
  - name: marts_acteur_stacked
    description: "Acteurs visibles et stackés"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: latitude
        description: "La latitude de l'acteur"
      - name: longitude
        description: "La longitude de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - stacked
  - name: marts_acteur_stacked_rounded
    description: "Acteurs visibles et stackés"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
      - name: rounded_latitude
        description: "La latitude de l'acteur"
      - name: rounded_longitude
        description: "La longitude de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - stacked
        - rounded
  - name: marts_acteur_siren_actif
    description: "Acteurs visibles avec un SIREN actif (AE)"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - siren
  - name: marts_acteur_siret_actif
    description: "Acteurs visibles avec un SIRET actif (AE)"
    columns:
      - name: identifiant_unique
        description: "L'identifiant unique de l'acteur"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - acteurs
        - siret
  - name: marts_distance_first_action
    description: "Distance entre la position aléatoire et l'acteur le plus proche pour chaque action"
    columns:
      - name: longitude
        description: "La longitude"
      - name: latitude
        description: "La latitude"
      - name: action_id
        description: "L'identifiant de l'action"
      - name: acteur_id
        description: "L'identifiant de l'acteur"
      - name: acteur_latitude
        description: "La latitude de l'acteur"
      - name: acteur_longitude
        description: "La longitude de l'acteur"
      - name: distance_m
        description: "La distance en mètres"
      - name: nb_solutions_100km
        description: "Le nombre de solutions dans les 100 km"
    config:
      materialized: table
      tags:
        - stats
        - marts
        - distance
        - first_action