# Generated by Django 5.1.8 on 2025-06-18 09:15


# warehouse=# DROP SERVER qfdmo_server CASCADE;
# NOTICE:  drop cascades to user mapping for qfdmo on server qfdmo_server
# DROP SERVER
# warehouse=# CREATE SERVER qfdmo_server                                                                                                                                 FOREIGN DATA WRAPPER postgres_fdw                                                                                                                                  OPTIONS (host 'localhost', port '5432', dbname 'qfdmo');
# CREATE SERVER
# warehouse=# CREATE USER MAPPING FOR CURRENT_USER                                                                                                                       SERVER qfdmo_server                                                                                                                                                OPTIONS (user 'qfdmo', password 'qfdmo');
# CREATE USER MAPPING
# warehouse=# IMPORT FOREIGN SCHEMA public from server qfdmo_server into qfdmo_public;

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    database = "warehouse"

    dependencies = [
        ("qfdmo", "0158_alter_carteconfig_slug"),
    ]

    db_port = (
        5432
        if settings.ENVIRONMENT == "development"
        else settings.DATABASES["default"]["PORT"]
    )

    operations = [
        migrations.RunSQL(
            f"""
            CREATE EXTENSION IF NOT EXISTS postgis;
            CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
            CREATE EXTENSION IF NOT EXISTS unaccent;
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
            CREATE EXTENSION IF NOT EXISTS postgres_fdw;
            DROP SERVER IF EXISTS qfdmo_server CASCADE;
            CREATE EXTENSION IF NOT EXISTS postgres_fdw;
            CREATE SERVER qfdmo_server FOREIGN DATA WRAPPER postgres_fdw
              OPTIONS (
                host '{settings.DATABASES['default']['HOST']}',
                port '{db_port}',
                dbname '{settings.DATABASES['default']['NAME']}'
              );
            CREATE USER MAPPING FOR CURRENT_USER SERVER qfdmo_server
              OPTIONS (
                user '{settings.DATABASES['default']['USER']}',
                password '{settings.DATABASES['default']['PASSWORD']}'
              );
            CREATE SCHEMA IF NOT EXISTS foreign_qfdmo_public;
            IMPORT FOREIGN SCHEMA public FROM SERVER qfdmo_server INTO foreign_qfdmo_public;
            """,
            """
            DROP SERVER IF EXISTS qfdmo_server CASCADE;
            """,
        ),
    ]
