# Generated by Django 5.2.4 on 2025-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0160_action_rapporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="acteur_type",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seuls les types d'acteurs sélectionnés s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.acteurtype",
                verbose_name="Type(s) d'acteurs",
            ),
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seuls les labels sélectionnés s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.labelqualite",
                verbose_name="Label(s) qualité",
            ),
        ),
    ]
