# Generated by Django 5.2.4 on 2025-08-19 15:16

import django.db.models.deletion
from django.db import migrations, models

import qfdmo.models.acteur


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0166_update_objets_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="displayedacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="revisionacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="lieu_prestation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_DOMICILE", "À domicile"),
                    ("SUR_PLACE", "Sur place"),
                    ("SUR_PLACE_OU_A_DOMICILE", "Sur place ou à domicile"),
                    ("", ""),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DisplayedPerimetreADomicile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPARTEMENTAL", "Départemental"),
                            ("KILOMETRIQUE", "Kilométrique"),
                        ],
                        default="KILOMETRIQUE",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[qfdmo.models.acteur.DepartementOrNumValidator()],
                    ),
                ),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perimetre_adomicile",
                        to="qfdmo.displayedacteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Périmètre à domicile",
                "verbose_name_plural": "Périmètres à domicile",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PerimetreADomicile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPARTEMENTAL", "Départemental"),
                            ("KILOMETRIQUE", "Kilométrique"),
                        ],
                        default="KILOMETRIQUE",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[qfdmo.models.acteur.DepartementOrNumValidator()],
                    ),
                ),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perimetre_adomicile",
                        to="qfdmo.acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Périmètre à domicile",
                "verbose_name_plural": "Périmètres à domicile",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RevisionPerimetreADomicile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPARTEMENTAL", "Départemental"),
                            ("KILOMETRIQUE", "Kilométrique"),
                        ],
                        default="KILOMETRIQUE",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[qfdmo.models.acteur.DepartementOrNumValidator()],
                    ),
                ),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perimetre_adomicile",
                        to="qfdmo.revisionacteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Périmètre à domicile",
                "verbose_name_plural": "Périmètres à domicile",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VuePerimetreADomicile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPARTEMENTAL", "Départemental"),
                            ("KILOMETRIQUE", "Kilométrique"),
                        ],
                        default="KILOMETRIQUE",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[qfdmo.models.acteur.DepartementOrNumValidator()],
                    ),
                ),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perimetre_adomicile",
                        to="qfdmo.vueacteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Périmètre à domicile",
                "verbose_name_plural": "Périmètres à domicile",
                "abstract": False,
            },
        ),
    ]
