# Generated by Django 5.2.5 on 2025-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0168_alter_serviceadomicile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carteconfig",
            old_name="hide_legend",
            new_name="cacher_legende",
        ),
        migrations.RenameField(
            model_name="carteconfig",
            old_name="preview_content",
            new_name="contenu_previsualisation",
        ),
        migrations.RenameField(
            model_name="carteconfig",
            old_name="no_branding",
            new_name="supprimer_branding",
        ),
        migrations.RenameField(
            model_name="carteconfig",
            old_name="preview_title",
            new_name="titre_previsualisation",
        ),
        migrations.AddField(
            model_name="carteconfig",
            name="mode_affichage",
            field=models.CharField(
                choices=[("carte", "Carte"), ("liste", "Liste")],
                default="carte",
                help_text="Ce choix permet de définir le mode d'affichage par défaut de la carte. Le mode liste affiche une liste d'acteurs tandis qu'une carte affiche un fond de carte.",
                verbose_name="Mode d'affichage par défaut",
            ),
        ),
    ]
