# Generated by Django 5.2.5 on 2025-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0171_alter_carteconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vueacteur",
            name="enfants_liste",
            field=models.JSONField(
                default=None,
                editable=False,
                null=True,
                verbose_name="La liste des enfants de l'acteur parent",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="enfants_nombre",
            field=models.IntegerField(
                default=None,
                editable=False,
                null=True,
                verbose_name="Le nombre d'enfants de l'acteur parent",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_dans_carte",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="L'acteur est affiché dans la carte",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_dans_opendata",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="L'acteur est dans le partage opendata",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="est_parent",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="L'acteur est un parent"
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="latitude",
            field=models.FloatField(
                default=0.0,
                editable=False,
                null=True,
                verbose_name="La latitude de l'acteur",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="longitude",
            field=models.FloatField(
                default=0.0,
                editable=False,
                null=True,
                verbose_name="La longitude de l'acteur",
            ),
        ),
        migrations.AddField(
            model_name="vueacteur",
            name="revision_existe",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Une correction existe"
            ),
        ),
    ]
