# Generated by Django 5.2.5 on 2025-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0173_alter_acteur_lieu_prestation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="souscategorieobjet",
            name="reemploi_possible",
            field=models.BooleanField(
                default=True,
                help_text="Indique si la sous-catégorie est compatible avec le reemploi",
                verbose_name="Reemploi possible",
            ),
        ),
    ]
