# Generated by Django 5.2.5 on 2025-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0174_souscategorieobjet_reemploi_possible"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="direction",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seules les actions correspondantes à la direction choisie s'afficheront sur la carte\nSi le champ n'est pas renseigné il sera ignoré",
                to="qfdmo.actiondirection",
                verbose_name="Direction des actions",
            ),
        ),
    ]
