# Generated by Django 5.2.7 on 2025-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0176_merge_20250924_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteconfig",
            name="SOLUTION_TEMPORAIRE_A_SUPPRIMER_DES_QUE_POSSIBLE_parametres_url",
            field=models.CharField(
                blank=True,
                verbose_name="paramètres d'URL pour la direction / groupes d'action",
            ),
        ),
    ]
