# Generated by Django 5.2.8 on 2025-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0179_remove_carteconfig_label_carteconfig_action_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="displayedacteur",
            index=models.Index(
                fields=["statut", "acteur_type_id"], name="da_statut_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displayedpropositionservice",
            index=models.Index(
                fields=["acteur", "action"], name="dps_acteur_action_idx"
            ),
        ),
    ]
