# Generated by Django 5.2.8 on 2025-11-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0183_alter_labelqualite_options_labelqualite_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vueacteur",
            old_name="enfants_liste",
            new_name="liste_enfants",
        ),
        migrations.RenameField(
            model_name="vueacteur",
            old_name="enfants_nombre",
            new_name="nombre_enfants",
        ),
    ]
