# Generated by Django 5.2.9 on 2025-12-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0185_add_bonus_reparation_to_carte_config"),
        ("qfdmo", "0185_vueacteur_sources"),
    ]

    operations = []
