# Generated by Django 6.0.2 on 2026-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0188_carteconfig_cacher_filtre_objet_carteconfig_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="slug",
            field=models.SlugField(
                help_text="Le slug est utilisé pour générer l'url de carte, par exemple: https://quefairedemesobjets.fr/carte/<strong>cyclevia</strong><br>Le slug est utilisé pour le script avec l'attribut <code>data-slug</code>, par exemple : <br/><code>&lt;script src='https://quefairedemesdechets.ademe.fr/static/carte.js' data-slug='cyclevia'&gt;&lt;/script&gt;</code>",
                unique=True,
            ),
        ),
    ]
