# Generated by Django 6.0.4 on 2026-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0189_alter_carteconfig_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carteconfig",
            name="supprimer_branding",
            field=models.BooleanField(
                default=False,
                help_text="Supprime le logo dans l'entête de la carte. Ce mode est utilisé essentiellement pour la carte affichée dans l'assistant.",
                verbose_name="Supprimer le branding",
            ),
        ),
    ]
