# Generated by Django 6.0.4 on 2026-05-13 12:24

from django.db import migrations, models


def default_false(apps, schema_editor):
    Acteur = apps.get_model("qfdmo", "Acteur")
    Acteur.objects.filter(exclusivite_de_reprisereparation=None).update(
        exclusivite_de_reprisereparation=False
    )
    Acteur.objects.filter(uniquement_sur_rdv=None).update(uniquement_sur_rdv=False)


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0190_alter_carteconfig_supprimer_branding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                default=False, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                default=False, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="displayedacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="exclusivite_de_reprisereparation",
            field=models.BooleanField(
                default=False, verbose_name="Exclusivité de reprise/réparation"
            ),
        ),
        migrations.AlterField(
            model_name="vueacteur",
            name="uniquement_sur_rdv",
            field=models.BooleanField(default=False),
        ),
    ]
