# Generated by Django 6.0.4 on 2026-05-13 12:24

from django.db import migrations, models

BOOLEAN_FIELDS = ("exclusivite_de_reprisereparation", "uniquement_sur_rdv")
TABLES = ("qfdmo_acteur", "qfdmo_displayedacteur", "qfdmo_vueacteur")


def _alter_boolean_columns_sql(*, reverse: bool = False) -> str:
    statements: list[str] = []
    for table in TABLES:
        for column in BOOLEAN_FIELDS:
            if reverse:
                statements.extend(
                    [
                        f'ALTER TABLE "{table}" ALTER COLUMN "{column}" DROP DEFAULT;',
                        f'ALTER TABLE "{table}" ALTER COLUMN "{column}" DROP NOT NULL;',
                    ]
                )
            else:
                statements.extend(
                    [
                        f'ALTER TABLE "{table}" ALTER COLUMN "{column}" SET DEFAULT false;',
                        f'ALTER TABLE "{table}" ALTER COLUMN "{column}" SET NOT NULL;',
                    ]
                )
    return "\n".join(statements)


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0191_rebuild_remote_server_fix_port"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_alter_boolean_columns_sql(),
                    reverse_sql=_alter_boolean_columns_sql(reverse=True),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="acteur",
                    name="exclusivite_de_reprisereparation",
                    field=models.BooleanField(
                        default=False,
                        verbose_name="Exclusivité de reprise/réparation",
                    ),
                ),
                migrations.AlterField(
                    model_name="acteur",
                    name="uniquement_sur_rdv",
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name="displayedacteur",
                    name="exclusivite_de_reprisereparation",
                    field=models.BooleanField(
                        default=False,
                        verbose_name="Exclusivité de reprise/réparation",
                    ),
                ),
                migrations.AlterField(
                    model_name="displayedacteur",
                    name="uniquement_sur_rdv",
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name="vueacteur",
                    name="exclusivite_de_reprisereparation",
                    field=models.BooleanField(
                        default=False,
                        verbose_name="Exclusivité de reprise/réparation",
                    ),
                ),
                migrations.AlterField(
                    model_name="vueacteur",
                    name="uniquement_sur_rdv",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
