# Generated by Django 6.1.1 on 2026-09-13 21:18

from django.db import migrations, models

# Libellés relevés sur le Figma « DSM Assistant V2 » (nœud 24382:53).
LIBELLES_COURTS = {
    "reparer": "Réparer",
    "donner_echanger_rapporter": "Donner",
    "emprunter_preter_louer": "Prêter",
    "vendre_acheter": "Vendre",
    "trier": "Déposer",
}


def peupler(apps, schema_editor):
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")
    for code, libelle in LIBELLES_COURTS.items():
        GroupeAction.objects.filter(code=code).update(libelle_court=libelle)


def vider(apps, schema_editor):
    GroupeAction = apps.get_model("qfdmo", "GroupeAction")
    GroupeAction.objects.update(libelle_court="")


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmo", "0191_rebuild_remote_server_fix_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupeaction",
            name="libelle_court",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom du geste à l'infinitif, tel qu'affiché sur les étiquettes de l'assistant : « Réparer », « Donner ». Se distingue du libellé courant, une phrase à la première personne (« Je répare ») déduite des actions du groupe.",  # noqa: E501
                max_length=50,
                verbose_name="Libellé court",
            ),
        ),
        migrations.RunPython(peupler, vider),
    ]
