name: Setup E2E Tools
description: Install all tools needed for E2E testing (frontend, backend, GIS, optionally Playwright)

inputs:
  build-frontend:
    description: "Build frontend assets"
    required: false
    default: "false"
  install-playwright:
    description: "Install Playwright browsers"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup frontend environment
      uses: ./.github/actions/setup-frontend
      with:
        build: ${{ inputs.build-frontend }}

    - name: Setup backend environment
      uses: ./.github/actions/setup-backend
      with:
        uv-groups: "--package webapp --only-group dev"

    - name: Install GIS packages
      uses: ./.github/actions/install-gis

    - name: Setup Playwright
      if: inputs.install-playwright == 'true'
      uses: ./.github/actions/setup-playwright
