version: 2

models:
  - name: int_epci
    description: "EPCI model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_type: integer
        data_tests:
          - not_null
      - name: code
        description: "Le code de l'EPCI"
        data_type: varchar(10)
        data_tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments:
                value: 9
      - name: nom
        description: "Le nom de l'EPCI"
        data_type: varchar(255)
        data_tests:
          - not_null
    config:
      tags:
        - intermediate
        - normalisation
        - geo
        - epci
      materialized: table
      contract:
        enforced: true