version: 2

models:
  - name: marts_exhaustive_acteur
    description: "Acteur model"
    columns:
      - name: identifiant_unique
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: uuid
        description: "The uuid for this table"
        data_tests:
          - unique
          - not_null
      - name: nom
        description: "Le nom de l'acteur"
        data_tests:
          - not_null
      - name: description
        description: "La description de l'acteur"
      - name: acteur_type_id
        description: "Le type d'acteur"
      - name: adresse
        description: "L'adresse de l'acteur"
      - name: adresse_complement
        description: "L'adresse complémentaire de l'acteur"
      - name: code_postal
        description: "Le code postal de l'acteur"
      - name: ville
        description: "La ville de l'acteur"
      - name: url
        description: "L'URL de l'acteur"
      - name: email
        description: "L'email de l'acteur"
      - name: location
        description: "La localisation de l'acteur"
      - name: telephone
        description: "Le numéro de téléphone de l'acteur"
      - name: nom_commercial
        description: "Le nom commercial de l'acteur"
      - name: nom_officiel
        description: "Le nom officiel de l'acteur"
      - name: siren
        description: "Le numéro SIREN de l'acteur"
      - name: siret
        description: "Le numéro SIRET de l'acteur"
      - name: source_id
        description: "L'identifiant source de l'acteur"
      - name: identifiant_externe
        description: "L'identifiant externe de l'acteur"
      - name: naf_principal
        description: "Le code NAF principal de l'acteur"
      - name: commentaires
        description: "Les commentaires de l'acteur"
      - name: horaires_osm
        description: "Les horaires OSM de l'acteur"
      - name: horaires_description
        description: "La description des horaires de l'acteur"
      - name: public_accueilli
        description: "Le public accueilli par l'acteur"
      - name: reprise
        description: "La reprise de l'acteur"
      - name: exclusivite_de_reprisereparation
        description: "L'exclusivité de la réparation de l'acteur"
      - name: uniquement_sur_rdv
        description: "Le fait que l'acteur soit uniquement sur RDV"
      - name: consignes_dacces
        description: "Les consignes d'accès de l'acteur"
      - name: action_principale_id
        description: "L'action principale de l'acteur"
      - name: modifie_le
        description: "La date de modification de l'acteur"
      - name: parent_id
        description: "L'identifiant du parent de l'acteur"
      - name: cree_le
        description: "La date de création de l'acteur"
      - name: statut
        description: "Le statut de l'acteur"
      - name: siret_is_closed
        description: "Information si on sait que le SIRET est fermé"
      - name: revision_existe
        description: "Le fait que l'acteur est une révision"
        data_tests:
          - not_null
      - name: est_parent
        description: "Vrai si l'acteur est un parent"
        data_type: boolean
        data_tests:
          - not_null
      - name: liste_enfants
        description: "La liste des enfants de l'acteur"
        data_type: jsonb
      - name: nombre_enfants
        description: "Le nombre d'enfants de l'acteur"
        data_type: integer
      - name: est_dans_carte
        description: "Vrai si l'acteur est dans la carte"
        data_type: boolean
        data_tests:
          - not_null
      - name: est_dans_opendata
        description: "Vrai si l'acteur est dans l'opendata"
        data_type: boolean
        data_tests:
          - not_null
    config:
      materialized: table
  - name: marts_exhaustive_acteur_acteur_services
    description: "Acteur Acteur Services model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: acteurservice_id
        description: "The acteurservice_id for this table"
        data_tests:
          - not_null
    config:
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - acteurservice_id
  - name: marts_exhaustive_acteur_sources
    description: "Acteur Sources model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: source_id
        description: "The source_id for this table"
        data_tests:
          - not_null
      - name: identifiant_externe
        description: "The identifiant_externe for this table"
        data_tests:
          - not_null
    config:
      materialized: table
      tags:
        - marts
        - exhaustive
        - acteurs
        - acteur_sources
  - name: marts_exhaustive_acteur_labels
    description: "Acteur Labels model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: labelqualite_id
        description: "The labelqualite_id for this table"
        data_tests:
          - not_null
    config:
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - labelqualite_id
  - name: marts_exhaustive_propositionservice
    description: "Proposition Service model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: action_id
        description: "The action_id for this table"
        data_tests:
          - not_null
      - name: ps_id
        description: "The ps_id for this table"
      - name: rps_id
        description: "The rps_id for this table"
      - name: revision_existe
        description: "The revision_existe for this table"
    config:
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - action_id
  - name: marts_exhaustive_propositionservice_sous_categories
    description: "Proposition Service Sous Categories model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: propositionservice_id
        description: "The propositionservice_id for this table"
        data_tests:
          - not_null
      - name: souscategorieobjet_id
        description: "The souscategorieobjet_id for this table"
        data_tests:
          - not_null
    config:
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - propositionservice_id
              - souscategorieobjet_id
  - name: marts_exhaustive_perimetreadomicile
    description: "Vue sur les périmètres à domicile affichés sur la carte"
    columns:
      - name: id
        description: "L'identifiant du périmètre à domicile"
        data_tests:
          - not_null
          - unique
      - name: acteur_id
        description: "L'identifiant de l'acteur"
        data_tests:
          - not_null
      - name: type
        description: "Le type de périmètre à domicile"
        data_tests:
          - not_null
      - name: valeur
        description: "La valeur du périmètre à domicile"
        data_tests:
          - not_null
    config:
      materialized: table
      tags:
        - marts
        - exhaustive
        - acteurs
        - perimetreadomicile
  - name: marts_exhaustive_acteur_epci
    description: "Lien entre acteur et code EPCI"
    columns:

      - name: identifiant_unique
        description: "The identifiant_unique for this table"
        data_tests:
          - not_null
      - name: code_postal
        description: "The code_postal for this table"
      - name: upper_acteur_ville
        description: "The upper_acteur_ville for this table"
      - name: upper_epci_nom_commune
        description: "The upper_epci_nom_commune for this table"
      - name: code_commune_insee
        description: "The code_commune_insee for this table"
      - name: code_epci
        description: "The code_epci for this table"
      - name: nom_epci
        description: "The nom_epci for this table"
      - name: similarity_score
        description: "The similarity_score for this table"
    config:
      materialized: table
      tags:
        - marts
        - exhaustive
        - acteurs
        - epci
