name: "Setup E2E Environment"
description: "Sets up Node.js, Python, and Playwright for E2E tests"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".tool-versions"
        cache: "npm"

    - name: Install uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244
      with:
        enable-cache: true

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Setup frontend environment
      uses: ./.github/actions/setup-frontend

    - name: Frontend Assets Cache
      uses: actions/cache@v4
      id: frontend-assets-cache
      with:
        key: frontend-build-${{ hashFiles('static/**', 'package.json', 'package-lock.json', '.parcelrc', 'tailwind.config.js') }}
        path: static/compiled/*

    - name: Build assets
      shell: bash
      if: steps.frontend-assets-cache.outputs.cache-hit != 'true'
      run: npm run build
