# Generated by Django 6.1.1 on 2026-09-28 21:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Identifiant technique, ex : visiteurs_orientes",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(blank=True)),
                (
                    "target",
                    models.FloatField(
                        blank=True,
                        help_text="Objectif à atteindre sur l'année",
                        null=True,
                        verbose_name="Cible",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Saisie manuelle"),
                            ("posthog", "Insight PostHog"),
                            ("code", "Calculé par le code (stats/key_results.py)"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "posthog_insight",
                    models.CharField(
                        blank=True,
                        help_text="Seule la première série de l'insight est enregistrée, par mois.",
                        max_length=20,
                        verbose_name="Insight PostHog",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("sum_year", "Somme des valeurs de l'année en cours"),
                            ("last", "Dernière valeur"),
                        ],
                        default="last",
                        help_text="Comment le résultat courant est calculé à partir des valeurs.",
                        max_length=10,
                        verbose_name="Résultat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key result",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="KeyResultValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Premier jour de la période (mois, année)"
                    ),
                ),
                ("value", models.FloatField(verbose_name="Valeur")),
                (
                    "key_result",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stats.keyresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key_result", "date"), name="unique_key_result_date"
                    )
                ],
            },
        ),
    ]
