name: Prepare Django Database
description: Initialize Django database with migrations, static files, and seed data

inputs:
  cache-key:
    description: "Cache key for database dump"
    required: true
  local-dump-path:
    description: "Path to store local database dump"
    required: false
    default: "database-dump.pgdump"
  sample-dump-path:
    description: "Path to store the sample dump"
    required: false
    default: "sample-dump.pgdump"
  sample-db-uri:
    description: "PostgreSQL URI to dump sample database from (e.g., postgres://user:pass@host:port/dbname)" # pragma: allowlist secret
    required: false
    default: ""
  database-url:
    description: "PostgreSQL database URL for local database"
    required: false
    default: ""

outputs:
  cache-hit:
    description: Whether the database cache was hit
    value: ${{ steps.cache-db.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Check database cache
      id: cache-db
      uses: actions/cache@v5
      with:
        path: ${{ inputs.local-dump-path }}
        key: ${{ inputs.cache-key }}

    - name: Dump sample database from remote
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Dumping sample database from remote..."
        pg_dump -Fc "${{ inputs.sample-db-uri }}" -f ${{ inputs.sample-dump-path }}
        echo "Sample database dumped successfully"

    - name: Restore sample database
      if: steps.cache-db.outputs.cache-hit != 'true'
      uses: ./.github/actions/pg-restore
      with:
        database-url: ${{ inputs.database-url }}
        dump-path: ${{ inputs.sample-dump-path }}

    - name: Prepare django, migrate, collect static files
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: |
        make createcachetable
        uv run python manage.py migrate_from_sites_faciles_experiment --no-input
        make migrate

    - name: Init django admin superuser
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: make createsuperuser-example

    - name: Dump PostgreSQL database
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: pg_dump -Fc -f ${{ inputs.local-dump-path }}
