/**
 * Extraction script: DSFR typography classes → typography.js
 *
 * Reads @gouvfr/dsfr/dist/core/core.main.css and extracts the CSS properties
 * for fr-h*, fr-display--*, and fr-text--* classes (at-root, not inside @media).
 *
 * Run with: node webapp/dsfr_hacks/extract_dsfr_typography.js
 */

import { readFileSync, writeFileSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

const coreCssPath = resolve(
  __dirname,
  "../node_modules/@gouvfr/dsfr/dist/core/core.main.css",
)
const outputPath = resolve(__dirname, "typography.js")

const css = readFileSync(coreCssPath, "utf8")

// Match top-level (not inside @media) class blocks for the typography classes we care about.
// Strategy: split on "}" to get candidate blocks, then check if the selector matches.
// This avoids false positives from the @media override blocks deeper in the file.
const seen = new Set()
const typography = {}

// Match top-level rule blocks (single or multi-selector) for our typography classes.
// Pattern: one or more selectors (possibly comma-separated) followed by a { ... } block.
// We capture only blocks whose selectors are all fr-h*, fr-display--*, or fr-text--*.
const typographyClass = /fr-h[1-6]|fr-display--[a-z]+|fr-text--[a-z]+/
const blockPattern =
  /((?:\.(fr-h[1-6]|fr-display--[a-z]+|fr-text--[a-z]+),?\n?)+) \{([^}]+)\}/gm

let match
while ((match = blockPattern.exec(css)) !== null) {
  const selectorBlock = match[1].trim() // e.g. ".fr-text--xl,\n.fr-text--lead"
  const body = match[3]

  // Parse "prop: value;" lines into a JS object
  const props = {}
  for (const line of body.split("\n")) {
    const m = line.match(/^\s*([\w-]+):\s*(.+?);?\s*$/)
    if (!m) continue
    const prop = m[1]
    // Escape inner double quotes so the value is safe inside a JS double-quoted string
    const value = m[2].trim().replace(/;$/, "").replace(/"/g, '\\"')
    props[prop] = value
  }

  if (Object.keys(props).length === 0) continue

  // Apply the same props to each selector in the block
  for (const rawSelector of selectorBlock.split(",")) {
    const selector = rawSelector.trim() // e.g. ".fr-text--xl"
    const className = selector.slice(1)

    if (!typographyClass.test(className)) continue
    // Skip duplicates — first occurrence is the base (non-@media) definition
    if (seen.has(className)) continue
    seen.add(className)

    typography[selector] = props
  }
}

const entries = Object.entries(typography)
  .map(([selector, props]) => {
    const propsStr = Object.entries(props)
      .map(([p, v]) => `      "${p}": "${v}"`)
      .join(",\n")
    return `  "${selector}": {\n${propsStr}\n  }`
  })
  .join(",\n")

const output = `/**
 * AUTO-GENERATED by extract_dsfr_typography.js — DO NOT EDIT MANUALLY
 *
 * DSFR typography utilities extracted from:
 *   @gouvfr/dsfr/dist/core/core.main.css
 *
 * Used in tailwind.config.js to register fr-h*, fr-display--*, fr-text--*
 * as Tailwind utilities so responsive variants work (e.g. md:fr-h6, max-md:fr-h3).
 */

const dsfrTypography = {
${entries}
}

export default dsfrTypography
`

writeFileSync(outputPath, output, "utf8")

console.log(`✓ Extracted ${Object.keys(typography).length} typography classes`)
console.log(`✓ Written to ${outputPath}`)
