/**
 * Extraction script: DSFR semantic colors → semantic_colors.js
 *
 * Reads @gouvfr/dsfr/dist/utility/colors/colors.css and extracts:
 *   - fr-background-* classes → backgroundColors (background-color CSS vars)
 *   - fr-text-* classes → textColors (color CSS vars)
 *
 * Run with: node webapp/dsfr_hacks/extract_dsfr_semantic_colors.js
 */

import { readFileSync, writeFileSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

const colorsCssPath = resolve(
  __dirname,
  "../node_modules/@gouvfr/dsfr/dist/utility/colors/colors.css",
)
const outputPath = resolve(__dirname, "semantic_colors.js")

const css = readFileSync(colorsCssPath, "utf8")

const backgroundColors = {}
const textColors = {}

// Match blocks like:
// .fr-background-alt--blue-france {
//   background-color: var(--background-alt-blue-france) !important;
//   ...
// }
const bgPattern =
  /\.fr-(background-[a-z0-9-]+--[a-z0-9-]+)\s*\{[^}]*background-color:\s*(var\(--[a-z0-9-]+\))/g

let match
while ((match = bgPattern.exec(css)) !== null) {
  const className = match[1] // e.g. "background-alt--blue-france"
  const cssVar = match[2] // e.g. "var(--background-alt-blue-france)"
  backgroundColors[className] = cssVar
}

// Match blocks like:
// .fr-text-label--blue-france {
//   color: var(--text-label-blue-france) !important;
//   ...
// }
const textPattern =
  /\.fr-(text-[a-z0-9-]+--[a-z0-9-]+)\s*\{[^}]*color:\s*(var\(--[a-z0-9-]+\))/g

while ((match = textPattern.exec(css)) !== null) {
  const className = match[1] // e.g. "text-label--blue-france"
  const cssVar = match[2] // e.g. "var(--text-label-blue-france)"
  textColors[className] = cssVar
}

const bgEntries = Object.entries(backgroundColors)
  .map(([k, v]) => `  '${k}': '${v}'`)
  .join(",\n")

const textEntries = Object.entries(textColors)
  .map(([k, v]) => `  '${k}': '${v}'`)
  .join(",\n")

const output = `/**
 * AUTO-GENERATED by extract_dsfr_semantic_colors.js — DO NOT EDIT MANUALLY
 *
 * DSFR semantic color utilities extracted from:
 *   @gouvfr/dsfr/dist/utility/colors/colors.css
 *
 * Used in tailwind.config.js to generate:
 *   qf-bg-<key>  → background-color: <css-var>
 *   qf-text-<key> → color: <css-var>
 */

export const backgroundColors = {
${bgEntries}
}

export const textColors = {
${textEntries}
}
`

writeFileSync(outputPath, output, "utf8")

console.log(`✓ Extracted ${Object.keys(backgroundColors).length} background colors`)
console.log(`✓ Extracted ${Object.keys(textColors).length} text colors`)
console.log(`✓ Written to ${outputPath}`)
