version: 2

models:
  - name: int_acteur
    description: "Acteur model"
    columns:
      - name: identifiant_unique
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: uuid
        description: "The uuid for this table"
        data_tests:
          - unique
          - not_null
      - name: nom
        description: "Le nom de l'acteur"
        data_tests:
          - not_null
      - name: description
        description: "La description de l'acteur"
      - name: acteur_type_id
        description: "Le type d'acteur"
      - name: adresse
        description: "L'adresse de l'acteur"
      - name: adresse_complement
        description: "L'adresse complémentaire de l'acteur"
      - name: code_postal
        description: "Le code postal de l'acteur"
      - name: ville
        description: "La ville de l'acteur"
      - name: url
        description: "L'URL de l'acteur"
      - name: email
        description: "L'email de l'acteur"
      - name: location
        description: "La localisation de l'acteur"
      - name: telephone
        description: "Le numéro de téléphone de l'acteur"
      - name: nom_commercial
        description: "Le nom commercial de l'acteur"
      - name: nom_officiel
        description: "Le nom officiel de l'acteur"
      - name: siren
        description: "Le numéro SIREN de l'acteur"
      - name: siret
        description: "Le numéro SIRET de l'acteur"
      - name: source_id
        description: "L'identifiant source de l'acteur"
      - name: identifiant_externe
        description: "L'identifiant externe de l'acteur"
      - name: naf_principal
        description: "Le code NAF principal de l'acteur"
      - name: commentaires
        description: "Les commentaires de l'acteur"
      - name: horaires_osm
        description: "Les horaires OSM de l'acteur"
      - name: horaires_description
        description: "La description des horaires de l'acteur"
      - name: public_accueilli
        description: "Le public accueilli par l'acteur"
      - name: reprise
        description: "La reprise de l'acteur"
      - name: exclusivite_de_reprisereparation
        description: "L'exclusivité de la réparation de l'acteur"
      - name: uniquement_sur_rdv
        description: "Le fait que l'acteur soit uniquement sur RDV"
      - name: consignes_dacces
        description: "Les consignes d'accès de l'acteur"
      - name: action_principale_id
        description: "L'action principale de l'acteur"
      - name: modifie_le
        description: "La date de modification de l'acteur"
      - name: parent_id
        description: "L'identifiant du parent de l'acteur"
      - name: cree_le
        description: "La date de création de l'acteur"
      - name: statut
        description: "Le statut de l'acteur"
      - name: revision_existe
        description: "Le fait que l'acteur est une révision"
        data_tests:
          - not_null
      - name: siret_is_closed
        description: "Information si on sait que le SIRET est fermé"
    config:
      tags:
        - intermediate
        - acteurs
        - acteur
      materialized: table
  - name: int_acteur_acteur_services
    description: "Acteur Acteur Services model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: acteurservice_id
        description: "The acteurservice_id for this table"
        data_tests:
          - not_null
    config:
      tags:
        - intermediate
        - acteurs
        - acteur_acteur_services
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - acteurservice_id
  - name: int_acteur_labels
    description: "Acteur Labels model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: labelqualite_id
        description: "The labelqualite_id for this table"
        data_tests:
          - not_null
    config:
      tags:
        - intermediate
        - acteurs
        - acteur_labels
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - labelqualite_id
  - name: int_propositionservice
    description: "Proposition Service model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: acteur_id
        description: "The acteur_id for this table"
        data_tests:
          - not_null
      - name: action_id
        description: "The action_id for this table"
        data_tests:
          - not_null
      - name: ps_id
        description: "The ps_id for this table"
      - name: rps_id
        description: "The rps_id for this table"
      - name: revision_existe
        description: "The revision_existe for this table"
    config:
      tags:
        - intermediate
        - acteurs
        - propositionservice
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - acteur_id
              - action_id
  - name: int_propositionservice_sous_categories
    description: "Proposition Service Sous Categories model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: propositionservice_id
        description: "The propositionservice_id for this table"
        data_tests:
          - not_null
      - name: souscategorieobjet_id
        description: "The souscategorieobjet_id for this table"
        data_tests:
          - not_null
    config:
      tags:
        - intermediate
        - acteurs
        - propositionservice_sous_categories
      materialized: table
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - propositionservice_id
              - souscategorieobjet_id
  - name: int_perimetreadomicile
    description: "Perimètre à domicile model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: acteur_id
        description: "Link to the acteur"
        data_tests:
          - not_null
      - name: type
        description: "The type of the perimeter"
        data_tests:
          - not_null
      - name: valeur
        description: "The value of the perimeter (departement or km)"
        data_tests:
          - not_null
    config:
      tags:
        - intermediate
        - acteurs
        - perimetreadomicile
      materialized: table
