name: "Setup Backend Environment"
description: "Installs uv and Python dependencies with caching"

inputs:
  uv-groups:
    description: 'UV sync groups (e.g., "--group dev --group airflow" or "--only-dev")'
    required: false
    default: "--group dev"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244
      with:
        enable-cache: true

    - name: Cache Python virtual environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ hashFiles('uv.lock') }}

    - name: Install Python dependencies
      run: uv sync ${{ inputs.uv-groups }}
      shell: bash
