version: 2

models:
  - name: int_ae_unite_legale
    description: "Unités légales de l'Annuaire Entreprises (AE)"
    columns:
      - name: siren
        description: "Numéro SIREN"
        data_type: varchar(9)
        data_tests:
          - not_null
          - unique
      - name: est_actif
        description: "OUI si A = Active"
        data_type: boolean
        data_tests:
          - not_null
      - name: naf
        description: "Code NAF Rev2"
        # Test failing on 2025-03-17 due to missing data in source table
        # data_tests:
        #   - not_null
      - name: nom_commercial
        description: "Dénomination"
        # Test failing on 2025-03-17 due to missing data in source table
        # data_tests:
        #   - not_null
      - name: dirigeant_prenom1
        description: "Prénom 1 du dirigeant"
      - name: dirigeant_prenom2
        description: "Prénom 2 du dirigeant"
      - name: dirigeant_prenom3
        description: "Prénom 3 du dirigeant"
      - name: dirigeant_prenom4
        description: "Prénom 4 du dirigeant"
      - name: dirigeant_prenom_usuel
        description: "Prénom usuel du dirigeant"
      - name: dirigeant_pseudonyme
        description: "Pseudonyme du dirigeant"
      - name: dirigeant_nom
        description: "Nom du dirigeant"
      - name: dirigeant_nom_usage
        description: "Nom d'usage du dirigeant"
    config:
      materialized: table
      tags:
        - intermediate
        - ae
        - annuaire_entreprises
        - unite_legale
      indexes:
        - columns: ['siren']
          unique: true
        - columns: ['est_actif']
        - columns: ['a_dirigeant_noms_ou_prenoms_non_null']
  - name: int_ae_etablissement
    description: "Établissements de l'Annuaire Entreprises (AE)"
    columns:
      - name: siret
        description: "Numéro SIRET"
        data_type: varchar(14)
        data_tests:
          - not_null
          - unique
      - name: activite_principale
        description: "Code NAF Rev2"
      - name: nom
        description: "Nom de l'établissement"
        data_tests:
          - not_null
      - name: est_actif
        description: "OUI si A = Actif"
        data_type: boolean
        data_tests:
          - not_null
      - name: numero_voie
        description: "Numéro de voie"
      - name: complement_adresse
        description: "Complement d'adresse (ex: étage, bâtiment)"
      - name: type_voie
        description: "Type de voie (ex: rue, avenue)"
      - name: libelle_voie
        description: "Nom de la voie"
      - name: code_postal
        description: "Postal code"
      - name: libelle_commune
        description: "Nom de la ville"
      - name: adresse_normalize_string_for_match
        description: "Adresse nomalisée pour la recherche"
    config:
      materialized: table
      create_table_as: false
      tags:
        - intermediate
        - ae
        - annuaire_entreprises
        - etablissement
      indexes:
        - columns: ['siret']
          unique: true
        - columns: ['code_postal']
          type: hash
        - columns: ['adresse_normalize_string_for_match']
          type: hash
