# Generated by Django 5.1.4 on 2025-01-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_tables_suggestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestion",
            old_name="context",
            new_name="contexte",
        ),
    ]
