# Generated by Django 5.1.4 on 2025-01-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_rename_context_suggestion_contexte"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestion",
            options={
                "verbose_name": "1️⃣ Suggestion",
                "verbose_name_plural": "1️⃣ Suggestions",
            },
        ),
        migrations.AlterModelOptions(
            name="suggestioncohorte",
            options={
                "verbose_name": "📦 Cohorte",
                "verbose_name_plural": "📦 Cohortes",
            },
        ),
    ]
