# Generated by Django 5.1.4 on 2025-02-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_suggestion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestion",
            options={"verbose_name": "1️⃣ Suggestions"},
        ),
    ]
