# Generated by Django 5.1.4 on 2025-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_suggestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="metadata",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Metadata de la cohorte, données statistiques",
            ),
        ),
    ]
