# Generated by Django 5.2.5 on 2025-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_alter_suggestioncohorte_type_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestioncohorte",
            name="type_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRAWL_URLS", "🔗 URLs scannées"),
                    ("ENRICH_ACTEURS_CLOSED", "🚪 Acteurs fermés"),
                    ("ENRICH_ACTEURS_RGPD", "🕵 Anonymisation RGPD"),
                    ("ENRICH_ACTEURS_VILLES_TYPO", "🏙️ Acteurs villes typographiques"),
                    ("ENRICH_ACTEURS_VILLES_NEW", "🏙️ Acteurs villes nouvelles"),
                    (
                        "ENRICH_ACTEURS_CP_TYPO",
                        "🏙️ Acteurs codes postaux non conformes",
                    ),
                    (
                        "ENRICH_REVISION_ACTEURS_CP_TYPO",
                        "🏙️ Revision acteurs codes postaux non conformes",
                    ),
                    ("CLUSTERING", "regroupement/déduplication des acteurs"),
                    ("SOURCE_AJOUT", "ingestion de source de données - nouveau acteur"),
                    (
                        "SOURCE_MODIFICATION",
                        "ingestion de source de données - modification d'acteur existant",
                    ),
                    ("SOURCE_SUPRESSION", "ingestion de source de données"),
                ],
                max_length=50,
            ),
        ),
    ]
