# Generated by Django 5.2.8 on 2025-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_alter_suggestion_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="parametres",
            field=models.JSONField(blank=True, db_default="", default=dict),
        ),
    ]
