# Generated by Django 5.2.9 on 2025-12-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_alter_bancache_modifie_le_alter_suggestion_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Finie en erreur"),
                    ("SUCCES", "✅ Finie avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestiongroupe",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Finie en erreur"),
                    ("SUCCES", "✅ Finie avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVALIDER", "🟠 À valider"),
                    ("REJETEE", "🔴 Rejetée"),
                    ("ATRAITER", "⏳ À traiter"),
                    ("ENCOURS", "⏳ En cours de traitement"),
                    ("ERREUR", "❌ Finie en erreur"),
                    ("SUCCES", "✅ Finie avec succès"),
                ],
                default="AVALIDER",
                max_length=50,
            ),
        ),
    ]
