# Generated by Django 5.2.9 on 2025-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_alter_suggestion_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="parametres",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
