# Generated by Django 5.2.9 on 2026-01-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_alter_suggestionunitaire_parametres"),
        ("qfdmo", "0187_alter_acteur_identifiant_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestiongroupe",
            name="acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_groupes",
                to="qfdmo.acteur",
            ),
        ),
        migrations.AlterField(
            model_name="suggestiongroupe",
            name="revision_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_groupes",
                to="qfdmo.revisionacteur",
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_unitaires",
                to="qfdmo.acteur",
            ),
        ),
        migrations.AlterField(
            model_name="suggestionunitaire",
            name="revision_acteur",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_unitaires",
                to="qfdmo.revisionacteur",
            ),
        ),
    ]
