# Generated by Django 6.0.2 on 2026-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_suggestiongroupe_parent_revision_acteur_and_more"),
        ("qfdmo", "0189_alter_carteconfig_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="suggestionunitaire",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revision_acteur_id__isnull", True),
                    ("suggestion_modele", "RevisionActeur"),
                    _negated=True,
                ),
                name="data_su_revision_acteur_if_modele_revision_acteur",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestionunitaire",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_revision_acteur_id__isnull", True),
                    ("suggestion_modele", "ParentRevisionActeur"),
                    _negated=True,
                ),
                name="data_su_parent_revision_acteur_if_modele_parent_revision_acteur",
            ),
        ),
    ]
