# Generated by Django 6.0.6 on 2026-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0022_suggestionunitaire_data_su_revision_acteur_if_modele_revision_acteur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestioncohorte",
            name="type_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRAWL_URLS", "🔗 URLs scannées"),
                    ("ENRICH_ACTEURS_CLOSED", "🚪 Acteurs fermés"),
                    ("ENRICH_ACTEURS_RGPD", "🕵 Anonymisation RGPD"),
                    ("ENRICH_ACTEURS_VILLES_TYPO", "🏙️ Acteurs villes typographiques"),
                    ("ENRICH_ACTEURS_VILLES_NEW", "🏙️ Acteurs villes nouvelles"),
                    (
                        "ENRICH_ACTEURS_CP_TYPO",
                        "🏙️ Acteurs codes postaux non conformes",
                    ),
                    (
                        "ENRICH_REVISION_ACTEURS_CP_TYPO",
                        "🏙️ Revision acteurs codes postaux non conformes",
                    ),
                    (
                        "ENRICH_ACTEURS_SIRET",
                        "🏢 Acteurs SIRET proposé depuis le SIREN connu",
                    ),
                    (
                        "ENRICH_ACTEURS_SIREN",
                        "🏢 Acteurs SIREN proposé depuis le SIRET connu",
                    ),
                    ("CLUSTERING", "regroupement/déduplication des acteurs"),
                    ("SOURCE_AJOUT", "ingestion de source de données - nouveau acteur"),
                    (
                        "SOURCE_MODIFICATION",
                        "ingestion de source de données - modification d'acteur existant",
                    ),
                    ("SOURCE_SUPRESSION", "ingestion de source de données"),
                ],
                max_length=50,
            ),
        ),
    ]
