# Generated by Django 6.1.1 on 2026-10-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_alter_suggestioncohorte_type_action"),
        ("qfdmo", "0191_rebuild_remote_server_fix_port"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestiongroupe",
            name="decision_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de la décision"
            ),
        ),
        migrations.AddField(
            model_name="suggestiongroupe",
            name="decision_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Décision prise par",
            ),
        ),
        migrations.AddField(
            model_name="suggestionunitaire",
            name="decision_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de la décision"
            ),
        ),
        migrations.AddField(
            model_name="suggestionunitaire",
            name="decision_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Décision prise par",
            ),
        ),
        migrations.AlterField(
            model_name="suggestionlog",
            name="niveau_de_log",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                default="WARNING",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="suggestiongroupe",
            index=models.Index(
                fields=["suggestion_cohorte", "statut", "id"],
                name="data_sg_cohorte_statut_id",
            ),
        ),
    ]
