# Generated by Django 5.2.9 on 2026-02-02 11:31

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=255)),
                (
                    "search_variants",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Variantes de recherche séparées par des virgules ou des retours à la ligne",
                        verbose_name="Variantes de recherche",
                    ),
                ),
                (
                    "legacy",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si ce terme de recherche provient d'un modèle legacy",
                        verbose_name="Legacy",
                    ),
                ),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                ("linked_object_id", models.PositiveIntegerField()),
                (
                    "parent_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms_as_parent",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terme de recherche",
                "verbose_name_plural": "Termes de recherche",
                "indexes": [
                    models.Index(
                        fields=["linked_content_type", "linked_object_id"],
                        name="search_sear_linked__f9e0b7_idx",
                    ),
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="search_sear_parent__012106_idx",
                    ),
                ],
                "unique_together": {("linked_content_type", "linked_object_id")},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
