# Generated by Django 5.2.9 on 2026-02-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchterm",
            options={
                "verbose_name": "Terme de recherche",
                "verbose_name_plural": "Termes de recherche",
            },
        ),
    ]
