# Generated by Django 5.2.9 on 2026-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("search", "0002_rename_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="searchterm",
            name="search_sear_linked__a1b2c3_idx",
        ),
        migrations.AddField(
            model_name="searchterm",
            name="search_variants",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Variantes de recherche séparées par des virgules ou des retours à la ligne",
                verbose_name="Variantes de recherche",
            ),
        ),
        migrations.AddIndex(
            model_name="searchterm",
            index=models.Index(
                fields=["linked_content_type", "linked_object_id"],
                name="search_sear_linked__f9e0b7_idx",
            ),
        ),
    ]
