# Generated by Django 5.2.9 on 2026-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_remove_searchterm_search_sear_linked__a1b2c3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="Indique si ce terme de recherche provient d'un modèle legacy",
                verbose_name="Legacy",
            ),
        ),
    ]
