# Shorthands to make writing tests shorter

from cluster.tasks.business_logic.cluster_acteurs_parents_choose_new import (
    REASON_ALREADY_POINT_TO_PARENT,
    REASON_NO_PARENT_CREATE_ONE,
    REASON_ONE_PARENT_KEPT,
    REASON_PARENT_TO_DELETE,
    REASON_PARENTS_KEEP_MOST_CHILDREN,
    REASON_POINT_TO_NEW_PARENT,
)

REASON_CREATE = REASON_NO_PARENT_CREATE_ONE
REASON_KEEP_ONLY = REASON_ONE_PARENT_KEPT
REASON_KEEP_MOST = REASON_PARENTS_KEEP_MOST_CHILDREN
REASON_NOTHING = REASON_ALREADY_POINT_TO_PARENT
REASON_POINT = REASON_POINT_TO_NEW_PARENT
REASON_DELETE = REASON_PARENT_TO_DELETE
