# Generated by Django 5.0.4 on 2024-07-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qfdmo", "0075_alter_dagrun_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qfdmo.souscategorieobjet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
            },
        ),
    ]
