# Generated by Django 5.0.4 on 2024-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produit",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.RemoveField(
            model_name="produit",
            name="sous_categories",
        ),
        migrations.AlterField(
            model_name="produit",
            name="titre",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
