# Generated by Django 5.0.4 on 2024-07-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0002_alter_produit_options_remove_produit_sous_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produit",
            options={"verbose_name": "Produit"},
        ),
    ]
