# Generated by Django 5.1.1 on 2024-11-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0006_lien"),
    ]

    operations = [
        migrations.CreateModel(
            name="Synonyme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, unique=True, help_text="Nom du produit"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonymes",
                        to="qfdmd.produit",
                    ),
                ),
            ],
        ),
    ]
