# Generated by Django 5.1.1 on 2024-11-20 14:43

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0008_synonyme_slug"),
    ]

    operations = [
        TrigramExtension(),
    ]
