# Generated by Django 5.1.1 on 2024-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("qfdmd", "0015_remove_produit_picto_synonyme_picto"),
        ("qfdmd", "0016_alter_produit_comment_les_eviter"),
        ("qfdmd", "0017_synonyme_pin_on_homepage"),
        ("qfdmd", "0018_produit_qu_est_ce_que_j_en_fais_bon_etat_and_more"),
        ("qfdmd", "0019_synonyme_meta_description_and_more"),
        ("qfdmd", "0020_alter_synonyme_meta_description_alter_synonyme_picto_and_more"),
        ("qfdmd", "0021_alter_synonyme_picto"),
    ]

    dependencies = [
        ("qfdmd", "0014_alter_suggestion_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="picto",
        ),
        migrations.AlterField(
            model_name="produit",
            name="comment_les_eviter",
            field=models.TextField(
                blank=True, help_text="Comment consommer responsable ?"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais_bon_etat",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - Bon état"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais_mauvais_etat",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - Mauvais état"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - ANCIEN CHAMP."
            ),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="meta_description",
            field=models.TextField(
                blank=True,
                verbose_name="Description lue et affichée par les moteurs de recherche.",
            ),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="pin_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Si un pictogramme est renseigné pour ce synonyme, celui-ci s'affichera en page d'accueil. À noter : seuls les 30 premiers synonymes avec la case cochée s'afficheront.",
                verbose_name="Épingler en page d'accueil",
            ),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="picto",
            field=models.FileField(
                blank=True,
                help_text="Ce pictogramme est affiché en page d'accueil s'il est renseigné et si la case ci-dessous est cochée.",
                null=True,
                upload_to="pictos",
            ),
        ),
    ]
