# Generated by Django 5.1.1 on 2024-12-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0014_alter_suggestion_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="picto",
        ),
        migrations.AddField(
            model_name="synonyme",
            name="picto",
            field=models.FileField(blank=True, null=True, upload_to="pictos"),
        ),
    ]
