# Generated by Django 5.1.1 on 2024-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0015_produitpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="liens",
            field=models.ManyToManyField(to="qfdmd.lien"),
        ),
    ]
