# Generated by Django 5.1.1 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0015_remove_produit_picto_synonyme_picto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="comment_les_eviter",
            field=models.TextField(
                blank=True, help_text="Comment consommer responsable ?"
            ),
        ),
    ]
