# Generated by Django 5.1.1 on 2024-11-26 13:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0016_produitpage_liens"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementReutilisable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Utilisé uniquement pour retrouver l'élément dans l'administration"
                    ),
                ),
                ("content", wagtail.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="produitpage",
            name="liens",
        ),
        migrations.AddField(
            model_name="produitpage",
            name="genre",
            field=models.CharField(
                choices=[("m", "Masculin"), ("f", "Féminin"), ("n", "Neutre")],
                default="n",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="infotri",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="nombre",
            field=models.CharField(
                choices=[("s", "Singuler"), ("p", "Pluriel")], default="s"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="qdti_bon_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="qdti_mauvais_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="qqjef_bon_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="qqjef_mauvais_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="synonyme",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmd.synonyme",
            ),
        ),
    ]
