# Generated by Django 5.1.1 on 2024-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0017_synonyme_pin_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais_bon_etat",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - Bon état"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais_mauvais_etat",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - Mauvais état"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - ANCIEN CHAMP"
            ),
        ),
    ]
