# Generated by Django 5.1.1 on 2024-11-26 13:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0017_elementreutilisable_remove_produitpage_liens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="qdti_bon_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                verbose_name="Bon état",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="qdti_mauvais_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte riche"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("gestes", 3)]],
                        {"label": "Carte", "max_num": 1},
                    ),
                },
                verbose_name="Mauvais état",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="qqjef_bon_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                verbose_name="Bon état",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="qqjef_mauvais_etat",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                verbose_name="Mauvais état",
            ),
        ),
    ]
