# Generated by Django 5.1.1 on 2024-11-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0018_alter_produitpage_qdti_bon_etat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elementreutilisable",
            old_name="content",
            new_name="contenu",
        ),
        migrations.RenameField(
            model_name="elementreutilisable",
            old_name="title",
            new_name="titre",
        ),
    ]
