# Generated by Django 5.1.1 on 2024-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0018_produit_qu_est_ce_que_j_en_fais_bon_etat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonyme",
            name="meta_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produit",
            name="qu_est_ce_que_j_en_fais",
            field=models.TextField(
                blank=True, help_text="Qu'est-ce que j'en fais ? - ANCIEN CHAMP."
            ),
        ),
    ]
