# Generated by Django 5.1.1 on 2024-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0019_synonyme_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonyme",
            name="meta_description",
            field=models.TextField(
                blank=True,
                verbose_name="Description lue et affichée par les moteurs de recherche.",
            ),
        ),
        migrations.AlterField(
            model_name="synonyme",
            name="picto",
            field=models.FileField(
                blank=True,
                help_text="Ce pictogramme est affiché en page d'accueil s'il est renseigné et si la case ci-dessous est cochée",
                null=True,
                upload_to="pictos",
            ),
        ),
        migrations.AlterField(
            model_name="synonyme",
            name="pin_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Si un pictogramme est renseigné pour ce synonyme, celui-ci s'affichera en page d'accueil. À noter : seuls les 30 premiers synonymes avec la case cochée s'afficheront.",
                verbose_name="Épingler en page d'accueil",
            ),
        ),
    ]
