# Generated by Django 5.1.1 on 2024-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0020_alter_synonyme_meta_description_alter_synonyme_picto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonyme",
            name="picto",
            field=models.FileField(
                blank=True,
                help_text="Ce pictogramme est affiché en page d'accueil s'il est renseigné et si la case ci-dessous est cochée.",
                null=True,
                upload_to="pictos",
            ),
        ),
    ]
