# Generated by Django 5.1.1 on 2024-11-26 14:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0020_alter_synonyme_options_produitpage_ccr"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="ccr",
            field=wagtail.fields.StreamField(
                [
                    ("element_reutilisable", 0),
                    ("rich_text", 1),
                    ("heading", 2),
                    ("carte", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.elementreutilisable",),
                        {},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("reparer", "Reparer"),
                                ("donner", "Donner"),
                                ("preter", "Prêter"),
                                ("acheter", "Acheter"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("gestes", 3)]], {}),
                },
                verbose_name="Comment consommer responsable",
            ),
        ),
    ]
