# Generated by Django 5.1.1 on 2024-11-26 15:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0021_produitindexpage_alter_produitpage_ccr"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("heading", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                },
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="synonyme",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qfdmd.synonyme",
            ),
        ),
    ]
