# Generated by Django 5.1.1 on 2025-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0022_synonyme_comment_les_eviter_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lien",
            options={"ordering": ("poids",)},
        ),
        migrations.RemoveField(
            model_name="lien",
            name="produits",
        ),
        migrations.AddField(
            model_name="lien",
            name="poids",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(unique=True, verbose_name="Libellé"),
        ),
    ]
