# Generated by Django 5.1.1 on 2025-01-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0022_synonyme_comment_les_eviter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(unique=True, verbose_name="Libellé"),
        ),
        migrations.CreateModel(
            name="ProduitLien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(default=0)),
                (
                    "lien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qfdmd.lien"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qfdmd.produit"
                    ),
                ),
            ],
            options={
                "ordering": ("weight",),
                "unique_together": {("produit", "lien")},
            },
        ),
    ]
