# Generated by Django 5.1.1 on 2025-01-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0023_alter_produit_nom_produitlien"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lien",
            name="produits",
        ),
    ]
