# Generated by Django 5.1.1 on 2025-01-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0023_lien_poids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lien",
            options={"ordering": ("poids",)},
        ),
    ]
