# Generated by Django 5.1.1 on 2025-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0024_alter_lien_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lien",
            name="produits",
        ),
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(unique=True, verbose_name="Libellé"),
        ),
    ]
