# Generated by Django 5.1.1 on 2025-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0024_remove_lien_produits"),
    ]

    operations = [
        migrations.AddField(
            model_name="lien",
            name="produits",
            field=models.ManyToManyField(
                help_text="Produits associés",
                related_name="liens",
                through="qfdmd.ProduitLien",
                to="qfdmd.produit",
            ),
        ),
    ]
