# Generated by Django 5.1.1 on 2025-01-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0025_lien_produits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produitlien",
            options={"ordering": ("poids",)},
        ),
        migrations.RenameField(
            model_name="produitlien",
            old_name="weight",
            new_name="poids",
        ),
    ]
