# Generated by Django 5.1.4 on 2025-01-09 19:34

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0026_produitlien_lien_produits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lien",
            options={"ordering": ("titre_du_lien",)},
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={"ordering": ("-modifie_le",)},
        ),
        migrations.AlterModelOptions(
            name="synonyme",
            options={"ordering": ("-modifie_le",)},
        ),
        migrations.AddField(
            model_name="produit",
            name="modifie_le",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AddField(
            model_name="synonyme",
            name="modifie_le",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
