# Generated by Django 5.1.4 on 2025-01-09 16:09

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("qfdmd", "0027_produit_modifie_le"),
        ("qfdmd", "0028_alter_produit_options_alter_synonyme_options_and_more"),
    ]

    dependencies = [
        ("qfdmd", "0026_produitlien_lien_produits"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="modifie_le",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={"ordering": ("-modifie_le",)},
        ),
        migrations.AlterModelOptions(
            name="synonyme",
            options={"ordering": ("-modifie_le",)},
        ),
        migrations.AddField(
            model_name="synonyme",
            name="modifie_le",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
