# Generated by Django 5.1.1 on 2025-01-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0024_alter_lien_options"),
        ("qfdmd", "0026_alter_produitlien_options_and_more"),
    ]

    operations = []
