# Generated by Django 5.1.4 on 2025-01-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0027_alter_lien_options_alter_produit_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lien",
            name="poids",
        ),
    ]
