# Generated by Django 5.1.4 on 2025-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("qfdmd", "0028_cmspage"), ("qfdmd", "0029_alter_cmspage_id")]

    dependencies = [
        ("qfdmd", "0027_alter_lien_options_alter_produit_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Ce champ est le seul contribuable.<br>Il correspond à l'ID de la page Wagtail.<br>Tous les autres champs seront automatiquement contribués à l'enregistrementde la page dans l'administration Django.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.JSONField()),
                ("search_description", models.CharField()),
                ("seo_title", models.CharField()),
                ("title", models.CharField()),
                ("slug", models.CharField()),
            ],
        ),
    ]
