# Generated by Django 5.1.4 on 2025-01-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmd",
            "0027_produit_modifie_le_squashed_0028_alter_produit_options_alter_synonyme_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lien",
            options={"ordering": ("titre_du_lien",)},
        ),
    ]
