# Generated by Django 5.1.4 on 2025-01-14 13:05

from django.db import migrations, models


def import_cms_pages(apps, schema_editor):
    CMSPage = apps.get_model("qfdmd", "CMSPage")
    ids = [223, 221, 226, 222, 230]
    for index, id in enumerate(ids):
        page, created = CMSPage.objects.update_or_create(
            id=id, defaults={"poids": index}
        )
        # Ensure the fields are populated
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0028_remove_lien_poids"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Ce champ est le seul contribuable.<br>Il correspond à l'ID de la page Wagtail.<br>Tous les autres champs seront automatiquement contribués à l'enregistrementde la page dans l'administration Django.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.JSONField(default=dict)),
                ("search_description", models.CharField(default="")),
                ("seo_title", models.CharField(default="")),
                ("title", models.CharField(default="")),
                ("slug", models.CharField(default="")),
                ("poids", models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(import_cms_pages, migrations.RunPython.noop),
    ]
