# Generated by Django 5.1.4 on 2025-01-14 12:08

from django.db import migrations, models


def import_cms_pages(apps, schema_editor):
    CMSPage = apps.get_model("qfdmd", "CMSPage")
    ids = [223, 221, 226, 222, 230]
    for index, id in enumerate(ids):
        CMSPage.objects.update_or_create(id=id, defaults={"poids": index})


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0028_cmspage_squashed_0029_alter_cmspage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmspage",
            name="poids",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="body",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="search_description",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="seo_title",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="slug",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="title",
            field=models.CharField(default=""),
        ),
        migrations.RunPython(import_cms_pages, migrations.RunPython.noop),
    ]
