# Generated by Django 5.1.4 on 2025-01-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0028_remove_lien_poids"),
        ("qfdmd", "0030_cmspage_poids_alter_cmspage_body_and_more"),
    ]

    operations = []
