# Generated by Django 5.1.4 on 2025-01-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmd",
            "0029_alter_produit_filieres_rep_and_more_squashed_0030_alter_produitlien_poids",
        ),
        ("qfdmd", "0029_cmspage"),
    ]

    operations = []
