# Generated by Django 5.1.4 on 2025-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0031_merge_20250114_1728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="poids",
            field=models.IntegerField(
                default=0,
                help_text="Ce champ détermine la position d'un élément dans la liste affichée.<br>Les éléments avec un poids plus élevé apparaissent plus bas dans la liste.<br>Les éléments avec un poids plus faible apparaissent plus haut.",
            ),
        ),
    ]
