# Generated by Django 5.1.6 on 2025-03-04 08:17

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0032_alter_cmspage_poids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synonyme",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=255, populate_from=["nom"]
            ),
        ),
    ]
