# Generated by Django 5.1.7 on 2025-03-18 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("qfdmd", "0034_synonyme_infotri"),
        ("qfdmd", "0035_remove_synonyme_infotri_produit_infotri"),
    ]

    dependencies = [
        ("qfdmd", "0033_alter_synonyme_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="infotri",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
            ),
        ),
    ]
