# Generated by Django 5.1.7 on 2025-03-18 13:23

from django.db import migrations


def create_footer_assistant_menu(apps, schema_editor):
    FlatMenu = apps.get_model("wagtailmenus", "FlatMenu")
    Site = apps.get_model("wagtailcore", "Site")
    FlatMenu.objects.get_or_create(
        site_id=Site.objects.first().id,
        title="Menu pied de page de l'assistant",
        handle="footer_assistant",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0033_alter_synonyme_slug"),
    ]

    operations = [
        migrations.RunPython(create_footer_assistant_menu, migrations.RunPython.noop),
    ]
