# Generated by Django 5.1.7 on 2025-03-17 13:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0033_alter_synonyme_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonyme",
            name="infotri",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
                default=dict,
            ),
            preserve_default=False,
        ),
    ]
