# Generated by Django 5.1.7 on 2025-03-18 14:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0034_synonyme_infotri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synonyme",
            name="infotri",
        ),
        migrations.AddField(
            model_name="produit",
            name="infotri",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
            ),
        ),
    ]
