# Generated by Django 5.1.8 on 2025-06-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmd",
            "0034_synonyme_infotri_squashed_0035_remove_synonyme_infotri_produit_infotri",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CMSPage",
        ),
    ]
