# Generated by Django 5.1.8 on 2025-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0036_delete_cmspage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.AutoField(
                help_text="Correspond à l'identifiant ID défini dans les données <i>Que Faire</i>.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
