# Generated by Django 5.1.8 on 2025-05-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0036_synonymepage_produitpage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="produitpage",
            options={"verbose_name": "Produit"},
        ),
        migrations.AlterModelOptions(
            name="synonymepage",
            options={"verbose_name": "Synonyme de recherche"},
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="produit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produit_page",
                to="qfdmd.produit",
            ),
        ),
    ]
