# Generated by Django 5.1.8 on 2025-06-17 14:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0037_cmspage_produitpage_produitindexpage_reusablecontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="tabs",
            field=wagtail.fields.StreamField(
                [("tab", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte libre"}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {
                            "label": "Contenu réutilisable",
                            "template": "blocks/reusable.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("reusable", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
