# Generated by Django 5.1.8 on 2025-05-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0037_produitindexpage_alter_produitpage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="produit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produit_page",
                to="qfdmd.produit",
            ),
        ),
    ]
