# Generated by Django 5.1.8 on 2025-05-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0038_alter_produitpage_produit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyPage",
            fields=[
                (
                    "produitpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="qfdmd.produitpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Famille",
            },
            bases=("qfdmd.produitpage",),
        ),
        migrations.AlterModelOptions(
            name="produitindexpage",
            options={"verbose_name": "Index des familles & produits"},
        ),
    ]
