# Generated by Django 5.1.8 on 2025-06-18 08:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0038_produitpage_tabs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="consigne",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("reusable", 1), ("produit", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte libre"}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {
                            "label": "Contenu réutilisable",
                            "template": "blocks/reusable.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Bon état", "bon_etat"),
                                ("Mauvais état", "mauvais_etat"),
                            ]
                        },
                    ),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.produit",),
                        {"label": "produit"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("champ", 2), ("produit", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="tabs",
            field=wagtail.fields.StreamField(
                [("tab", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte libre"}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {
                            "label": "Contenu réutilisable",
                            "template": "blocks/reusable.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Bon état", "bon_etat"),
                                ("Mauvais état", "mauvais_etat"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.produit",),
                        {"label": "produit"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("champ", 3), ("produit", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("reusable", 2), ("produit", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 6)]],
                        {},
                    ),
                },
            ),
        ),
    ]
