# Generated by Django 5.1.8 on 2025-05-20 13:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0039_familypage_alter_produitindexpage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReusableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("content", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Contenu réutilisable",
            },
        ),
        migrations.AddField(
            model_name="produitpage",
            name="synonyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyme_in_produit_page",
                to="qfdmd.produit",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produit_in_produit_page",
                to="qfdmd.produit",
            ),
        ),
    ]
