# Generated by Django 5.1.8 on 2025-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0039_alter_produitpage_consigne_alter_produitpage_tabs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="gender",
            field=models.CharField(
                choices=[("m", "Masculin"), ("f", "Féminin")], verbose_name="Genre"
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="number",
            field=models.IntegerField(
                choices=[(1, "singulier"), (2, "pluriel")], verbose_name="Nombre"
            ),
        ),
    ]
