# Generated by Django 5.1.8 on 2025-06-23 09:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0040_alter_produitpage_gender_alter_produitpage_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpage",
            name="consigne",
        ),
        migrations.RemoveField(
            model_name="produitpage",
            name="tabs",
        ),
        migrations.AddField(
            model_name="produitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("tabs", 139)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Rich text"}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                                ("h6", "Heading 6"),
                                ("p", "Paragraph"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 3.",
                            "label": "Heading level",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Alternative text (textual description of the image)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-content-media--sm", "Small"),
                                ("", "Medium"),
                                ("fr-content-media--lg", "Large"),
                            ],
                            "label": "Witdh",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-32x9", "32x9"),
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-3x2", "3x2"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                                ("fr-ratio-3x4", "3x4"),
                                ("fr-ratio-2x3", "2x3"),
                            ],
                            "label": "Image ratio",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Caption", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 3),
                                ("image", 4),
                                ("alt", 5),
                                ("width", 6),
                                ("image_ratio", 7),
                                ("caption", 8),
                                ("url", 9),
                            ]
                        ],
                        {"label": "Image"},
                    ),
                    11: ("wagtail.images.blocks.ImageBlock", [], {"label": "Image"}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Side where the image is displayed",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3/12"), ("5", "5/12"), ("6", "6/12")],
                            "label": "Image width",
                        },
                    ),
                    14: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link label", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "No icon"),
                                (
                                    "fr-icon-arrow-right-line fr-link--icon-right",
                                    "Icon on the right side",
                                ),
                                (
                                    "fr-icon-arrow-right-line fr-link--icon-left",
                                    "Icon on the left side",
                                ),
                            ],
                            "help_text": "Only used for internal links.",
                            "label": "Icon",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-link--sm", "Small"),
                                ("", "Medium"),
                                ("fr-link--lg", "Large"),
                            ],
                            "label": "Size",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("icon", 18),
                                ("size", 19),
                            ]
                        ],
                        {
                            "help_text": "The link is shown at the bottom of the text block, with an arrow",
                            "label": "Link",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link label (obsolete)",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Internal link (obsolete)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link URL (obsolete)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 11),
                                ("image_side", 12),
                                ("image_ratio", 13),
                                ("text", 1),
                                ("link", 20),
                                ("link_label", 21),
                                ("page", 22),
                                ("link_url", 23),
                            ]
                        ],
                        {"label": "Image and text"},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Message title", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Message text", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("error", "Error"),
                                ("success", "Success"),
                                ("info", "Information"),
                                ("warning", "Warning"),
                            ],
                            "label": "Message type",
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                                ("h6", "Heading 6"),
                                ("p", "Paragraph"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 3.",
                            "label": "Heading level",
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 25),
                                ("description", 26),
                                ("level", 27),
                                ("heading_tag", 28),
                            ]
                        ],
                        {"label": "Alert message"},
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Rich text", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                (
                                    "fr-btn fr-btn--tertiary-no-outline",
                                    "Tertiary without border",
                                ),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    32: (
                        "sites_faciles.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn--icon-left", "Left"),
                                ("fr-btn--icon-right", "Right"),
                            ],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("button_type", 31),
                                ("icon_class", 32),
                                ("icon_side", 33),
                            ]
                        ],
                        {"label": "Button"},
                    ),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 34)]],
                        {
                            "help_text": "Please use only one primary button.\n                        If you use icons, use them on all buttons and align them on the same side.",
                            "label": "Buttons",
                        },
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [[("buttons", 35)]],
                        {
                            "label": "Call-to-action buttons",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Call to action label  (obsolete)",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Link (obsolete)",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 30),
                                ("cta_buttons", 36),
                                ("cta_label", 37),
                                ("cta_url", 38),
                            ]
                        ],
                        {"label": "Text and call to action"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Video title", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use embed format, with a version that doesn't require a consent banner if available. (e.g. : https://www.youtube-nocookie.com/embed/gLzXOViPX-0) For Youtube, use Embed video and check Enable privacy-enhanced mode.",
                            "label": "Video URL",
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                            ],
                            "label": "Video ratio",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Transcription",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcription content", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("content", 44)]],
                        {"label": "Transcription", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 40),
                                ("caption", 8),
                                ("url", 41),
                                ("width", 6),
                                ("video_ratio", 42),
                                ("transcription", 45),
                            ]
                        ],
                        {"label": "Video"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("content", 44)]],
                        {"label": "Transcription"},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Badge label", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", [("new", "New"), ("grey", "Grey")]),
                                (
                                    "System colors",
                                    [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                ),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "label": "Badge color",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Hide badge icon", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 48), ("color", 49), ("hide_icon", 50)]],
                        {"label": "Badge"},
                    ),
                    52: (
                        "wagtail.blocks.StreamBlock",
                        [[("badge", 51)]],
                        {"label": "Badge list"},
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Small tag", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green-tilleul-verveine", "Tilleul verveine"),
                                ("green-bourgeon", "Bourgeon"),
                                ("green-emeraude", "Émeraude"),
                                ("green-menthe", "Menthe"),
                                ("green-archipel", "Archipel"),
                                ("blue-ecume", "Écume"),
                                ("blue-cumulus", "Cumulus"),
                                ("purple-glycine", "Glycine"),
                                ("pink-macaron", "Macaron"),
                                ("pink-tuile", "Tuile"),
                                ("yellow-tournesol", "Tournesol"),
                                ("yellow-moutarde", "Moutarde"),
                                ("orange-terre-battue", "Terre battue"),
                                ("brown-cafe-creme", "Café crème"),
                                ("brown-caramel", "Caramel"),
                                ("brown-opera", "Opéra"),
                                ("beige-gris-galet", "Gris galet"),
                            ],
                            "help_text": "Only for clickable tags",
                            "label": "Tag color",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 14), ("document", 15), ("external_url", 16)]],
                        {"required": False},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("is_small", 53),
                                ("color", 54),
                                ("icon_class", 32),
                                ("link", 55),
                            ]
                        ],
                        {"label": "Tag"},
                    ),
                    57: (
                        "wagtail.blocks.StreamBlock",
                        [[("tag", 56)]],
                        {"label": "Tag list"},
                    ),
                    58: ("wagtail.blocks.RichTextBlock", (), {"label": "Content"}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 58)]],
                        {"label": "Accordion", "max_num": 15, "min_num": 1},
                    ),
                    60: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 0), ("accordion", 59)]],
                        {"group": "DSFR components", "label": "Accordions"},
                    ),
                    61: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("button_type", 31),
                                ("icon_class", 32),
                                ("icon_side", 33),
                            ]
                        ],
                        {"label": "Button", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green-tilleul-verveine", "Tilleul verveine"),
                                ("green-bourgeon", "Bourgeon"),
                                ("green-emeraude", "Émeraude"),
                                ("green-menthe", "Menthe"),
                                ("green-archipel", "Archipel"),
                                ("blue-ecume", "Écume"),
                                ("blue-cumulus", "Cumulus"),
                                ("purple-glycine", "Glycine"),
                                ("pink-macaron", "Macaron"),
                                ("pink-tuile", "Tuile"),
                                ("yellow-tournesol", "Tournesol"),
                                ("yellow-moutarde", "Moutarde"),
                                ("orange-terre-battue", "Terre battue"),
                                ("brown-cafe-creme", "Café crème"),
                                ("brown-caramel", "Caramel"),
                                ("brown-opera", "Opéra"),
                                ("beige-gris-galet", "Gris galet"),
                            ],
                            "label": "Color",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 28),
                                ("icon_class", 32),
                                ("text", 61),
                                ("button", 62),
                                ("color", 63),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Callout"},
                    ),
                    65: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                        },
                    ),
                    66: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-text--sm", "Small"),
                                ("", "Medium"),
                                ("fr-text--lg", "Large"),
                            ],
                            "label": "Size",
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 65), ("color", 63), ("size", 66)]],
                        {"group": "DSFR components", "label": "Highlight"},
                    ),
                    68: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    69: ("wagtail.blocks.CharBlock", (), {"label": "Quote"}),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author name", "required": False},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author title", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 68),
                                ("quote", 69),
                                ("author_name", 70),
                                ("author_title", 71),
                                ("color", 63),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Quote"},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("icon", 18),
                                ("size", 19),
                            ]
                        ],
                        {"label": "Single link"},
                    ),
                    74: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Prefer SVG files.",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 14), ("document", 15), ("external_url", 16)]],
                        {"label": "Link", "required": False},
                    ),
                    77: ("wagtail.blocks.StreamBlock", [[("badge", 51)]], {}),
                    78: ("wagtail.blocks.StreamBlock", [[("tag", 56)]], {}),
                    79: (
                        "wagtail.blocks.StreamBlock",
                        [[("badges", 77), ("tags", 78)]],
                        {
                            "label": "Top detail: badges or tags",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If the tile links to a downloadable document, the values are pre-filled.",
                            "label": "Detail text",
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Small tile", "required": False},
                    ),
                    82: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile with grey background", "required": False},
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile without background", "required": False},
                    ),
                    84: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile without border", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile with a shadow", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Horizontal tile", "required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("heading_tag", 28),
                                ("description", 74),
                                ("image", 75),
                                ("link", 76),
                                ("top_detail_badges_tags", 79),
                                ("detail_text", 80),
                                ("is_small", 81),
                                ("grey_background", 82),
                                ("no_background", 83),
                                ("no_border", 84),
                                ("shadow", 85),
                                ("is_horizontal", 86),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Tile"},
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 2.",
                            "label": "Heading level",
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Blog",
                            "page_type": ["sites_faciles_blog.BlogIndexPage"],
                        },
                    ),
                    90: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Number of entries",
                            "max_value": 8,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_faciles_blog.Category",),
                        {"label": "Filter by category", "required": False},
                    ),
                    92: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_faciles_content_manager.Tag",),
                        {"label": "Filter by tag", "required": False},
                    ),
                    93: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_faciles_blog.Person",),
                        {"label": "Filter by author", "required": False},
                    ),
                    94: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_faciles_blog.Organization",),
                        {
                            "help_text": "The source is the organization of the post author",
                            "label": "Filter by source",
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Show filters", "required": False},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 88),
                                ("blog", 89),
                                ("entries_count", 90),
                                ("category_filter", 91),
                                ("tag_filter", 92),
                                ("author_filter", 93),
                                ("source_filter", 94),
                                ("show_filters", 95),
                            ]
                        ],
                        {"group": "Website structure", "label": "Blog recent entries"},
                    ),
                    97: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Event calendar",
                            "page_type": ["sites_faciles_events.EventsIndexPage"],
                        },
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 88),
                                ("index_page", 97),
                                ("entries_count", 90),
                                ("category_filter", 91),
                                ("tag_filter", 92),
                                ("author_filter", 93),
                                ("source_filter", 94),
                                ("show_filters", 95),
                            ]
                        ],
                        {
                            "group": "Website structure",
                            "label": "Event calendar recent entries",
                        },
                    ),
                    99: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Number of steps", "max_value": 8, "min_value": 1},
                    ),
                    100: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Current step", "max_value": 8, "min_value": 1},
                    ),
                    101: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Detail", "required": False},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("detail", 101)]],
                        {"label": "Step"},
                    ),
                    103: (
                        "wagtail.blocks.StreamBlock",
                        [[("step", 102)]],
                        {"label": "Steps"},
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("total", 99),
                                ("current", 100),
                                ("steps", 103),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Stepper"},
                    ),
                    105: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"group": "Expert syntax", "label": "Markdown"},
                    ),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessibility: The title should describe, in a clear and concise manner, the embedded content.",
                            "label": "Title",
                        },
                    ),
                    107: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Example for Tally: https://tally.so/embed/w2jMRa",
                            "label": "URL of the iframe",
                        },
                    ),
                    108: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Height (in pixels)"},
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For example: \"allow='geolocation'\".",
                            "label": "Parameters",
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 106),
                                ("url", 107),
                                ("height", 108),
                                ("parameters", 109),
                            ]
                        ],
                        {"group": "Expert syntax", "label": "Iframe"},
                    ),
                    111: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "group": "Expert syntax",
                            "help_text": "Warning: Use HTML block with caution. Malicious code can compromise the security of the site.",
                            "readonly": True,
                        },
                    ),
                    112: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Top margin",
                            "max_value": 15,
                            "min_value": 0,
                        },
                    ),
                    113: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Bottom margin",
                            "max_value": 15,
                            "min_value": 0,
                        },
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [[("top_margin", 112), ("bottom_margin", 113)]],
                        {"group": "Page structure", "label": "Separator"},
                    ),
                    115: (
                        "wagtail.blocks.StreamBlock",
                        [[("badge", 51)]],
                        {
                            "help_text": "Only used if the card has an image.",
                            "label": "Image area badge",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    116: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "group": "target",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link (obsolete)",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "group": "target",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "or Document (obsolete)",
                            "required": False,
                        },
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Top detail: text", "required": False},
                    ),
                    119: (
                        "sites_faciles.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Top detail: icon", "required": False},
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Incompatible with the bottom call-to-action.",
                            "label": "Bottom detail: text",
                            "required": False,
                        },
                    ),
                    121: (
                        "sites_faciles.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Bottom detail: icon", "required": False},
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    123: ("wagtail.blocks.StreamBlock", [[("link", 122)]], {}),
                    124: (
                        "wagtail.blocks.StreamBlock",
                        [[("links", 123), ("buttons", 35)]],
                        {
                            "help_text": "Incompatible with the bottom detail text.",
                            "label": "Bottom call-to-action: links or buttons",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    125: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card with grey background", "required": False},
                    ),
                    126: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card without background", "required": False},
                    ),
                    127: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card without border", "required": False},
                    ),
                    128: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card with a shadow", "required": False},
                    ),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("heading_tag", 28),
                                ("description", 61),
                                ("image", 68),
                                ("image_ratio", 7),
                                ("image_badge", 115),
                                ("link", 76),
                                ("url", 116),
                                ("document", 117),
                                ("top_detail_text", 118),
                                ("top_detail_icon", 119),
                                ("top_detail_badges_tags", 79),
                                ("bottom_detail_text", 120),
                                ("bottom_detail_icon", 121),
                                ("call_to_action", 124),
                                ("grey_background", 125),
                                ("no_background", 126),
                                ("no_border", 127),
                                ("shadow", 128),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Vertical card"},
                    ),
                    130: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_faciles_blog.Person",),
                        {
                            "help_text": "Optional, all values can be manually specified or overriden below",
                            "label": "Person",
                            "required": False,
                        },
                    ),
                    131: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": False},
                    ),
                    132: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Role", "max_length": 255, "required": False},
                    ),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Organization", "max_length": 255, "required": False},
                    ),
                    134: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Contact info", "max_length": 500, "required": False},
                    ),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [[("tag", 56)]],
                        {"label": "Tags", "required": False},
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("contact", 130),
                                ("link", 76),
                                ("heading_tag", 3),
                                ("name", 131),
                                ("role", 132),
                                ("organization", 133),
                                ("contact_info", 134),
                                ("image", 68),
                                ("tags", 135),
                            ]
                        ],
                        {"group": "Extra components", "label": "Contact card"},
                    ),
                    137: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 10),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 57),
                                ("accordions", 60),
                                ("callout", 64),
                                ("highlight", 67),
                                ("quote", 72),
                                ("link", 73),
                                ("tile", 87),
                                ("blog_recent_entries", 96),
                                ("events_recent_entries", 98),
                                ("stepper", 104),
                                ("markdown", 105),
                                ("iframe", 110),
                                ("html", 111),
                                ("separator", 114),
                                ("card", 129),
                                ("contact_card", 136),
                            ]
                        ],
                        {"label": "Content"},
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 137)]],
                        {"label": "Tab", "max_num": 15, "min_num": 1},
                    ),
                    139: (
                        "wagtail.blocks.StreamBlock",
                        [[("tabs", 138)]],
                        {"group": "DSFR components", "label": "Tabs"},
                    ),
                },
            ),
        ),
    ]
