# Generated by Django 5.1.8 on 2025-05-20 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0040_reusablecontent_produitpage_synonyme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produit_in_produit_page",
                to="qfdmd.produit",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="synonyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synonyme_in_produit_page",
                to="qfdmd.produit",
            ),
        ),
    ]
