# Generated by Django 5.1.8 on 2025-05-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0041_alter_produitpage_produit_alter_produitpage_synonyme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reusablecontent",
            options={
                "verbose_name": "Contenu réutilisable",
                "verbose_name_plural": "Contenus réutilisable",
            },
        ),
        migrations.AlterModelOptions(
            name="synonymepage",
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
        ),
    ]
