# Generated by Django 5.2.3 on 2025-07-03 22:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0042_merge_20250703_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("reusable", 0),
                    ("paragraph", 1),
                    ("image", 10),
                    ("imageandtext", 24),
                    ("alert", 29),
                    ("text_cta", 39),
                    ("video", 46),
                    ("transcription", 47),
                    ("badges_list", 52),
                    ("tags_list", 58),
                    ("link", 59),
                    ("accordions", 62),
                    ("callout", 66),
                    ("highlight", 69),
                    ("quote", 74),
                    ("stepper", 80),
                    ("card", 100),
                    ("tile", 110),
                    ("tabs", 144),
                    ("markdown", 123),
                    ("iframe", 128),
                    ("html", 129),
                    ("separator", 132),
                    ("multicolumns", 153),
                    ("item_grid", 156),
                    ("fullwidthbackground", 158),
                    ("fullwidthbackgroundwithsidemenu", 165),
                    ("subpageslist", 166),
                    ("blog_recent_entries", 120),
                    ("events_recent_entries", 122),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {
                            "label": "Contenu réutilisable",
                            "template": "blocks/reusable.html",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Rich text"}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                                ("h6", "Heading 6"),
                                ("p", "Paragraph"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 3.",
                            "label": "Heading level",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Alternative text (textual description of the image)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-content-media--sm", "Small"),
                                ("", "Medium"),
                                ("fr-content-media--lg", "Large"),
                            ],
                            "label": "Witdh",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-32x9", "32x9"),
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-3x2", "3x2"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                                ("fr-ratio-3x4", "3x4"),
                                ("fr-ratio-2x3", "2x3"),
                            ],
                            "label": "Image ratio",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Caption", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 3),
                                ("image", 4),
                                ("alt", 5),
                                ("width", 6),
                                ("image_ratio", 7),
                                ("caption", 8),
                                ("url", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.images.blocks.ImageBlock", [], {"label": "Image"}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Side where the image is displayed",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3/12"), ("5", "5/12"), ("6", "6/12")],
                            "label": "Image width",
                        },
                    ),
                    14: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link label", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "No icon"),
                                (
                                    "fr-icon-arrow-right-line fr-link--icon-right",
                                    "Icon on the right side",
                                ),
                                (
                                    "fr-icon-arrow-right-line fr-link--icon-left",
                                    "Icon on the left side",
                                ),
                            ],
                            "help_text": "Only used for internal links.",
                            "label": "Icon",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-link--sm", "Small"),
                                ("", "Medium"),
                                ("fr-link--lg", "Large"),
                            ],
                            "label": "Size",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("icon", 18),
                                ("size", 19),
                            ]
                        ],
                        {
                            "help_text": "The link is shown at the bottom of the text block, with an arrow",
                            "label": "Link",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link label (obsolete)",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Internal link (obsolete)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "group": "obsolete",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link URL (obsolete)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 11),
                                ("image_side", 12),
                                ("image_ratio", 13),
                                ("text", 1),
                                ("link", 20),
                                ("link_label", 21),
                                ("page", 22),
                                ("link_url", 23),
                            ]
                        ],
                        {"label": "Image and text"},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Message title", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Message text", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("error", "Error"),
                                ("success", "Success"),
                                ("info", "Information"),
                                ("warning", "Warning"),
                            ],
                            "label": "Message type",
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                                ("h6", "Heading 6"),
                                ("p", "Paragraph"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 3.",
                            "label": "Heading level",
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 25),
                                ("description", 26),
                                ("level", 27),
                                ("heading_tag", 28),
                            ]
                        ],
                        {"label": "Alert message"},
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Rich text", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                (
                                    "fr-btn fr-btn--tertiary-no-outline",
                                    "Tertiary without border",
                                ),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    32: (
                        "sites_conformes.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn--icon-left", "Left"),
                                ("fr-btn--icon-right", "Right"),
                            ],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("button_type", 31),
                                ("icon_class", 32),
                                ("icon_side", 33),
                            ]
                        ],
                        {"label": "Button"},
                    ),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 34)]],
                        {
                            "help_text": "Please use only one primary button.\n                        If you use icons, use them on all buttons and align them on the same side.",
                            "label": "Buttons",
                        },
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [[("buttons", 35)]],
                        {
                            "label": "Call-to-action buttons",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Call to action label  (obsolete)",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the CTA buttons above.",
                            "label": "Link (obsolete)",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 30),
                                ("cta_buttons", 36),
                                ("cta_label", 37),
                                ("cta_url", 38),
                            ]
                        ],
                        {"label": "Text and call to action"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Video title", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use embed format, with a version that doesn't require a consent banner if available. (e.g. : https://www.youtube-nocookie.com/embed/gLzXOViPX-0) For Youtube, use Embed video and check Enable privacy-enhanced mode.",
                            "label": "Video URL",
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                            ],
                            "label": "Video ratio",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Transcription",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Transcription content", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("content", 44)]],
                        {"label": "Transcription", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 40),
                                ("caption", 8),
                                ("url", 41),
                                ("width", 6),
                                ("video_ratio", 42),
                                ("transcription", 45),
                            ]
                        ],
                        {"label": "Video"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("content", 44)]],
                        {"label": "Transcription"},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Badge label", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", [("new", "New"), ("grey", "Grey")]),
                                (
                                    "System colors",
                                    [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                ),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "label": "Badge color",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Hide badge icon", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 48), ("color", 49), ("hide_icon", 50)]],
                        {"label": "Badge"},
                    ),
                    52: (
                        "wagtail.blocks.StreamBlock",
                        [[("badge", 51)]],
                        {"label": "Badge list"},
                    ),
                    53: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Small tag", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green-tilleul-verveine", "Tilleul verveine"),
                                ("green-bourgeon", "Bourgeon"),
                                ("green-emeraude", "Émeraude"),
                                ("green-menthe", "Menthe"),
                                ("green-archipel", "Archipel"),
                                ("blue-ecume", "Écume"),
                                ("blue-cumulus", "Cumulus"),
                                ("purple-glycine", "Glycine"),
                                ("pink-macaron", "Macaron"),
                                ("pink-tuile", "Tuile"),
                                ("yellow-tournesol", "Tournesol"),
                                ("yellow-moutarde", "Moutarde"),
                                ("orange-terre-battue", "Terre battue"),
                                ("brown-cafe-creme", "Café crème"),
                                ("brown-caramel", "Caramel"),
                                ("brown-opera", "Opéra"),
                                ("beige-gris-galet", "Gris galet"),
                            ],
                            "help_text": "Only for clickable tags",
                            "label": "Tag color",
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 14), ("document", 15), ("external_url", 16)]],
                        {"required": False},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 53),
                                ("is_small", 54),
                                ("color", 55),
                                ("icon_class", 32),
                                ("link", 56),
                            ]
                        ],
                        {"label": "Tag"},
                    ),
                    58: (
                        "wagtail.blocks.StreamBlock",
                        [[("tag", 57)]],
                        {"label": "Tag list"},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("icon", 18),
                                ("size", 19),
                            ]
                        ],
                        {"label": "Single link"},
                    ),
                    60: ("wagtail.blocks.RichTextBlock", (), {"label": "Content"}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("content", 60)]],
                        {"label": "Accordion", "max_num": 15, "min_num": 1},
                    ),
                    62: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 53), ("accordion", 61)]],
                        {"group": "DSFR components", "label": "Accordions"},
                    ),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                                ("button_type", 31),
                                ("icon_class", 32),
                                ("icon_side", 33),
                            ]
                        ],
                        {"label": "Button", "required": False},
                    ),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green-tilleul-verveine", "Tilleul verveine"),
                                ("green-bourgeon", "Bourgeon"),
                                ("green-emeraude", "Émeraude"),
                                ("green-menthe", "Menthe"),
                                ("green-archipel", "Archipel"),
                                ("blue-ecume", "Écume"),
                                ("blue-cumulus", "Cumulus"),
                                ("purple-glycine", "Glycine"),
                                ("pink-macaron", "Macaron"),
                                ("pink-tuile", "Tuile"),
                                ("yellow-tournesol", "Tournesol"),
                                ("yellow-moutarde", "Moutarde"),
                                ("orange-terre-battue", "Terre battue"),
                                ("brown-cafe-creme", "Café crème"),
                                ("brown-caramel", "Caramel"),
                                ("brown-opera", "Opéra"),
                                ("beige-gris-galet", "Gris galet"),
                            ],
                            "label": "Color",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 28),
                                ("icon_class", 32),
                                ("text", 63),
                                ("button", 64),
                                ("color", 65),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Callout"},
                    ),
                    67: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                        },
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-text--sm", "Small"),
                                ("", "Medium"),
                                ("fr-text--lg", "Large"),
                            ],
                            "label": "Size",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 67), ("color", 65), ("size", 68)]],
                        {"group": "DSFR components", "label": "Highlight"},
                    ),
                    70: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    71: ("wagtail.blocks.CharBlock", (), {"label": "Quote"}),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author name", "required": False},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Author title", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 70),
                                ("quote", 71),
                                ("author_name", 72),
                                ("author_title", 73),
                                ("color", 65),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Quote"},
                    ),
                    75: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Number of steps", "max_value": 8, "min_value": 1},
                    ),
                    76: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Current step", "max_value": 8, "min_value": 1},
                    ),
                    77: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Detail", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("detail", 77)]],
                        {"label": "Step"},
                    ),
                    79: (
                        "wagtail.blocks.StreamBlock",
                        [[("step", 78)]],
                        {"label": "Steps"},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 53),
                                ("total", 75),
                                ("current", 76),
                                ("steps", 79),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Stepper"},
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-card--horizontal-tier", "1/3"),
                                ("fr-card--horizontal-half", "50/50"),
                            ],
                            "label": "Image ratio",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.StreamBlock",
                        [[("badge", 51)]],
                        {
                            "help_text": "Only used if the card has an image.",
                            "label": "Image area badge",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 14), ("document", 15), ("external_url", 16)]],
                        {"label": "Link", "required": False},
                    ),
                    84: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "group": "target",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "Link (obsolete)",
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "group": "target",
                            "help_text": "This field is obsolete and will be removed in the near future. Please replace with the Link field above.",
                            "label": "or Document (obsolete)",
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Top detail: text", "required": False},
                    ),
                    87: (
                        "sites_conformes.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Top detail: icon", "required": False},
                    ),
                    88: ("wagtail.blocks.StreamBlock", [[("badge", 51)]], {}),
                    89: ("wagtail.blocks.StreamBlock", [[("tag", 57)]], {}),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [[("badges", 88), ("tags", 89)]],
                        {
                            "label": "Top detail: badges or tags",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Incompatible with the bottom call-to-action. If the card links to a downloadable document, the values are pre-filled.",
                            "label": "Bottom detail: text",
                            "required": False,
                        },
                    ),
                    92: (
                        "sites_conformes.content_manager.blocks.IconPickerBlock",
                        (),
                        {"label": "Bottom detail: icon", "required": False},
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 14),
                                ("document", 15),
                                ("external_url", 16),
                                ("text", 17),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    94: ("wagtail.blocks.StreamBlock", [[("link", 93)]], {}),
                    95: (
                        "wagtail.blocks.StreamBlock",
                        [[("links", 94), ("buttons", 35)]],
                        {
                            "help_text": "Incompatible with the bottom detail text.",
                            "label": "Bottom call-to-action: links or buttons",
                            "max_num": 1,
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card with grey background", "required": False},
                    ),
                    97: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card without background", "required": False},
                    ),
                    98: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card without border", "required": False},
                    ),
                    99: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Card with a shadow", "required": False},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 53),
                                ("heading_tag", 28),
                                ("description", 63),
                                ("image", 70),
                                ("image_ratio", 81),
                                ("image_badge", 82),
                                ("link", 83),
                                ("url", 84),
                                ("document", 85),
                                ("top_detail_text", 86),
                                ("top_detail_icon", 87),
                                ("top_detail_badges_tags", 90),
                                ("bottom_detail_text", 91),
                                ("bottom_detail_icon", 92),
                                ("call_to_action", 95),
                                ("grey_background", 96),
                                ("no_background", 97),
                                ("no_border", 98),
                                ("shadow", 99),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Horizontal card"},
                    ),
                    101: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "label": "Content",
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Prefer SVG files.",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If the tile links to a downloadable document, the values are pre-filled.",
                            "label": "Detail text",
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Small tile", "required": False},
                    ),
                    105: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile with grey background", "required": False},
                    ),
                    106: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile without background", "required": False},
                    ),
                    107: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile without border", "required": False},
                    ),
                    108: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Tile with a shadow", "required": False},
                    ),
                    109: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Horizontal tile", "required": False},
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 53),
                                ("heading_tag", 28),
                                ("description", 101),
                                ("image", 102),
                                ("link", 83),
                                ("top_detail_badges_tags", 90),
                                ("detail_text", 103),
                                ("is_small", 104),
                                ("grey_background", 105),
                                ("no_background", 106),
                                ("no_border", 107),
                                ("shadow", 108),
                                ("is_horizontal", 109),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Tile"},
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 3),
                                ("image", 4),
                                ("alt", 5),
                                ("width", 6),
                                ("image_ratio", 7),
                                ("caption", 8),
                                ("url", 9),
                            ]
                        ],
                        {"label": "Image"},
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 2.",
                            "label": "Heading level",
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Blog",
                            "page_type": ["sites_conformes_blog.BlogIndexPage"],
                        },
                    ),
                    114: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Number of entries",
                            "max_value": 8,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    115: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_conformes_blog.Category",),
                        {"label": "Filter by category", "required": False},
                    ),
                    116: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_conformes_content_manager.Tag",),
                        {"label": "Filter by tag", "required": False},
                    ),
                    117: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_conformes_blog.Person",),
                        {"label": "Filter by author", "required": False},
                    ),
                    118: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_conformes_blog.Organization",),
                        {
                            "help_text": "The source is the organization of the post author",
                            "label": "Filter by source",
                            "required": False,
                        },
                    ),
                    119: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Show filters", "required": False},
                    ),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 112),
                                ("blog", 113),
                                ("entries_count", 114),
                                ("category_filter", 115),
                                ("tag_filter", 116),
                                ("author_filter", 117),
                                ("source_filter", 118),
                                ("show_filters", 119),
                            ]
                        ],
                        {"group": "Website structure", "label": "Blog recent entries"},
                    ),
                    121: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Event calendar",
                            "page_type": ["sites_conformes_events.EventsIndexPage"],
                        },
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("heading_tag", 112),
                                ("index_page", 121),
                                ("entries_count", 114),
                                ("category_filter", 115),
                                ("tag_filter", 116),
                                ("author_filter", 117),
                                ("source_filter", 118),
                                ("show_filters", 119),
                            ]
                        ],
                        {
                            "group": "Website structure",
                            "label": "Event calendar recent entries",
                        },
                    ),
                    123: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"group": "Expert syntax", "label": "Markdown"},
                    ),
                    124: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accessibility: The title should describe, in a clear and concise manner, the embedded content.",
                            "label": "Title",
                        },
                    ),
                    125: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Example for Tally: https://tally.so/embed/w2jMRa",
                            "label": "URL of the iframe",
                        },
                    ),
                    126: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"label": "Height (in pixels)"},
                    ),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For example: \"allow='geolocation'\".",
                            "label": "Parameters",
                            "required": False,
                        },
                    ),
                    128: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 124),
                                ("url", 125),
                                ("height", 126),
                                ("parameters", 127),
                            ]
                        ],
                        {"group": "Expert syntax", "label": "Iframe"},
                    ),
                    129: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "group": "Expert syntax",
                            "help_text": "Warning: Use HTML block with caution. Malicious code can compromise the security of the site.",
                            "readonly": True,
                        },
                    ),
                    130: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Top margin",
                            "max_value": 15,
                            "min_value": 0,
                        },
                    ),
                    131: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "label": "Bottom margin",
                            "max_value": 15,
                            "min_value": 0,
                        },
                    ),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [[("top_margin", 130), ("bottom_margin", 131)]],
                        {"group": "Page structure", "label": "Separator"},
                    ),
                    133: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Incompatible with the bottom call-to-action.",
                            "label": "Bottom detail: text",
                            "required": False,
                        },
                    ),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 53),
                                ("heading_tag", 28),
                                ("description", 63),
                                ("image", 70),
                                ("image_ratio", 7),
                                ("image_badge", 82),
                                ("link", 83),
                                ("url", 84),
                                ("document", 85),
                                ("top_detail_text", 86),
                                ("top_detail_icon", 87),
                                ("top_detail_badges_tags", 90),
                                ("bottom_detail_text", 133),
                                ("bottom_detail_icon", 92),
                                ("call_to_action", 95),
                                ("grey_background", 96),
                                ("no_background", 97),
                                ("no_border", 98),
                                ("shadow", 99),
                            ]
                        ],
                        {"group": "DSFR components", "label": "Vertical card"},
                    ),
                    135: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sites_conformes_blog.Person",),
                        {
                            "help_text": "Optional, all values can be manually specified or overriden below",
                            "label": "Person",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 255, "required": False},
                    ),
                    137: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Role", "max_length": 255, "required": False},
                    ),
                    138: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Organization", "max_length": 255, "required": False},
                    ),
                    139: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Contact info", "max_length": 500, "required": False},
                    ),
                    140: (
                        "wagtail.blocks.StreamBlock",
                        [[("tag", 57)]],
                        {"label": "Tags", "required": False},
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("contact", 135),
                                ("link", 83),
                                ("heading_tag", 3),
                                ("name", 136),
                                ("role", 137),
                                ("organization", 138),
                                ("contact_info", 139),
                                ("image", 70),
                                ("tags", 140),
                            ]
                        ],
                        {"group": "Extra components", "label": "Contact card"},
                    ),
                    142: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("card", 134),
                                ("contact_card", 141),
                            ]
                        ],
                        {"label": "Content"},
                    ),
                    143: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("content", 142)]],
                        {"label": "Tab", "max_num": 15, "min_num": 1},
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [[("tabs", 143)]],
                        {"group": "DSFR components", "label": "Tabs"},
                    ),
                    145: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background image", "required": False},
                    ),
                    146: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "Primary colors",
                                    [
                                        ("blue-france", "Blue France"),
                                        ("red-marianne", "Red Marianne"),
                                    ],
                                ),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    147: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "error_messages": {
                                "invalid": "Incorrect color format, must be #fff or #f5f5f5"
                            },
                            "help_text": "This field is obsolete and will be removed in the near future. Replace it with the background color.",
                            "label": "Background color, hexadecimal format (obsolete)",
                            "regex": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            "required": False,
                        },
                    ),
                    148: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                                ("h6", "Heading 6"),
                                ("p", "Paragraph"),
                            ],
                            "help_text": "Adapt to the page layout. Defaults to heading 2.",
                            "label": "Heading level",
                            "required": False,
                        },
                    ),
                    149: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("3", "3/12"),
                                ("4", "4/12"),
                                ("5", "5/12"),
                                ("6", "6/12"),
                                ("7", "7/12"),
                                ("8", "8/12"),
                                ("9", "9/12"),
                            ],
                            "help_text": "The total width of all columns should be 12.",
                            "label": "Column width",
                            "required": False,
                        },
                    ),
                    150: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("card", 134),
                                ("contact_card", 141),
                            ]
                        ],
                        {"label": "Column content"},
                    ),
                    151: (
                        "wagtail.blocks.StructBlock",
                        [[("width", 149), ("content", 150)]],
                        {"group": "Page structure", "label": "Adjustable column"},
                    ),
                    152: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("card", 134),
                                ("column", 151),
                            ]
                        ],
                        {"label": "Columns"},
                    ),
                    153: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("bg_image", 145),
                                ("bg_color_class", 146),
                                ("bg_color", 147),
                                ("title", 2),
                                ("heading_tag", 148),
                                ("columns", 152),
                            ]
                        ],
                        {"group": "Page structure", "label": "Multiple columns"},
                    ),
                    154: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3/12"), ("4", "4/12"), ("6", "6/12")],
                            "label": "Column width",
                        },
                    ),
                    155: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("card", 134),
                                ("contact_card", 141),
                            ]
                        ],
                        {"label": "Items"},
                    ),
                    156: (
                        "wagtail.blocks.StructBlock",
                        [[("column_width", 154), ("items", 155)]],
                        {"group": "Page structure", "label": "Item grid"},
                    ),
                    157: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("image_and_text", 24),
                                ("card", 100),
                                ("tabs", 144),
                                ("item_grid", 156),
                            ]
                        ],
                        {"label": "Content"},
                    ),
                    158: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("bg_image", 145),
                                ("bg_color_class", 146),
                                ("content", 157),
                            ]
                        ],
                        {"group": "Page structure", "label": "Full width background"},
                    ),
                    159: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 1),
                                ("image", 111),
                                ("imageandtext", 24),
                                ("alert", 29),
                                ("text_cta", 39),
                                ("video", 46),
                                ("transcription", 47),
                                ("badges_list", 52),
                                ("tags_list", 58),
                                ("accordions", 62),
                                ("callout", 66),
                                ("highlight", 69),
                                ("quote", 74),
                                ("link", 59),
                                ("tile", 110),
                                ("blog_recent_entries", 120),
                                ("events_recent_entries", 122),
                                ("stepper", 80),
                                ("markdown", 123),
                                ("iframe", 128),
                                ("html", 129),
                                ("separator", 132),
                                ("image_and_text", 24),
                                ("card", 100),
                                ("tabs", 144),
                                ("item_grid", 156),
                            ]
                        ],
                        {"label": "Main content"},
                    ),
                    160: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Side menu title", "required": False},
                    ),
                    161: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Warning: Use HTML block with caution. Malicious code can compromise the security of the site.",
                            "label": "HTML",
                        },
                    ),
                    162: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Parent page"},
                    ),
                    163: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 162)]],
                        {"label": "Page tree"},
                    ),
                    164: (
                        "wagtail.blocks.StreamBlock",
                        [[("html", 161), ("pagetree", 163)]],
                        {"label": "Side menu content"},
                    ),
                    165: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("bg_image", 145),
                                ("bg_color_class", 146),
                                ("main_content", 159),
                                ("sidemenu_title", 160),
                                ("sidemenu_content", 164),
                            ]
                        ],
                        {
                            "group": "Page structure",
                            "label": "Full width background with side menu",
                        },
                    ),
                    166: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "A simple, alphabetical list of the subpages of the current page.",
                            "group": "Website structure",
                            "label": "Subpages list",
                            "template": "content_manager/blocks/subpages_list.html",
                        },
                    ),
                },
                verbose_name="Corps de texte",
            ),
        ),
    ]
