# Generated by Django 5.1.8 on 2025-05-20 13:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0042_alter_reusablecontent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="consigne",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("reusable", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {},
                    ),
                },
            ),
        ),
    ]
