# Generated by Django 5.1.8 on 2025-05-20 13:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0043_produitpage_consigne"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="gender",
            field=models.CharField(default="M"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produitpage",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="consigne",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("reusable", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Texte libre"}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("qfdmd.reusablecontent",),
                        {
                            "label": "Contenu réutilisable",
                            "template": "blocks/reusable.html",
                        },
                    ),
                },
            ),
        ),
    ]
