# Generated by Django 5.1.8 on 2025-05-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0044_produitpage_gender_produitpage_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="gender",
            field=models.CharField(
                help_text="Scelerisque felis dictum nisl parturient parturient quam suspendisse hac habitasse posuere scelerisque in conubia vestibulum a vulputate nunc.Rhoncus rutrum dignissim suspendisse nisi feugiat a sit a sem fermentum aenean mi suspendisse eu sagittis penatibus consectetur et sociosqu mus."
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produit_page",
                to="qfdmd.produit",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="synonyme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produit_page",
                to="qfdmd.synonyme",
            ),
        ),
    ]
