# Generated by Django 5.2.3 on 2025-07-17 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qfdmd", "0044_produitpage_titre_phrase"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS unaccent;

            CREATE TEXT SEARCH CONFIGURATION wagtail_french (COPY = french);
            ALTER TEXT SEARCH CONFIGURATION wagtail_french
              ALTER MAPPING FOR hword, hword_part, word
              WITH unaccent, french_stem;
            """,
            reverse_sql="""
            DROP TEXT SEARCH CONFIGURATION IF EXISTS wagtail_french;
            """,
        ),
    ]
