# Generated by Django 5.1.8 on 2025-05-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0045_alter_produitpage_gender_alter_produitpage_produit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CMSPage",
        ),
    ]
