# Generated by Django 5.2.3 on 2025-07-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0050_bonus_alter_produitpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="bonus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produit_page",
                to="qfdmd.bonus",
            ),
        ),
    ]
