# Generated by Django 5.2.4 on 2025-07-31 13:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0050_bonus_produitpage_disable_bonus_inheritance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpagematieretag",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="produitpagematieretag",
            name="tag",
        ),
        migrations.AlterModelOptions(
            name="reusablecontent",
            options={
                "verbose_name": "Contenu réutilisable",
                "verbose_name_plural": "Contenus réutilisables",
            },
        ),
        migrations.AddField(
            model_name="synonymepage",
            name="titre_phrase",
            field=models.CharField(
                default="",
                help_text="Ce titre sera utilisé dans les contenus réutilisables, pour l'affichage du synonyme de recherche",
                verbose_name="Titre utilisé dans les phrases",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="content",
            field=wagtail.fields.RichTextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="title",
            field=models.CharField(unique=True, verbose_name="Titre"),
        ),
        migrations.DeleteModel(
            name="ProduitPageMarqueTag",
        ),
        migrations.DeleteModel(
            name="ProduitPageMatiereTag",
        ),
    ]
