# Generated by Django 5.2.3 on 2025-07-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0051_produitpage_bonus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonus",
            old_name="montant",
            new_name="montant_min",
        ),
        migrations.AddField(
            model_name="bonus",
            name="montant_max",
            field=models.IntegerField(null=True),
        ),
    ]
