# Generated by Django 5.2.4 on 2025-07-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0051_remove_produitpagematieretag_content_object_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produitpage",
            old_name="produit",
            new_name="legacy_produit",
        ),
        migrations.RenameField(
            model_name="produitpage",
            old_name="synonyme",
            new_name="legacy_synonyme",
        ),
    ]
