# Generated by Django 5.2.4 on 2025-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0052_rename_produit_produitpage_legacy_produit_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="produitpage",
            name="no_produit_and_synonyme_filled_in_parallel",
        ),
        migrations.AddConstraint(
            model_name="produitpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legacy_produit__isnull", True),
                    ("legacy_synonyme__isnull", True),
                    _connector="OR",
                ),
                name="no_produit_and_synonyme_filled_in_parallel",
            ),
        ),
    ]
