# Generated by Django 5.2.4 on 2025-08-19 10:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0052_remove_produitpagemarquetag_content_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reusablecontent",
            name="feminin_pluriel",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Contenu - Féminin pluriel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reusablecontent",
            name="feminin_singulier",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Contenu - Féminin singulier"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reusablecontent",
            name="masculin_pluriel",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Contenu - Masculin pluriel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reusablecontent",
            name="masculin_singulier",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Contenu - Masculin singulier"
            ),
            preserve_default=False,
        ),
    ]
