# Generated by Django 5.2.3 on 2025-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0052_rename_montant_bonus_montant_min_bonus_montant_max"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonus",
            options={"verbose_name_plural": "Bonus"},
        ),
        migrations.AddField(
            model_name="produitpage",
            name="disable_bonus_inheritance",
            field=models.BooleanField(
                default=False, verbose_name="Désactiver l'héritage du bonus"
            ),
        ),
    ]
