# Generated by Django 5.2.4 on 2025-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0053_reusablecontent_feminin_pluriel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="titre_phrase",
            field=models.CharField(
                blank=True,
                help_text="Ce titre sera utilisé dans les contenus réutilisables, pour l'affichage du synonyme de recherche",
                verbose_name="Titre utilisé dans les phrases",
            ),
        ),
        migrations.AlterField(
            model_name="synonymepage",
            name="titre_phrase",
            field=models.CharField(
                blank=True,
                help_text="Ce titre sera utilisé dans les contenus réutilisables, pour l'affichage du synonyme de recherche",
                verbose_name="Titre utilisé dans les phrases",
            ),
        ),
    ]
