# Generated by Django 5.2.4 on 2025-07-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0051_alter_reusablecontent_title"),
        (
            "qfdmd",
            "0053_remove_produitpage_no_produit_and_synonyme_filled_in_parallel_and_more",
        ),
    ]

    operations = []
