# Generated by Django 5.2.5 on 2025-08-26 13:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0053_produitpage_sous_categorie_objet_and_more"),
        ("qfdmo", "0170_update_perimetre_adomicile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="sous_categorie_objet",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="produit_pages", to="qfdmo.souscategorieobjet"
            ),
        ),
    ]
