# Generated by Django 5.2.4 on 2025-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0054_alter_produitpage_titre_phrase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("m", "Masculin"), ("f", "Féminin")],
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="nombre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "singulier"), (2, "pluriel")],
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("m", "Masculin"), ("f", "Féminin")],
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="nombre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "singulier"), (2, "pluriel")],
                verbose_name="Nombre",
            ),
        ),
    ]
