# Generated by Django 5.2.5 on 2025-09-01 15:28

from django.db import migrations
from slugify import slugify


def populate_objet_slug(apps, schema_editor):
    Synonyme = apps.get_model("qfdmd", "Synonyme")
    for synonyme in Synonyme.objects.all():
        synonyme.slug = slugify(synonyme.nom)
        synonyme.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0054_alter_produitpage_sous_categorie_objet"),
    ]

    operations = [
        migrations.RunPython(
            populate_objet_slug, reverse_code=migrations.RunPython.noop
        ),
    ]
