# Generated by Django 5.2.4 on 2025-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0054_merge_20250731_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reusablecontent",
            name="title",
            field=models.CharField(unique=True, verbose_name="Titre"),
        ),
    ]
