# Generated by Django 5.2.5 on 2025-09-02 12:56

import django.db.models.deletion
import django.db.models.functions.datetime
import modelcluster.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0054_alter_produitpage_sous_categorie_objet"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reusablecontent",
            name="content",
        ),
        migrations.RemoveField(
            model_name="reusablecontent",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="reusablecontent",
            name="nombre",
        ),
        migrations.CreateModel(
            name="TemporarySynonymeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonymes",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synnoyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
