# Generated by Django 5.2.5 on 2025-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0054_alter_produitpage_sous_categorie_objet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reusablecontent",
            name="content",
        ),
        migrations.RemoveField(
            model_name="reusablecontent",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="reusablecontent",
            name="nombre",
        ),
    ]
