# Generated by Django 5.2.4 on 2025-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0056_alter_produitpage_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="nombre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "singulier"), (2, "pluriel")],
                null=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="reusablecontent",
            name="nombre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "singulier"), (2, "pluriel")],
                null=True,
                verbose_name="Nombre",
            ),
        ),
    ]
