# Generated by Django 5.2.5 on 2025-09-11 11:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0056_alter_produitpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbedSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backlink_assistant",
                    wagtail.fields.RichTextField(
                        verbose_name="Backlink de l'iframe de l'assistant"
                    ),
                ),
                (
                    "backlink_carte",
                    wagtail.fields.RichTextField(
                        verbose_name="Backlink de l'iframe de la carte"
                    ),
                ),
                (
                    "backlink_formulaire",
                    wagtail.fields.RichTextField(
                        verbose_name="Backlink de l'iframe du formulaire"
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglage des iframes",
            },
        ),
    ]
