# Generated by Django 5.2.4 on 2025-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0057_alter_produitpage_nombre_and_more"),
        ("qfdmo", "0166_update_objets_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="sous_categories",
            field=models.ManyToManyField(
                blank=True, related_name="produit_pages", to="qfdmo.souscategorieobjet"
            ),
        ),
    ]
