# Generated by Django 5.2.5 on 2025-09-23 14:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0060_alter_produit_options_alter_synonyme_options_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyIntermediateProduitPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_produit",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_wagtail_page",
                        to="qfdmd.produit",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche produit",
                "verbose_name_plural": "Fiches produit",
            },
        ),
    ]
