# Generated by Django 5.2.5 on 2025-09-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0062_formpagevalidationsettings"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formpagevalidationsettings",
            options={"verbose_name": "Paramètres des pages de formulaire"},
        ),
        migrations.AlterField(
            model_name="formpagevalidationsettings",
            name="form_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Sélectionnez la page de formulaire utilisée pour le formulaire de contact. qui Celle-ci doit avoir exactement 4 champs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
