# Generated by Django 5.2.7 on 2025-11-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0065_alter_legacyintermediateproduitpage_produit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarysynonymemodel",
            name="page",
        ),
        migrations.DeleteModel(
            name="SynonymePage",
        ),
        migrations.DeleteModel(
            name="TemporarySynonymeModel",
        ),
    ]
