# Generated by Django 5.2.8 on 2025-11-26 16:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0066_remove_temporarysynonymemodel_page_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpage",
            name="legacy_synonyme",
        ),
        migrations.CreateModel(
            name="LegacyIntermediateSynonymePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_synonyme",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "synonyme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_wagtail_page",
                        to="qfdmd.synonyme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche synonyme",
                "verbose_name_plural": "Fiches synonyme",
            },
        ),
    ]
