# Generated by Django 5.2.8 on 2025-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qfdmd",
            "0068_alter_legacyintermediateproduitpagesynonymeexclusion_page_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="produitlien",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="produitlien",
            constraint=models.UniqueConstraint(
                fields=("produit", "lien"), name="unique_produit_lien"
            ),
        ),
    ]
