# Generated by Django 5.2.9 on 2026-01-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0069_alter_produitlien_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitlien",
            name="produit",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="qfdmd.produit",
            ),
        ),
    ]
