# Generated by Django 5.2.9 on 2026-01-22 11:05

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0070_searchtag_taggedsearchtag_produitpage_search_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitpage",
            name="search_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="qfdmd.TaggedSearchTag",
                to="qfdmd.SearchTag",
                verbose_name="Tags",
            ),
        ),
    ]
