# Generated by Django 5.2.9 on 2026-02-05 11:24

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


def create_search_terms_for_synonymes(apps, schema_editor):
    """Create SearchTerm records for existing Synonyme instances."""
    Synonyme = apps.get_model("qfdmd", "Synonyme")
    SearchTerm = apps.get_model("search", "SearchTerm")

    for synonyme in Synonyme.objects.all():
        # Create a SearchTerm for this synonyme
        search_term = SearchTerm.objects.create()
        # Link it to the synonyme
        synonyme.searchterm_ptr = search_term
        synonyme.save(update_fields=["searchterm_ptr"])


def reverse_search_terms_for_synonymes(apps, schema_editor):
    """Reverse: delete SearchTerm records created for Synonyme instances."""
    Synonyme = apps.get_model("qfdmd", "Synonyme")
    SearchTerm = apps.get_model("search", "SearchTerm")

    # Get all searchterm_ptr IDs from synonymes and delete them
    search_term_ids = Synonyme.objects.exclude(searchterm_ptr__isnull=True).values_list(
        "searchterm_ptr_id", flat=True
    )
    SearchTerm.objects.filter(pk__in=list(search_term_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0070_produitpage_est_famille"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTag",
            fields=[
                (
                    "searchterm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchterm",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
            bases=("search.searchterm", models.Model),
        ),
        migrations.AddField(
            model_name="produitpage",
            name="search_variants",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Termes alternatifs permettant de trouver cette page dans la recherche. Ces variantes sont invisibles pour les utilisateurs mais améliorent la recherche. Séparez les termes par des virgules ou des retours à la ligne.",
                verbose_name="Variantes de recherche",
            ),
        ),
        # Step 1: Add searchterm_ptr as nullable field (not as PK yet)
        migrations.AddField(
            model_name="synonyme",
            name="searchterm_ptr",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="search.searchterm",
            ),
        ),
        # Step 2: Populate the field with actual SearchTerm records
        migrations.RunPython(
            create_search_terms_for_synonymes,
            reverse_search_terms_for_synonymes,
        ),
        # Step 3: Remove the old 'id' primary key
        migrations.RemoveField(
            model_name="synonyme",
            name="id",
        ),
        # Step 4: Make searchterm_ptr non-nullable and set as primary key
        migrations.AlterField(
            model_name="synonyme",
            name="searchterm_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="search.searchterm",
            ),
        ),
        migrations.CreateModel(
            name="TaggedSearchTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tags_items",
                        to="qfdmd.produitpage",
                    ),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_produit_page",
                        to="qfdmd.searchtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
        ),
        migrations.AddField(
            model_name="produitpage",
            name="search_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="qfdmd.TaggedSearchTag",
                to="qfdmd.SearchTag",
                verbose_name="Synonyme de recherche",
            ),
        ),
    ]
