# Generated by Django 5.2.9 on 2026-01-29 20:08

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import search.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0070_produitpage_est_famille"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
            bases=(search.mixins.SearchTermSyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TaggedSearchTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tags_items",
                        to="qfdmd.produitpage",
                    ),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_produit_page",
                        to="qfdmd.searchtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
        ),
        migrations.AddField(
            model_name="produitpage",
            name="search_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="qfdmd.TaggedSearchTag",
                to="qfdmd.SearchTag",
                verbose_name="Synonyme de recherche",
            ),
        ),
    ]
