# Generated by Django 5.2.9 on 2026-02-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_searchtag_remove_synonyme_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonyme",
            name="imported_as_search_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, ce synonyme a été importé comme SearchTag et ne devrait plus apparaître dans les résultats de recherche.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_synonymes",
                to="qfdmd.searchtag",
                verbose_name="Importé comme SearchTag",
            ),
        ),
    ]
