# Generated by Django 5.2.9 on 2026-02-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_searchtag_synonyme_inheritance"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtag",
            name="legacy_existing_synonyme",
            field=models.ForeignKey(
                blank=True,
                help_text="Référence vers le synonyme legacy dont ce tag est issu.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_tag_reference",
                to="qfdmd.synonyme",
                verbose_name="Synonyme legacy associé",
            ),
        ),
    ]
