# Generated by Django 5.2.9 on 2026-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_searchtag_synonyme_inheritance"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="search_variants",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Termes alternatifs permettant de trouver cette page dans la recherche. Ces variantes sont invisibles pour les utilisateurs mais améliorent la recherche. Séparez les termes par des virgules ou des retours à la ligne.",
                verbose_name="Variantes de recherche",
            ),
        ),
    ]
