# Generated by Django 5.2.9 on 2026-02-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_searchtag_synonyme_inheritance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpage",
            name="search_term",
        ),
    ]
