# Generated by Django 5.2.9 on 2026-01-22 11:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_alter_produitpage_search_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggedsearchtag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_search_tags_items",
                to="qfdmd.produitpage",
            ),
        ),
    ]
