# Generated by Django 5.2.11 on 2026-02-11 15:32

import django.db.models.deletion
from django.db import migrations, models


def populate_search_term_produit_page(apps, schema_editor):
    ProduitPage = apps.get_model("qfdmd", "ProduitPage")
    for p in ProduitPage.objects.all():
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0072_searchtag_and_synonyme_inheritance"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitPageSearchTerm",
            fields=[
                (
                    "searchterm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="search.searchterm",
                    ),
                ),
                ("searchable_title", models.CharField()),
                (
                    "produit_page",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produit_page_search_term",
                        to="qfdmd.produitpage",
                    ),
                ),
            ],
            bases=("search.searchterm",),
        ),
        migrations.RunPython(populate_search_term_produit_page),
    ]
