# Generated by Django 5.2.9 on 2026-02-09 13:14

import django.db.models.deletion
from django.db import migrations, models


def create_search_terms_for_produit_pages(apps, schema_editor):
    """Create a SearchTerm for each existing ProduitPage."""
    ProduitPage = apps.get_model("qfdmd", "ProduitPage")
    SearchTerm = apps.get_model("search", "SearchTerm")

    for page in ProduitPage.objects.all():
        search_term = SearchTerm.objects.create()
        page.search_term = search_term
        page.save(update_fields=["search_term"])


def delete_search_terms_for_produit_pages(apps, schema_editor):
    """Delete SearchTerms associated with ProduitPages."""
    ProduitPage = apps.get_model("qfdmd", "ProduitPage")
    SearchTerm = apps.get_model("search", "SearchTerm")

    search_term_ids = ProduitPage.objects.filter(search_term__isnull=False).values_list(
        "search_term_id", flat=True
    )
    SearchTerm.objects.filter(id__in=list(search_term_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0072_produitpage_search_variants"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="search_term",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produit_page",
                to="search.searchterm",
            ),
        ),
        migrations.RunPython(
            create_search_terms_for_produit_pages,
            delete_search_terms_for_produit_pages,
        ),
    ]
