# Generated by Django 5.2.9 on 2026-01-22 11:57

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0072_alter_taggedsearchtag_content_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="search_variants",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Variantes de recherche séparées par des virgules ou des retours à la ligne",
                verbose_name="Variantes de recherche",
            ),
        ),
        migrations.AlterField(
            model_name="produitpage",
            name="search_tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="qfdmd.TaggedSearchTag",
                to="qfdmd.SearchTag",
                verbose_name="Synonyme de recherche",
            ),
        ),
        migrations.AlterField(
            model_name="taggedsearchtag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_tags_items",
                to="qfdmd.produitpage",
            ),
        ),
    ]
