# Generated by Django 5.2.9 on 2026-02-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0072_searchtag_legacy_existing_synonyme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpage",
            name="search_variants",
        ),
    ]
