# Generated by Django 5.2.11 on 2026-02-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0071_remove_produitpage_bonus_and_more"),
        ("qfdmd", "0073_remove_produitpage_search_variants"),
    ]

    operations = []
