# Generated by Django 5.2.9 on 2026-01-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0073_produitpage_search_variants_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taggedsearchtag",
            options={
                "verbose_name": "Synonyme de recherche",
                "verbose_name_plural": "Synonymes de recherche",
            },
        ),
        migrations.AlterField(
            model_name="taggedsearchtag",
            name="tag",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_produit_page",
                to="qfdmd.searchtag",
            ),
        ),
    ]
