# Generated by Django 5.2.9 on 2026-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0074_alter_taggedsearchtag_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitpage",
            name="search_variants",
        ),
    ]
