# Generated by Django 5.2.11 on 2026-02-23 13:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0074_synonyme_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="Titre de la page d'accueil",
                    ),
                ),
                (
                    "hero_subtitle",
                    wagtail.fields.RichTextField(
                        blank=True, default="", verbose_name="Sous-titre"
                    ),
                ),
                (
                    "hero_search_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Label du champ de recherche",
                    ),
                ),
                (
                    "icons",
                    wagtail.fields.StreamField(
                        [("image", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.images.blocks.ImageBlock", [], {})},
                        verbose_name="Icônes de la page d'accueil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de la page d'accueil",
            },
        ),
    ]
