# Generated by Django 5.2.11 on 2026-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0074_merge_20260211_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitpage",
            name="migree_depuis_synonymes_legacy",
            field=models.BooleanField(
                default=False, verbose_name="Migration des synonymes effectuée"
            ),
        ),
    ]
