# Generated by Django 5.2.11 on 2026-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qfdmd", "0074_alter_produitindexpage_body_alter_produitpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonyme",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Un synonyme désactivé ne s'affichera nulle partOn le conserve en base de données pour conserver les redirections",
                verbose_name="Désactivé",
            ),
        ),
    ]
