version: 2
models:
  - name: base_ae_unite_legale
    description: Unités légales de l'Annuaire Entreprises (AE)
    columns:
      - name: siren
        description: Numéro SIREN
        data_type: varchar(9)
      - name: activite_principale
        description: Code NAF Rev2
        data_type: string
      - name: etat_administratif
        description: 'État administratif: A = Active, C = Cessée'
        data_type: varchar(1)
      - name: denomination
        description: Dénomination
        data_type: string
      - name: prenom1
        description: Prénom 1 du dirigeant
        data_type: string
      - name: prenom2
        description: Prénom 2 du dirigeant
        data_type: string
      - name: prenom3
        description: Prénom 3 du dirigeant
        data_type: string
      - name: prenom4
        description: Prénom 4 du dirigeant
        data_type: string
      - name: prenom_usuel
        description: Prénom usuel du dirigeant
        data_type: string
      - name: pseudonyme
        description: Pseudonyme du dirigeant
        data_type: string
      - name: nom
        description: Nom du dirigeant
        data_type: string
      - name: nom_usage
        description: Nom d'usage du dirigeant
        data_type: string
  - name: base_ae_etablissement
    description: Établissements de l'Annuaire Entreprises (AE)
    columns:
      - name: siret
        description: Numéro SIRET
        data_type: varchar(14)
      - name: activite_principale
        description: Code NAF Rev2
        data_type: string
      - name: denomination_usuelle
        description: Nom de l'établissement
        data_type: string
      - name: etat_administratif
        description: A = Actif, F = Fermé
        data_type: varchar(1)
      - name: numero_voie
        description: Numéro de voie
        data_type: string
      - name: complement_adresse
        description: 'Complement d''adresse (ex: étage, bâtiment)'
        data_type: string
      - name: type_voie
        description: 'Type de voie (ex: rue, avenue)'
        data_type: string
      - name: libelle_voie
        description: Nom de la voie
        data_type: string
      - name: code_postal
        description: Postal code
        data_type: string
      - name: libelle_commune
        description: Nom de la ville
        data_type: string
