name: Build Parcel Assets

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v4
        name: Cache Parcel build
        id: parcel-cache
        with:
          path: |
            static/compiled
            .parcel-cache
          key: parcel-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('static/to_compile/**/*.css', 'static/to_compile/**/*.ts') }}
          restore-keys: |
            parcel-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('static/to_compile/**/*.css', 'static/to_compile/**/*.ts') }}
            parcel-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            parcel-${{ runner.os }}-

      - name: Build assets if cache missed
        if: steps.parcel-cache.outputs.cache-hit != 'true'
        run: npm run build
