on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  # ci:
  #   name: Intégration continue
  #   uses: ./.github/workflows/_ci.yml

  deploy-django:
    uses: ./.github/workflows/_deploy-on-scalingo.yml
    secrets: inherit # pragma: allowlist secret`
    # needs: [ci]
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: DJANGO_SCALINGO_APP_NAME

  deploy_airflow-webserver:
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    # needs: [ci]
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_SCHEDULER_CLEVERCLOUD_APP_NAME

  deploy_airflow-scheduler:
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    # needs: [ci]
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_WEBSERVER_CLEVERCLOUD_APP_NAME
