on:
  workflow_call:
    inputs:

jobs:
  release:
    name: Release
    needs: [preprod]
    runs-on: "ubuntu-latest"
    # Run only on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
      # - uses: mattermost/action-mattermost-notify@master
      #   with:
      #     MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      #     PAYLOAD: |-
      #       {
      #         "text": "🚨 Nouveau déploiement #${{ github.run_id }} en cours de l'application **${{ vars[inputs.app_name_key] }}**. Déclenché par la [PR #${{ github.event.number }}](https://github.com/incubateur-ademe/quefairedemesobjets/pull/${{ github.event.number }}). [Suivre les logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
      #         "channel": "lvao-tour-de-controle",
      #         "username": "Bipboop le robot de seconde main",
      #         "icon": "https://cdn3.iconfinder.com/data/icons/system-basic-vol-4-1/20/icon-note-attention-alt3-512.png"
      #       }
