on:
  workflow_call:
    inputs:
      container_id:
        type: string
        required: true

jobs:
  deploy_container:
    - name: Deploy container
      run: |
        curl -X POST \
        -H "X-Auth-Token: $SCALEWAY_DEPLOY_KEY" \
        -H "Content-Type: application/json" \
        -d '{}' \
        "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/$CONTAINER_ID/deploy"
      env:
        SCALEWAY_DEPLOY_KEY: ${{ secrets.SCALEWAY_DEPLOY_KEY }}
        CONTAINER_ID: ${{ inputs.container_id }}