name: Install Python webapp dependencies

on:
  workflow_call:
    inputs:
      groups:
        type: string
        description: "Comma-separated groups to install with poetry"
        required: false
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          cache: "pip"

      - name: Install poetry
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-dev-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry sync --with ${{ inputs.groups }} --no-root
