name: "_[Airflow] Déploiement des DAGs"

on:
  workflow_call:
    inputs:
      S3_BUCKET_DESTINATION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_HOST: https://cellar-c2.services.clever-cloud.com
  FOLDER_SOURCE: dags

jobs:
  deploy_dags:
    name: "Déploiement des DAGs dans Clever Cloud"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install AWS CLI dependencies
        run: |
          pip install awscli
      - name: Push to S3 bucket production
        run: aws --endpoint-url ${{ env.S3_HOST }} s3 sync --delete --quiet ${{ env.FOLDER_SOURCE }} ${{ inputs.S3_BUCKET_DESTINATION }}
