name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  python:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3-alpine
        env:
          POSTGRES_USER: qfdmo
          POSTGRES_PASSWORD: qfdmo
          POSTGRES_DB: qfdmo
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 50
        ports:
          - 6543:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: "3.11.4"
      - name: Install GIS Packages
        run: sudo apt-get install gdal-bin
      - name: Install Dependencies
        run: pip install --require-hashes --no-deps -r requirements.txt -r dev-requirements.txt
      - name: Run unit tests
        run: pytest unit_tests
      - name: Run integration tests
        run: pytest integration_tests
      - name: Check code formatting
        run: black --check --diff .
      - uses: chartboost/ruff-action@v1

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Build assets
        run: |
          npm ci
          npm run build

      - name: Check code formatting
        run: npm run lint

      - name: Run tests
        run: npm run test

  deploy:
    needs: [python, node]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-host: ssh.osc-fr1.scalingo.com
          app-name: quefairedemesobjets
