name: "[🟠 Preprod] Déploiement continu"

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  run_tests:
    uses: ./.github/workflows/_run_tests.yml
  deploy:
    name: Deploy on Scalingo
    environment: preprod
    needs: [run_tests]
    uses: ./.github/workflows/_deploy-on-scalingo.yml
    with:
      app: ${{ vars.DJANGO_SCALINGO_APP_NAME }}

  deploy_airflow-webserver:
    name: Deploy PREPROD Airflow webserver on Clever Cloud
    needs: [run_tests]
    environment: preprod
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    with:
      app: ${{ vars.AIRFLOW_WEBSERVER_CLEVERCLOUD_APP_NAME }}

  deploy_airflow-scheduler:
    name: Deploy PREPROD Airflow scheduler on Clever Cloud
    needs: [run_tests]
    environment: preprod
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    with:
      app: ${{ vars.AIRFLOW_SCHEDULER_CLEVERCLOUD_APP_NAME }}

  healthchecks:
    name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v4
    with:
      url: ${{ vars.HEALTHCHECK_URLS }}
      max-attempts: 3
      retry-delay: 5s
      retry-all: true

