name: "[🟠 Preprod] Déploiement continu"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # for test only

defaults:
  run:
    shell: bash

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml

  deploy:
    name: Deploy on Scalingo
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-host: ssh.osc-fr1.scalingo.com
          app-name: quefairedemesobjets-preprod

  deploy_airflow-webserver:
    name: Deploy PREPROD Airflow webserver on Clever Cloud
    needs: [run_tests]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 47ng/actions-clever-cloud@v2.0.0
        with:
          alias: lvao-preprod-airflow-webserver
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}


  deploy_airflow-scheduler:
    name: Deploy PREPROD Airflow scheduler on Clever Cloud
    needs: [run_tests]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 47ng/actions-clever-cloud@v2.0.0
        with:
          alias: lvao-preprod-airflow-scheduler
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
