name: "[🟠 Preprod] Déploiement continu"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  cd:
    uses: ./.github/workflows/_cd.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      environment: preprod
