name: "[🔴 Prod] Déploiement continu"

on:
  push:
    tags:
      - v*

env:
  CC_PROD_AIRFLOW_WEBSERVER_APP: app_efd2802a-1773-48e0-987e-7a6dffb929d1
  CC_PROD_AIRFLOW_SCHEDULER_APP: app_fda5d606-44d9-485f-a1b4-1f7007bc3bec

defaults:
  run:
    shell: bash

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml

  create-release:
    name: Create GitHub Release
    needs: [run_tests]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  deploy:
    name: Deploy on Scalingo
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-host: ssh.osc-fr1.scalingo.com
          app-name: quefairedemesobjets

  deploy_airflow-webserver:
    name: Deploy Airflow webserver on Clever Cloud
    needs: [run_tests]
    runs-on: "ubuntu-latest"
    steps:
      - uses: 47ng/actions-clever-cloud@v2.0.0
        with:
          alias: ${{ env.CC_PROD_AIRFLOW_WEBSERVER_APP }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}


  deploy_airflow-scheduler:
    name: Deploy Airflow scheduler on Clever Cloud
    needs: [run_tests]
    runs-on: "ubuntu-latest"
    steps:
      - uses: 47ng/actions-clever-cloud@v2.0.0
        with:
          alias: ${{ env.CC_PROD_AIRFLOW_SCHEDULER_APP }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
