name: "[LVAO] [🔴 Prod] Déploiement continu"

on:
  push:
    tags:
      - v*

env:
  S3_HOST: https://cellar-c2.services.clever-cloud.com
  FOLDER_SOURCE: dags
  S3_BUCKET_DESTINATION: s3://prod-dags/
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_S3_SECRET_KEY }}

defaults:
  run:
    shell: bash

jobs:
  run_test:
    uses: ./.github/workflows/lvao_tests.yml

  create-release:
    name: Create GitHub Release
    needs: [run_test]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  deploy:
    name: Deploy on Scalingo
    needs: [run_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-host: ssh.osc-fr1.scalingo.com
          app-name: quefairedemesobjets
