name: 🚀 Déploiement continu


on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: 🤖 CI
    uses: ./.github/workflows/_ci.yml

  preprod:
    name: 🟠 Preprod
    uses: ./.github/workflows/_cd-by-environment.yml
    secrets: inherit # pragma: allowlist secret`
    needs: [ci]
    with:
      environment: preprod
