name: "🔴 Déploiement continu | prod"

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  cd:
    name: 🚀 Déploiement continu
    uses: ./.github/workflows/_cd.yml
    with:
      environment: prod
