name: "🛑 Export des Acteurs sous licence ouverte en PROD"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * SUN"

env:
  DUPLICATE_API_TOKEN: ${{ secrets.DUPLICATE_API_TOKEN }}
  PRODUCTION_APP: ${{ secrets.SCALINGO_PRODUCTION_APP }}
  S3_HOST: https://cellar-c2.services.clever-cloud.com
  S3_PRODUCTION_BUCKET: ${{ secrets.LVAO_S3_PRODUCTION_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.LVAO_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LVAO_S3_SECRET_KEY }}

defaults:
  run:
    shell: bash

jobs:
  export_acteur_open_license_preprod:
    name: Export des Acteurs sous licence ouverte en PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Export Displayed Acteur
        uses: ./.github/actions/export_displayedacteur
        with:
          SCALINGO_API_TOKEN: ${{ env.DUPLICATE_API_TOKEN }}
          SCALINGO_APP: ${{ env.PRODUCTION_APP }}
          S3_HOST: ${{ env.S3_HOST }}
          S3_BUCKET: ${{ env.S3_PRODUCTION_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
