name: Build and test

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  run_test:
    uses: ./.github/workflows/run_tests.yml
  deploy_dags:
    uses: ./.github/workflows/push_dags_to_s3.yml
    with:
      s3_bucket_destination: 's3://qfdmo-airflow-dags/ongoing_pr/'
      folder_source: 'dags/'
      s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
      s3_host: https://cellar-c2.services.clever-cloud.com
