on:
  workflow_call:

    inputs:
      s3_bucket_destination:
        type: string
        required: true
        description: 'S3 bucket / folder destination'
      folder_source:
        type: string
        required: true
        description: 'Folder source'

env:
  S3_HOST: https://cellar-c2.services.clever-cloud.com
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}

jobs:
  copy-dags-folder-to-s3:
    name: Copy dags folder to ${{ inputs.s3_bucket_destination }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install AWS CLI dependencies
        run: |
          pip install awscli
      - name: Backup
        run: aws --endpoint-url ${{ env.S3_HOST }} s3 sync --quiet ${{ inputs.folder_source }} ${{ inputs.s3_bucket_destination }}
