on:
  workflow_call:

    inputs:
      s3_bucket_destination:
        type: string
        required: true
        description: 'S3 bucket / folder destination'
      folder_source:
        type: string
        required: true
        description: 'Folder source'


      s3_access_key:
        type: string
        required: true
        description: 'to set AWS_ACCESS_KEY_ID'
      s3_secret_key:
        type: string
        required: true
        description: 'to set AWS_SECRET_ACCESS_KEY'
      s3_host:
        type: string
        required: true
        description: 's3 host'


jobs:
  copy-dags-folder-to-s3:
    name: Copy dags folder to ${{ inputs.s3_bucket_destination }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install AWS CLI dependencies
        run: |
          pip install awscli
      - name: env
        run: |
          export AWS_ACCESS_KEY_ID= ${{ inputs.s3_access_key }}
          export AWS_SECRET_ACCESS_KEY= ${{ inputs.s3_secret_key }}
      - name: Backup
        run: aws --endpoint-url ${{ inputs.s3_host }} s3 sync --quiet ${{ inputs.folder_source }} ${{ inputs.s3_bucket_destination }}
