name: Build and test

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  run_test:
    uses: ./.github/workflows/run_tests.yml

  create-release:
    name: "Create Release"
    needs: [run_test]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  deploy:
    name: Deploy to Production
    needs: [run_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-host: ssh.osc-fr1.scalingo.com
          app-name: quefairedemesobjets
