name: Build and test

on:
  pull_request:

defaults:
  run:
    shell: bash

env:
  S3_HOST: https://cellar-c2.services.clever-cloud.com
  FOLDER_SOURCE: development
  S3_BUCKET_DESTINATION: s3://qfdmo-airflow-dags/preprod/
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}

jobs:
  run_test:
    uses: ./.github/workflows/run_tests.yml
  deploy_dags:
    name: Copy local folder to Preprod s3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install AWS CLI dependencies
        run: |
          pip install awscli
      - name: Push to S3 bucket preprod
        run: aws --endpoint-url ${{ env.S3_HOST }} s3 sync --delete --quiet ${{ env.FOLDER_SOURCE }} ${{ env.S3_BUCKET_DESTINATION }}
