# From https://github.com/marketplace/actions/release-drafter
name: 🔢 Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: 🤖 CI
    uses: ./.github/workflows/ci.yml

  preprod:
    name: 🟠 Preprod
    uses: ./.github/workflows/_cd-by-environment.yml
    secrets: inherit # pragma: allowlist secret`
    needs: [ci]
    with:
      environment: preprod


  # Common release-drafter configuration
  _release_drafter: &release_drafter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Standard release draft update
  update_release_draft:
    <<: *release_drafter
    needs: [preprod]

  # Hotfix-only release draft update
  update_release_draft_for_hotfix:
    <<: *release_drafter
    if: ! (contains("hotfix", github.ref))
