name: 'Terragrunt Lint'
on:
  - pull_request

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@95fc057922e3c3d4cc021a81a213f088f333ddef
        with:
          tg_version: '0.83.2'
          tofu_version: '1.10.3'

      - name: Run Tofu format check
        run: |
          cd infrastructure/
          tofu fmt -recursive -check

# Address actions/missing-workflow-permissions rule in
# code scanning alerts
permissions:
  contents: read